### ISSUE TITLE
azure-documentdb-dotnet-master\samples\rest-from-.net\Program.cs(27,162,27,172): error CS1503: Argument 1: cannot convert from 'System.Uri' to 'string'

### ISSUE THREAD

**Issue by HEDIDIN** [Azure/azure-documentdb-dotnet#105]

**Comment by ryancrawcour** [comment]
Are you sure you are using the correct version of System.Net.Http? 
Solution clearly compiles (and runs) on my machine with the packages pulled from NuGet as per the packages.json file

**Comment by HEDIDIN** [comment]
I open the Rest from NET solution on my machine using VS 2015 Enterprise Update 1
I have ReSharper installed.



System.Net.Http.Primitives and Extensions are separate assemblies than System.Net.Http

System.Net.Http vwersion is 4.0.0.0

**Comment by ryancrawcour** [comment]
Ah, I think that is the problem. System.Net.Http shouldn't be version 4. At least it is not in my solution. 
You should configure your solution as per the packages.json file. 
![untitled](https://cloud.githubusercontent.com/assets/1082796/13832797/da44dafa-eb9c-11e5-85c6-df1bf7503b50.png)

**Comment by ryancrawcour** [comment]
Not sure why v4 would cause a problem, but there must've been a breaking change between v2 and v4. I will look in to this at some stage.
