### ISSUE TITLE
azure-documentdb-dotnet-master\samples\rest-from-.net\Program.cs(27,174,27,179): error CS1503: Argument 2: cannot convert from 'T' to 'System.Net.Http.HttpContent'

### ISSUE THREAD

**Issue by HEDIDIN** [Azure/azure-documentdb-dotnet#106]
`public static class HttpClientExtensions
    {
        public static async Task<HttpResponseMessage> PostWithNoCharSetAsync<T>(this HttpClient client, Uri requestUri, T value) { return await client.PostAsync(requestUri, value, new NoCharSetJsonMediaTypeFormatter()); }
    }
`

**Comment by ryancrawcour** [comment]
Are you sure you are using the correct version of System.Net.Http? 
Solution clearly compiles (and runs) on my machine with the packages pulled from NuGet as per the packages.json file

**Comment by HEDIDIN** [comment]
resolved by importing assembly
