### ISSUE TITLE
azure-documentdb-dotnet-master\samples\rest-from-.net\Program.cs(27,181,27,218): error CS1503: Argument 3: cannot convert from 'REST_from.NET.NoCharSetJsonMediaTypeFormatter' to 'System.Threading.CancellationToken'

### ISSUE THREAD

**Issue by HEDIDIN** [Azure/azure-documentdb-dotnet#107]
`  public class NoCharSetJsonMediaTypeFormatter : JsonMediaTypeFormatter
    {
        public override void SetDefaultContentHeaders(Type type, System.Net.Http.Headers.HttpContentHeaders headers, System.Net.Http.Headers.MediaTypeHeaderValue mediaType)
        { 
            base.SetDefaultContentHeaders(type, headers, new System.Net.Http.Headers.MediaTypeHeaderValue("application/query+json"));
            headers.ContentType.CharSet = "";
        }
    }`

`  //A custom extension of HttpClient that adds a new PostWithNoCharSet async method
    //that uses the custom MediaTypeFormatter class to post with the correct Content-Type header
    public static class HttpClientExtensions
    {
        public static async Task<HttpResponseMessage> PostWithNoCharSetAsync<T>(this HttpClient client, Uri requestUri, T value) { return await client.PostAsync(requestUri, value, new NoCharSetJsonMediaTypeFormatter()); }
    }`

**Comment by ryancrawcour** [comment]
Are you sure you are using the correct version of System.Net.Http? 
Solution clearly compiles (and runs) on my machine with the packages pulled from NuGet as per the packages.json file

**Comment by HEDIDIN** [comment]
Ryan,

The following are screenshots from my machine

This was after restoring the assemblies

[cid:image001.png@01D17FB8.7E8B8D80]
[cid:image002.png@01D17FB8.7E8B8D80]

This is from Updating packages

[cid:image003.png@01D17FB8.7E8B8D80]


This is the results after trying to build the ap

[cid:image004.png@01D17FB8.7E8B8D80]

[cid:image005.png@01D17FB8.D19814D0]

[cid:image006.png@01D17FB8.D19814D0]

[cid:image007.png@01D17FB8.D19814D0]


After installing Microsoft.Net.Http


[cid:image008.png@01D17FB9.A7932250]

To resolve the missing assembly I did this
[cid:image009.png@01D17FBA.8CEB71E0]

I then was able to build the project



Howard S. Ediidn MCTS, MCP
Senior Azure Solution Architect

Microsoft Integration P-TSP
Microsoft Azure Advisory Group
DocumentDB Wizard

100 Menlo Park, Suite 302B, Edison NJ 08837
Office: (732) 474-6844
Cell: (224) 360-3200
Toll Free: (855) VNB CONS
Email : howard.edidin@vnbconsulting.com<mailto:howard.edidin@vnbconsulting.com>
Web : www.vnbconsulting.com<http://www.vnbconsulting.com/>

VNB Consulting Services Inc.
A Microsoft Gold Partner|Tier-1 CSP|CAS Red Carpet Partner
Application Integration I Business Intelligence I CRMOL |Cloud Solutions

_______________________________________________________________________________
Disclaimer: This email and any attachments are sent in strictest confidence for the sole use of the addressee and may contain legally privileged, confidential, and proprietary data. If you are not the intended recipient, please advise the sender by replying promptly to this email and then delete and destroy this email and any attachments without any further use, copying or forwarding

**Comment by ryancrawcour** [comment]
Can't see any of your imges

**Comment by HEDIDIN** [comment]
sent email to you directly
