### ISSUE TITLE
Support use of custom JsonSerializerSettings in SDK

### ISSUE THREAD

**Issue by smartnose** [Azure/azure-documentdb-dotnet#112]
A rather simple code to replace existing document is not working. After fumbling around, I found that the dynamic property value binding seems to be the problem.

My code looks like this:

``` csharp
MyDocument: Document {
    [JsonProperty]
    public string MyValue {get; set; }
}
var myDocument = client.CreateDocumentQuery<MyDocument>(this.collection.SelfLink)
                        .Where(d => d.Id == "myid")
                        .Single();
myDocument.MyValue = "updated"; // Here, the POCO property is updated, but the dynamic property view in the debugger still shows the old value.
client.ReplaceDocument(myDocument);
```

The document is not updated. When debugging through the code, MyValue property in the watch window is updated, but if I clicked into the dynamic value view window, it still shows the old value.

I don't know much about how dynamic object works in C#. For the moment, I just do the following workaround:

``` csharp
MyDocument copy = (dynamic)myDocument;
copy.MyValue = "updated";
client.ReplaceDocument(myDocument.selfLink, copy);
```

It seems to be working fine now.

**Comment by smartnose** [comment]
Ok. Found the root cause: one of my data types has private setter, so serialization didn't happen correctly.

I guess it would be better if DocumentDb accepts a customized JsonSettings.

Hacking the global JsonSettings for now is just a bit too risky.

**Comment by ryancrawcour** [comment]
out of interest, how would customized JsonSettings solve the private setter problem? Is there a setting that allows serialization of private properties?

**Comment by smartnose** [comment]
A customized JsonSetting would allow me to passing a custom contract resolver. See this post

http://patrickdesjardins.com/blog/how-to-have-json-net-deserialize-using-private-constructor-and-private-setter

**Comment by ryancrawcour** [comment]
Right. Good point. Please vote for this ability on UserVoice - https://feedback.azure.com/forums/263030-documentdb/suggestions/6422364-allow-me-to-set-jsonserializersettings

**Comment by ryancrawcour** [comment]
Reopening issue for tracking purposes.

**Comment by FelschR** [comment]
I'm working with inheritance for objects that I store in a DocumentDB collection.
Using a custom JsonConverter seemed like the best way to properly create objects with correct classes when deserializing. Unfortunately I currently cannot use the custom JsonConverter with DocumentDB.
