### ISSUE TITLE
Document not found when using custom ID, works with _rid

### ISSUE THREAD

**Issue by sjwoodard** [Azure/azure-documentdb-dotnet#113]
When I try to read or delete a document using a custom GUID, I get an exception. If I use the document's _rid it works fine.

```
Microsoft.Azure.Documents.NotFoundException
The value 'dbs/xxxxxx==/colls/xxxxxxyyyyyy=/docs/zzzzzz' specified  for query '$resolveFor' is invalid.\r\nActivityId: ...
```

Here's the code:

```
var database = "xxxxxx==";
var collection = "xxxxxxyyyyyy=";
var id = "zzzzzz";
var link = UriFactory.CreateDocumentUri(database, collection, id);
var res = await _client.ReadDocumentAsync(link);
var obj = (T)(dynamic)res.Resource;
return obj;
```

I'm using a new DocumentDB instance and .NET SDK 1.5.3. Thanks.

**Comment by jonathanfishbein1** [comment]
I am also experiencing this issue while using ReplaceDocumentAsync.  Works with the the _rid but not with the user assigned id.

**Comment by rnagpal** [comment]
@sjwoodard CreateDocumentUri methods expects the "id" of the database/collection/document but you seem to be passing the "_rid" to it, so if you pass the "id" property of database/collection to this API, it should work.

@jonathanfishbein1 Are you doing the same mistake? If not, please send me your code sample.

**Comment by jonathanfishbein1** [comment]
@rnagpal I can confirm that passing in the _rid **works** but passing in the id does **not** work.  I am using Azure Functions with F# Here is my code sample below first with the _rid followed by use of the id


This works
` let newUserUri = UriFactory.CreateDocumentUri(databaseId, collectionId, "aJB+ANqlIwC6AQAAAAAAAA==")
        let! newUser = documentClient.ReplaceDocumentAsync(newUserUri, routeProblemNewProblem.currentUser) |> Async.AwaitTask`

Does **Not** Work
 let newUserUri = UriFactory.CreateDocumentUri(databaseId, collectionId, "jonathanfishbein1gmailcom")
        let! newUser = documentClient.ReplaceDocumentAsync(newUserUri, routeProblemNewProblem.currentUser) |> Async.AwaitTask

**Comment by sjwoodard** [comment]
@rnagpal Sorry, this was a year ago, and I'm no longer using DocumentDB. I think @jonathanfishbein1 confirmed what I had found though.

**Comment by ishepherd** [comment]
@rnagpal Is there any progress on this issue?

**Comment by jonathanfishbein1** [comment]
@rnagpal figured it out, CreateDocumentUri needs consistent ids, either all ids or all, _rids for the database, collection, and document.  You can mark this as resolved, although some docs clarifying this may be helpful
