### ISSUE TITLE
Where is the Partitioned Collections Sample?

### ISSUE THREAD

**Issue by RehanSaeed** [Azure/azure-documentdb-dotnet#116]
I'm trying to work out how to use the partitioning now built into the latest versions of DocumentDB. I can't see any samples for how this can be implemented. It's called Partitioned Collections and is described [here](https://azure.microsoft.com/en-us/documentation/articles/documentdb-partition-data/).

[This](https://azure.microsoft.com/en-us/documentation/articles/documentdb-sharding/) page does not mention Partitioned Collections at all and should probably be updated too.

The [SDK Reference](https://msdn.microsoft.com/library/azure/dn948556.aspx) pages also don't tell you anything. No remarks or added information. In particular I'm trying to work out what a partition key is supposed to look like if I want to point to an object within the document.

**Comment by RehanSaeed** [comment]
I found a few snippets of code [here](https://azure.microsoft.com/en-us/documentation/articles/documentdb-partition-data/) in case anybody is looking.

The partition key looks like it's in the format `"/root/element"` and has to be camel-case.

**Comment by rnagpal** [comment]
[This ](https://azure.microsoft.com/en-us/documentation/articles/documentdb-sharding/) link that you mentioned is for the client side partitioning that we had before we introduced server-side partitioning in the latest release. The FAQ for that page has been updated to point folks to server-side partitioning.

>>The partition key looks like it's in the format  "/root/element"  and has to be camel-case
There is no such requirement for the partitionkey to be camel-case.

You can find some sample code for server-side partitioning [here](https://github.com/arramac/azure-documentdb-dotnet/blob/cbef5b2e66bc7d4f0d01a680731f310301cfd9bf/documentdb-partitioning.md ) and also the code samples [here](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/code-samples) have been updated to use server-side partitioning wherever needed.

I've requested to have this page added to Azure/azure-documentdb-dotnet GitHub repo.
