### ISSUE TITLE
Problems querying using CamelCasePropertyNamesContractResolver

### ISSUE THREAD

**Issue by cannehag** [Azure/azure-documentdb-dotnet#122]
I would like to use a general CamelCasePropertyNamesContractResolver for Json.NET.
This works well for serialization/deserialization but not when querying on properties using LINQ since that seems to require the JsonPropertyAttribute.

**Comment by aliuy** [comment]
This appears to be a duplicate of https://github.com/Azure/azure-documentdb-dotnet/issues/55
