### ISSUE TITLE
Cannot execute a stored procedure using a read only key

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-dotnet#123]
If I try to execute a stored procedure using a read only key I get the following exception thrown.

_"The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. ......"
_

I can read query and return documents using this read only key, it only appears to be the stored procedure that has an issue.
The stored procedure only reads data and is used to perform a count.

If I simply swap the read only key for a full access key the problem does not occur.  This exception appears to be similar to that if I try to delete a document when using a read only key

**Comment by shellygms** [comment]
Hi Geetarman, this is by design.  Execute stored procedure require a Read/Write key.

Thanks.
