### ISSUE TITLE
When we can expect the plan to support "netstandard1.5" ?

### ISSUE THREAD

**Issue by rave1502** [Azure/azure-documentdb-dotnet#127]
I have moved my project to Net 2015 RC2 which has depricated dnvm. I have no idea how can I compile my code in newer .Netstandard1.5?

I am getting the following error while adding the component into my project space.
Package Microsoft.Azure.DocumentDB 1.7.1 **is not compatible with netstandard1.5** (.NETStandard,Version=v1.5). Package Microsoft.Azure.DocumentDB 1.7.1 supports: net45 (.NETFramework,Version=v4.5)

Is there any workaround to still use .netframework 4.5 with rc2. Sorry for my ignorance if I am missing anything.

**Comment by pherbel** [comment]
👍  Netstandard support

@rave1502 check this out https://github.com/dotnet/cli/issues/3218

If you have 4.5.1 taget it will works

**Comment by BernieWhite** [comment]
Yes would like to the know timing expectations on support for netstandard 1.5.

**Comment by rswillis** [comment]
Similar question.  I'm porting over some services and noticed that this library had not been updated to dotnet core / netstandard 1.6

"Package Microsoft.Azure.DocumentDB 1.8.0 is not compatible with netcoreapp1.0"

Any thoughts as to when this might be updated or some alternative method of working with DocumentDb in code might be suggested?

thx for the work on this.  I have found it really invaluable.

**Comment by rnagpal** [comment]
@BernieWhite We are currently working on it and should be releasing a preview next month or so. We will target .NET Standard 1.6

**Comment by rnagpal** [comment]
We now support .targetting .Net Standard 1.5 and 1.6. Details
https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-sdk-dotnet-core
