### ISSUE TITLE
Where can I find the release notes for .NET SDK 1.8

### ISSUE THREAD

**Issue by mxa0079** [Azure/azure-documentdb-dotnet#130]
I looked here without success: https://azure.microsoft.com/en-in/documentation/articles/documentdb-sdk-dotnet/

Thanks!

**Comment by rnagpal** [comment]
The documentation is in the process of publishing:

Here is it for now:

•	Added Support for geo-replicated databases and enabled endpoint discovery by default.  User can customize how endpoints are selected for each request by setting the ConnectionPolicy.EnableEndpointDiscovery and ConnectionPolicy.PreferredLocations properties when creating a DocumentClient instance.
•	Added support for retry on throttled requests.  User can customize the number of retries and the max wait time by configuring the ConnectionPolicy.RetryOptions property.
•	Added a new IDocumentClient interface that defines the signatures of all DocumenClient properties and methods.  As part of this change, also changed extension methods that create IQueryable and IOrderedQueryable to methods on the DocumentClient class itself.
•	Added configuration option to set the ServicePoint.ConnectionLimit for a given DocumentDB endpoint Uri.  Use ConnectionPolicy.MaxConnectionLimit to change the default value, which is set to 50.
•	Deprecated IPartitionResolver and its implementation.  Support for IPartitionResolver is now obsolete. It's recommended that you use Partitioned Collections for higher storage and throughput.

**Comment by mxa0079** [comment]
Hello @rnagpal 

I'd suggest to keep this issue open until the documentation is published. Discovery is easier in open issues ;)

**Comment by rnagpal** [comment]
@mxa0079:  It was published yesterday: https://azure.microsoft.com/en-in/documentation/articles/documentdb-sdk-dotnet/
