### ISSUE TITLE
1.8.0 doesn't seem to work with Microsoft.Azure.DocumentDB.TransientFaultHandling

### ISSUE THREAD

**Issue by ronmichael** [Azure/azure-documentdb-dotnet#131]
Maybe I'm doing something wrong... but after upgrading to 1.8.0 I just get this error when trying to execute a query:

> Method not found: 'System.Linq.IQueryable`1<System.Object> Microsoft.Azure.Documents.Linq.DocumentQueryable.CreateDocumentQuery(Microsoft.Azure.Documents.Client.DocumentClient, System.String, Microsoft.Azure.Documents.SqlQuerySpec, Microsoft.Azure.Documents.Client.FeedOptions, System.Object)'.

if I'm using an IReliableReadWriteDocumentClient. Works fine under 1.7.0 and 1.7.1. I'm guessing it has something to do with this change in 1.8.0:

> Added a new IDocumentClient interface that defines the signatures of all DocumenClient properties and methods. As part of this change, also changed extension methods that create IQueryable and IOrderedQueryable to methods on the DocumentClient class itself.

But I'm not sure if there's something I need to change to account for this or if we need to wait for an update to TransientFaultHandling. 

I know the new RetryOptions eliminates some of the need for TransientFaultHandling when it comes to more retries when I'm being throttled (TransientFaultHandling does do that, right?) but it doesn't handle transient network failures (right?).

**Comment by rnagpal** [comment]
@ronmichael : Thanks for reporting this!

We will work on updating TransientFaultHandling package soon to be compatible with .NET SDK 1.8.0

Meanwhile, if you are using the API as:
client.CreateDocumentQuery(collectionLink, querySpec, feedOptions, partitionKey)
Change it to:
client.ExecuteReadAsync(c => c.CreateDocumentQuery(collectionLink, querySpec, feedOptions, partitionKey))

If you were not passing the partitionKey or feedOptions earlier(as they had default optional values = null), the change would look something like:

client.CreateDocumentQuery(collectionLink, querySpec);
to
client.ExecuteReadAsync(c => c.CreateDocumentQuery(collectionLink, querySpec));

Please let me know if that unblocks you in the meantime.

**Comment by rnagpal** [comment]
@ronmichael : On your questions:
TransientFaultHandling provides a more comprehensive way of specifying your retry strategy and also retries on other retryable exceptions.

The RetryOptions introduced in this release allow you to specify the MaxRetryCount and we will internally use the retryafter response header and retry again for MaxRetryCount times. There is also an option to specify the max time you want to wait for throttle(in case retryafter is too large).

.NET SDK 1.8.0 doesn't handles transient network failures yet.

**Comment by rnagpal** [comment]
@ronmichael An update to the TransientFaultHandling package has been pushed(1.3.0) that fixes this issue, so please update it and let us know if that resolves the issue.
