### ISSUE TITLE
Incorrect Parameter Name on ReplaceDocumentAsync

### ISSUE THREAD

**Issue by scottbrady91** [Azure/azure-documentdb-dotnet#134]
Only a minor thing but one of the overloads for ReplaceDocumentAsync has a parameter of documentCollectionUri, with the documentation saying the same thing.

It should be documentUri. Just got caught out by this.

**Comment by rnagpal** [comment]
@scottbrady91 Thanks for pointing that out. I'll get that fixed.

**Comment by rnagpal** [comment]
@scottbrady91 This is fixed now.
