### ISSUE TITLE
The read session is not available for the input session token

### ISSUE THREAD

**Issue by andijakl** [Azure/azure-documentdb-dotnet#141]
In a C# app using the Document DB SDK, we're recently experiencing issues that so far proved to be difficult to consistently reproduce, but do happen from time to time.

The exception thrown by the SDK is "The read session is not available for the input session token".
In the stack trace, it's visible that the BackoffRetryUtility has already executed retries; could it be possible that the session token the gets invalid between retries? Or how can it happen in the SDK that there is an input session token that does not have a read session associated?

The stack trace from the exception:

> ErrorCode: 500
> ErrorMessage: One or more errors occurred. InnerException message: The read session is not available for the input session token. ActivityId: 7eb35e5e-5f96-4354-9c43-00549e516fc8
> Id: 86a6a7bb-a529-4e18-b81d-cd3113bbebb0
> StackTrace: at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
> at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
> at System.Threading.Tasks.Task`1.get_Result()
> at Mwp.Web.MwpService.GetEmployeesInShift() in MwpService.cs:line 507
> at GetEmployeesInShift(DomainService , Object[] )
> at OpenRiaServices.DomainServices.Server.ReflectionDomainServiceDescriptionProvider.ReflectionDomainOperationEntry.Invoke(DomainService domainService, Object[] parameters)
> at OpenRiaServices.DomainServices.Server.DomainService.Invoke(InvokeDescription invokeDescription, IEnumerable`1& validationErrors)
> ----------------------- Start of aggregated exception stacktrace for The read session is not available for the input session token.
> ActivityId: 7eb35e5e-5f96-4354-9c43-00549e516fc8 -----------------------------
> at Microsoft.Azure.Documents.Client.ClientExtensions.<ParseResponseAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.GatewayStoreModel.<>c__DisplayClass10.<<InvokeAsync>b__f>d__12.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__1>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.GatewayStoreModel.<InvokeAsync>d__1e.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.GatewayStoreModel.<ProcessMessageAsync>d__2.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Client.DocumentClient.<ExecuteQueryAsync>d__2f3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Query.DocumentQueryClient.<ExecuteQueryAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteQueryRequestAsync>d__1f.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteOnceAsync>d__9.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<>c__DisplayClass2.<<ExecuteAsync>b__1>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteRetry>d__16.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.BackoffRetryUtility`1.<ExecuteAsync>d__7.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Query.DefaultDocumentQueryExecutionContext.<ExecuteInternalAsync>d__6.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextBase.<ExecuteNextAsync>d__5.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at Microsoft.Azure.Documents.Linq.DocumentQuery`1.<ExecuteNextPrivateAsync>d__15`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> at Mwp.Data.Repositories.DocumentDbRepository`1.<GetItemsAsync>d__37`1.MoveNext() in C:\4.Code\FMWP\FMWP\Develop\mwp\mwp\04-Data\Mwp.Data\Repositories\DocumentDbRepository.cs:line 289
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> at Mwp.Data.Repositories.DocumentDbRepository`1.<GetItemsAsync>d__40.MoveNext() in C:\4.Code\FMWP\FMWP\Develop\mwp\mwp\04-Data\Mwp.Data\Repositories\DocumentDbRepository.cs:line 311
> --- End of stack trace from previous location where exception was thrown ---
> at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
> at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
> at Mwp.Data.Repositories.HumanUserRepository.<GetEmployeesInShift>d__10.MoveNext() in C:\4.Code\FMWP\FMWP\Develop\mwp\mwp\04-Data\Mwp.Data\Repositories\HumanUserRepository.cs:line 78
> ----------------------- End of aggregated exception stacktrace for The read session is not available for the input session token.
> ActivityId: 7eb35e5e-5f96-4354-9c43-00549e516fc8 -----------------------------

The calling code is essentially:

```
        public async Task<IEnumerable<HumanUser>> GetEmployeesInShift()
        {
            var shift = await BasicRepository.GetShift();
            IEnumerable<string> userIds = shift.EmployeesInShift.Select(u => u.Id);
            return await GetItemsAsync(user => userIds.Contains(user.Id));
        }

        public static async Task<IEnumerable<T1>> GetItemsAsync<T1>(Expression<Func<T1, bool>> predicate, string userId = null) where T1 : Resource
        {
            var query = (IDocumentQuery<T1>)GetItemsQuery(predicate, userId);
            var result = await query.ExecuteNextAsync<T1>();
            return result.AsEnumerable();
        }

        protected static IQueryable<T1> GetItemsQuery<T1>(Expression<Func<T1, bool>> predicate, string userId) where T1 : Resource
        {
            return GetItemsQuery<T1>(predicate, userId, null);
        }

        protected static IQueryable<T1> GetItemsQuery<T1>(Expression<Func<T1, bool>> predicate, string userId, FeedOptions fo) where T1 : Resource
        {
            var q = Client.CreateDocumentQuery<T1>(GetCollectionLink(), fo)
                                .Where(predicate)
                                .OfType<T1>()
                                .ForUser(userId);
            System.Diagnostics.Debug.WriteLine(q.ToSql());
            return q;
        }
```

**Comment by mingaliu** [comment]
Hi Andreas ,
   This error "The read session is not available for the input session token" usually indicate the storage system can not satisfy the read/query request with the asked session.  It shouldn't be related to retries.   It usually won't happen with non-geo replicated DocumentDB account.  How often are you observing it? If you can give a more recent ActivityId, it would help me to trackdown the root cause.

Regards,
Ming

**Comment by codecadwallader** [comment]
I've been intermittently experiencing this issue recently as well.  It seems to happen more frequently during nightly operations, where there's heavier periods of usage of the database if that helps (could simply be that more traffic means more potential for error to occur).

I've seen it in two separate app service plans, within two separate DocumentDB instances.

The first is using .NET SDK v1.11.2 and has a single partition.  ActivityId: 6278928c-2532-42f1-af22-45974c4ca45f 

The second is also using .NET SDK v1.11.2 and has multi-partitions.  ActivityId: efdb0603-7af9-44bf-b93e-4093783dff08

I see v1.11.3 was published two days ago, so I'll upgrade to that in case it has a relevant fix.

**Comment by mingaliu** [comment]
Actually SDK v1.11.2 has a bug on this and please upgrade to 11.3 to try. https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/

**Comment by codecadwallader** [comment]
Thanks, I did upgrade to v1.11.3 and I do still see the issue.  Newer ActivityID: 1337f1e3-77f6-4081-a924-70d7ed447f7d

It appears like the issue may be less frequent now, but it's hard to assess since it's intermittent.

**Comment by rnagpal** [comment]
@codecadwallader We will investigate this. By any chance, are you deleting/creating a collection in quick succession with the same name? Can you drop an email to askdocdb@microsoft.com so that we have your direct email if we need any account specific information from you?

**Comment by codecadwallader** [comment]
E-mail sent, and no I'm not deleting/creating collections.

**Comment by rnagpal** [comment]
@codecadwallader We are still investigating and looks like we have a bug here. From our initial investigations, this bug happens in Gateway mode. Can you switch to Direct/TCP and see if that resolves the issue?

**Comment by codecadwallader** [comment]
E-mail sent with overnight logs.  How do I switch modes?

**Comment by rnagpal** [comment]
I see that these logs are from when running in Gateway mode.

Here is how you change the mode/protocol. Let me know if changing to that you still see the issue? We are working on a fix for gateway mode.

DocumentClient client = new DocumentClient(serviceEndpoint, authKey,
new ConnectionPolicy
{
    ConnectionMode = ConnectionMode.Direct,
    ConnectionProtocol = Protocol.Tcp
});

**Comment by codecadwallader** [comment]
Thanks, I see that is recommended in the performance tips as well so I'll switch over to that connection mode.  It's deployed now and I'll check the nightly logs again tomorrow.

**Comment by codecadwallader** [comment]
Yep, switching to Direct/Tcp seems to have resolved the issues for me.  Thanks again.

**Comment by rnagpal** [comment]
@codecadwallader We have fixed this issue in the Gateway mode as well as part of the 1.11.4 released today.

**Comment by kz1000fan** [comment]
@rnagpal I've recently converted a project that was using net451 and DocumentDb SDK 1.19.1 to one that uses netcoreapp2.0 and DocumentDb-netcore-SDK 1.7.1.  I'm seeing this error when running unit tests in the new environment.  Is there a chance that the above-mentioned fix didn't make it into the netcore code path, or could I be running into a separate issue?  Note that the unit tests do indeed drop/re-create the document collection before attempting to insert new documents which is something you asked the OP about -- it would be helpful if you could elaborate on whether/why that might be an issue, thanks!

**Comment by siteshkumar5516** [comment]
Hi guyz I am using SDK -1.17.0 then also I am getting above issue frequently

**Comment by hanvyj** [comment]
I've just ran into this issue after deleting and creating a collection again in quick succession.

**Comment by kirankumarkolli** [comment]
@hanvyj which version of SDK version used?

**Comment by balukantu** [comment]
Hi Team, I still see the same issue with the latest version also with Gateway ConnectionProtocol. It seems the fix is not yet given for Gateway mode. Please confirm.

Also, Can someone let me know why do we get this type of issue(s)?

**Comment by kirankumarkolli** [comment]
@balukantu what's the SDK version used? 
Also is it collection/container re-create scenario?

**Comment by richardhauer** [comment]
I am getting this error when running a query from the web portal:

`select count(1) from c where c._type = 'MyRecord' and startswith( c.id, '90' )`

I thought it might be a connection timeout and refreshed the page (F5) but same result. The collection is very large > 100M documents, not sure that it makes any difference there.

**Comment by nahk-ivanov** [comment]
Same here. I'm using Gremlin API and anytime I'm doing simple `g.V()` - I'm getting this error consistently. There are less than 10 vertices in that graph, so I don't think size is the problem. I'll keep the container intact, in case somebody wants to investigate.
```
The read session is not available for the input session token. ActivityId: d3203369-36bb-4b27-a242-08d0eb95c73c
```
