### ISSUE TITLE
Example project "Queries" fails to build : error CS0122: 'DocumentClientHelper' is inaccessible due to its protection level

### ISSUE THREAD

**Issue by StefH** [Azure/azure-documentdb-dotnet#146]
error CS0122: 'DocumentClientHelper' is inaccessible due to its protection level ?

**Comment by rnagpal** [comment]
@arramac : Can you please look into this?

**Comment by StefH** [comment]
I've to add here that I'm not using the example as is, but copied the source code to a VS2015 .Net Core project which targets net46 and uses Microsoft.Azure.DocumentDB version="1.9.2".

**Comment by rnagpal** [comment]
@StefH : DocumentClientHelper is defined in the Shared project in the solution. Please make sure that you have that project referenced. It's a public class with public static methods.

Not sure if this is related but be don't yet support our .NET SDK in projects targeting .NET Core, so you may run into several issues. Does your current code works if you try it on a VS 2015 Console/Library project targeting net45/net46? If yes, then .NET Core part is the issue which we don't yet support.
