### ISSUE TITLE
SDK does not support .NET Core

### ISSUE THREAD

**Issue by wingfeng** [Azure/azure-documentdb-dotnet#153]
error NU1002: The dependency Microsoft.Azure.DocumentDB 1.9.5 does not support framework .NETStandard,Version=v1.6.

**Comment by jensenkd** [comment]
How is it even possible that this SDK doesn't support .net core.  sigh.

**Comment by rnagpal** [comment]
@wingfeng @jensenkd We are currently working on the .NET Core support for DocumentDB and plan to release in the next couple of months. Will update when it's available as a preview.

**Comment by poimis** [comment]
@mwawrusch If you need to get going now, use MongoDB driver that supports .NET Core: https://mongodb.github.io/mongo-csharp-driver/

https://azure.microsoft.com/en-us/documentation/articles/documentdb-protocol-mongodb/

**Comment by rnagpal** [comment]
@mwawrusch @poimis We are releasing a public preview in next few days!

**Comment by arramac** [comment]
We are excited to announce the preview of the DocumentDB .NET Core SDK, which lets you build fast, cross-platform .NET web applications and services. Please see https://docs.microsoft.com/en-us/azure/documentdb/documentdb-sdk-dotnet-core

**Comment by prajaybasu** [comment]
@arramac Where is the source code ? Is this GitHub "repo" just an issue tracker ? [Only a preview comes after 2 months.. What is the advantage of using this over the MongoDB driver then](url)

**Comment by rnagpal** [comment]
@prajaybasu Yes, currently this GitHub repo is an issue tracker for DocumentDB .NET SDK with no immediate plans to open source it yet in near future. If you were using the .NET Core driver of MongoDB just to talk with DocumentDB, you can get rid of that and instead use this .NET Core SDK for DocumentDB for your app. Let s know if you run into any issue using the SDK.
