### ISSUE TITLE
DocumentDB order-by no document return

### ISSUE THREAD

**Issue by Junfei1101** [Azure/azure-documentdb-dotnet#159]
Recently, i am doing some research on DocumentDB. One phenomenon confuse me when try to apply order-by to query data over one collection.
1.  if not add order-by, then data return normally, however, once appended then no return.
   ![image](https://cloud.githubusercontent.com/assets/22791230/19517587/acb92210-9634-11e6-90e6-b959faa05659.png)
2. Is there anyone know what happen? 

Much appreciate!!~~

**Comment by Junfei1101** [comment]
I did not make any change over the collection FamilyColl, every configuration are keep the default.

**Comment by rnagpal** [comment]
@Junfei1101 We currently don't support Order By queries for partitioned collections when using Query Explorer in Azure portal, so this is expected as of now.
