### ISSUE TITLE
ReadDocumentAsync vs CreateDocumentQuery

### ISSUE THREAD

**Issue by FelschR** [Azure/azure-documentdb-dotnet#167]
Hi, maybe it's a stupid question but I'll ask anyways:

When the goal is to get a single document by id does `ReadDocumentAsync()` have any disadvantages in comparison to `CreateDocumentQuery().Where(d => d.Id == id).AsEnumerable().FirstOrDefault()`?

I'm just wondering because I've seen some projects using the 2nd approach. Even in one of the official samples:
https://github.com/Azure/azure-documentdb-dotnet/blob/master/samples/searchable-todo/src/searchabletodo/Data/DocumentDBRepository.cs

**Comment by arramac** [comment]
You should always use ReadDocumentAsync over a query for simple ID lookups. 

On the server side, a ReadDocumentAsync (GET on REST API) is more lightweight in terms of throughput (RUs) and latency - there's no SQL parsing/compilation/index scans, it's just a direct lookup. They complete in sub-millisecond latency on the server side.

**Comment by FelschR** [comment]
Thanks for clarifying this.
