### ISSUE TITLE
CreateDocumentQuery should be able to pick partial documents

### ISSUE THREAD

**Issue by bpatra** [Azure/azure-documentdb-dotnet#172]
Take the following situation

```
public class LightEntity{
    public string id {get;set;}
    public string LightProp {get;set;}

}

public class FatEntity : LightEntity{
    public string FatProperty {get;set;}
}
```
When requesting DocumentDB with  `CreateDocumentQuery<LightEntity>` the underlying request generated by .NET SDK is `SELECT * FROM` you will then suffer the penalties of retrieving the FatEntity to application server in terms of RUs and request payload.

The only workaround is to recreate manually the projection with a `Select` statement but I believe that reflection should be able to address this directly on the generic type.

This is a feature request following [this stackoverflow question](http://stackoverflow.com/questions/40845441/querying-objects-properties-with-net-documentdb-sdk/40851843#40851843)

**Comment by dennyglee** [comment]
The stackoverflow question has been answered so we're closing this.  DocumentDB supports this.
