### ISSUE TITLE
DocumentDB: issue while adding details to document

### ISSUE THREAD

**Issue by lisapalathingal** [Azure/azure-documentdb-dotnet#182]
@rnagpal: I created a document in documentdb to store details of spaces in a building. The document includes a total of 31000 lines. When I try adding details of new spaces, it displays error message while updating db. When I tried the same function in another document, I was able to add spaces. Could you please let me know what's the issue?

**Comment by rnagpal** [comment]
@lisapalathingal Can you paste the error message you got along with the stack trace? Please also send me the sample code you are using. Can you also let me know the size of the document that contains 31000 lines. There is a limit on the size of the document you can store in documentdb(2MB) and I wanted to make sure you are not exceeding that.

**Comment by lisapalathingal** [comment]
![error message](https://cloud.githubusercontent.com/assets/6519992/21398758/78b5f06a-c75d-11e6-8f34-ae1d25787dd5.png)
[code.txt](https://github.com/Azure/azure-documentdb-dotnet/files/666940/code.txt)

Attached is the code and the error message. I'm not sure how to check the size of document in documentdb. When I check the of a textfile that included the contents in the document, its 3.34 MB. Please let me know if I need to check the size from documentdb.

**Comment by kirankumarkolli** [comment]
MAX allowed document size is 2MB and is mostly the cause here. Try to split it into multiple documents.
