### ISSUE TITLE
Dynamic LINQ support

### ISSUE THREAD

**Issue by FelschR** [Azure/azure-documentdb-dotnet#183]
I'm curious if there are plans to add support for dynamic LINQ.
This would allow using dynamic properties in queries which I'm missing currently.

It was asked here (and strangely marked as completed):
https://feedback.azure.com/forums/263030-documentdb/suggestions/6805221-dynamic-linq-support-for-documentdb

**Comment by kirankumarkolli** [comment]
This feature was delivered

**Comment by kieronlanning** [comment]
@kirankumarkolli Is there a sample for this? I can't seem to get it working or find and docs that successfully combine either dynamic LINQ + typed LINQ or SqlQuerySpec + typed LINQ.

**Comment by Laumania** [comment]
I'm listening in on this one, as I'm looking for the same.

**Comment by Laumania** [comment]
@kirankumarkolli 

> This feature was delivered

Where? Sample please.

**Comment by jonathanfishbein1** [comment]
I'm getting the same error described here 

https://github.com/Azure/azure-documentdb-dotnet/issues/173
