### ISSUE TITLE
Updating from 1.10 to 1.11 and using TransientFaultHandling package

### ISSUE THREAD

**Issue by nhwilly** [Azure/azure-documentdb-dotnet#188]
Anyone else having trouble with this?

DocumentDB client library 1.10 works with TransientFaultHandling  1.4.

Upgrading to 1.11 upgrades TransientFaultHandling to 1.5.

I get errors about unable to find assembly 1.10 when I use AutoFac to resolve the reliable client.  

`            builder.RegisterInstance( _documentDbClient ).As<IReliableReadWriteDocumentClient>();
`

If I back it down to 1.10, everything seems fine again.

**Comment by rnagpal** [comment]
@nhwilly It's the other way round: Updating TransientFaultHandling to 1.5 upgrades DocumentDB SDK to 1.11. Do you still Microsoft.Azure.DocumentDB.1.10.0 folder under packages dir of your solution? If yes, this might not have been upgraded properly. Try force deleting it from Nuget Package Manager and then install 1.11

Let me know if that helps!

**Comment by nhwilly** [comment]
That got it.  Working now.  Thanks!
