### ISSUE TITLE
Run emulator in containers

### ISSUE THREAD

**Issue by galvesribeiro** [Azure/azure-documentdb-dotnet#193]
Hello,

What would take to have DocumentDb Emulator to run in a Windows Container? It would be good if we have a .zip package deployment instead of a MSI so we can run it from a `microsoft/windowsservercore` container, and even better (and lightweight) if we could run it on a `microsoft/nanoserver` container.

What can we do to have it to work? Any plans on support it? Any ETA?

Thanks, that would be really helpful to support. 

Thanks!
Gutemberg

**Comment by rnagpal** [comment]
@galvesribeiro We’re working on a Windows container for the emulator (currently based on windowsservercore).  The timeframe is about 2-3 weeks.

**Comment by galvesribeiro** [comment]
@rnagpal thanks for get back. Will track this issue to follow up.

Thanks!

**Comment by jplane** [comment]
Any updates on this? I've seen a few recent references to running the emulator in a Windows container... has someone published a Docker image yet?

**Comment by galvesribeiro** [comment]
@rnagpal any news?

**Comment by erichexter** [comment]
I just got an email from Azure and one of the headlines was DocumentDb Emulator in Docker.  But there were no details to it in the email other then the headlines. 

![image](https://cloud.githubusercontent.com/assets/114692/24731464/df445540-1a2f-11e7-9fd4-af90cd783995.png)

**Comment by mimig1** [comment]
Emulator in Docker is now available - https://docs.microsoft.com/en-us/azure/documentdb/documentdb-nosql-local-emulator#running-on-docker-for-windows. 
@erichexter - Sorry for the delay in updating the documentation.  
@rnagpal - Can you update the labels on this issue?

**Comment by galvesribeiro** [comment]
Sadly, it is only for Windows :(

**Comment by galvesribeiro** [comment]
I wonder why it was closed if it is just for windows... Beats the purpose of the container and this issue... To be clear, I'm editing the issue description to cover that...

**Comment by YohanSciubukgian** [comment]
Even if the issue has been closed last year, do you plan to support Linux Containers ?
