### ISSUE TITLE
Can't start documentdb emulator, error: "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing on you computer"

### ISSUE THREAD

**Issue by mindis** [Azure/azure-documentdb-dotnet#195]
Hi,

Installed but can't start documentdb emulator

Error: "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing on you computer"

OS: Windows 7 Enterprise, Service Pack 1

**Comment by rnagpal** [comment]
@mindis We have the following requirement for DocumentDB Emulator, so it's not supported on Windows 7.

Software requirements
Windows Server 2012 R2, Windows Server 2016, or Windows 10

**Comment by rnagpal** [comment]
If you absolutely want emulator support on Windows 7, please vote on https://feedback.azure.com/forums/263030-documentdb/suggestions/17825839-add-emulator-support-for-windows-7-8
