### ISSUE TITLE
Not compatible with net461

### ISSUE THREAD

**Issue by tachev** [Azure/azure-documentdb-dotnet#201]
I'm using Service fabric that adds a dependency on net461.

That's the error I'm getting, because of that:

Package Microsoft.Azure.DocumentDB.Core 1.0.0 is not compatible with net461 (.NETFramework,Version=v4.6.1) / win7-x64. Package Microsoft.Azure.DocumentDB.Core 1.0.0 supports: netstandard1.6 (.NETStandard,Version=v1.6)
One or more packages are incompatible with .NETFramework,Version=v4.6.1 (win7-x64).

**Comment by mingaliu** [comment]
Please use Microsoft.Azure.DocumentDB full framework version https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/.  We will merge the nuget package for both.

**Comment by tachev** [comment]
Thanks! It may be good to update the getting started documentation.

**Comment by rnagpal** [comment]
@tachev I see that we have this documented in our Getting started article for .NET SDK: https://docs.microsoft.com/en-us/azure/documentdb/documentdb-get-started as
_"Within the results, find Microsoft.Azure.DocumentDB and click Install. The package ID for the DocumentDB Client Library is Microsoft.Azure.DocumentDB."_

Please let us know where do you think it would be useful to document.

Also note that in our main page for .NET SDK download, we have specified as below:
Current supported framework: Microsoft .NET Framework 4.5
/cc: @mimig1

**Comment by tachev** [comment]
Im using the dotnet core docs
Within the results, find Microsoft.Azure.DocumentDB.Core and click Install. The package ID for the DocumentDB Client Library is Microsoft.Azure.DocumentDB.Core

Get Outlook for iOS




On Tue, Feb 7, 2017 at 9:34 AM -0500, "Rajesh Nagpal" <notifications@github.com> wrote:












@tachev I see that we have this documented in our Getting started article for .NET SDK: https://docs.microsoft.com/en-us/azure/documentdb/documentdb-get-started as

"Within the results, find Microsoft.Azure.DocumentDB and click Install. The package ID for the DocumentDB Client Library is Microsoft.Azure.DocumentDB."


Please let us know where do you think it would be useful to document.


Also note that in our main page for .NET SDK download, we have specified as below:

Current supported framework: Microsoft .NET Framework 4.5

/cc: @mimig1

**Comment by rnagpal** [comment]
@tachev : Please take a look at https://github.com/Microsoft/azure-docs-pr/pull/5898 if that's what you expected in the documentation. Feel free to add comments to that PR and I'll address them.

**Comment by rnagpal** [comment]
@tachev In case you are not able to view the above PR, here is what I have changed it to:

_The package ID for the DocumentDB Client Library for .NET Core is [Microsoft.Azure.DocumentDB.Core](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core). If you are targetting a .NET Framework version(like net461) that is not supported by this .NET Core Nuget package, then use [Microsoft.Azure.DocumentDB](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB) that supports all .NET Framework versions starting .NET Framework 4.5._

**Comment by rnagpal** [comment]
Updated the documentation.

**Comment by spelltwister** [comment]
Let us say that I have a netstandard lib that uses Microsoft.Azure.DocumentDB.Core.  I have a full framework unit test that references the netstandard lib which cannot install Microsoft.Azure.DocumentDB.Core, but installing Microsoft.Azure.DocumentDB gives a missing reference error where the test is looking for DocumentDB.Core.  Is there a way to use redirects or similar to get this to work?
