### ISSUE TITLE
client transaction question

### ISSUE THREAD

**Issue by CodingCat** [Azure/azure-documentdb-dotnet#204]
in https://github.com/Azure/azure-documentdb-dotnet/blob/063d65dbf7f0fca6d14913ddf2cf6c06034c4ded/samples/clientside-transactions/DocDBClientBulk/DocDBClientBulk/Program.cs#L93

What will happen when delete itself failed?

**Comment by rnagpal** [comment]
@CodingCat If you look here: https://github.com/Azure/azure-documentdb-dotnet/blob/063d65dbf7f0fca6d14913ddf2cf6c06034c4ded/samples/clientside-transactions/DocDBClientBulk/DocDBClientBulk/Program.cs#L115 we would throw the exception up in case InvokeBulkDeleteSproc failed. Does that answers your question?

/cc: @arramac

**Comment by rnagpal** [comment]
@CodingCat Please confirm so that I can close the issue.

**Comment by CodingCat** [comment]
Sure, thanks for the reply
