### ISSUE TITLE
GeometryOperationExtensions support for "ST_Intersects"

### ISSUE THREAD

**Issue by lawrencegripper** [Azure/azure-documentdb-dotnet#206]
Currently the extensions has Distance, IsValid and Within

We'd really like to be able to use Intersects!

**Comment by kanshiG** [comment]
Thanks Lawrence - we have intersect for polygons - does that help. https://docs.microsoft.com/en-us/azure/documentdb/documentdb-geospatial

**Comment by lawrencegripper** [comment]
Thanks for the quick reply, sorry for my brief description above was it a bit of rush. 

We're using the LINQ provider to query the DocDB database, in the LINQ provider there is an implementation of Within, on the GeometryOperationExtensions object, but it doesn't currently have an intersects implementation. 

Depending on ETA of the source code I could attempt to create pull request adding this in. If not would be great to get it added into the SDK. Will reach out over email to Govindk too

**Comment by kanshiG** [comment]
Thanks for your time Lawrence,
              This is definitely on the backlog for support in LINQ.

Regards
Govind

**Comment by lawrencegripper** [comment]
Thanks, that's great news, can you give any rough ideas of timelines?

**Comment by rnagpal** [comment]
@lawrencegripper This will be fixed in our next update to the SDK which is sometimes next week.

**Comment by rnagpal** [comment]
@lawrencegripper This has been fixed in 1.12.1 version of the SDK. Please confirm.

**Comment by lawrencegripper** [comment]
Thanks, I'll look to update the SDK and test later this week.
