### ISSUE TITLE
Can DocumentDB run in windows8.1?

### ISSUE THREAD

**Issue by Eric-mingjie** [Azure/azure-documentdb-dotnet#218]
My system is windows8.1. When I use the DocumentDB emulator, same issue as 
[https://github.com/Azure/azure-documentdb-dotnet/issues/185](url) also appeared.
I see that in the offcial website, the system requirement is windows 10 or windows server 2012. So I am wondering if the problem is due to my system problem and whether I need to install windows 10 on my PC.

**Comment by rnagpal** [comment]
@Eric-mingjie Yes, The emulator is supported on Windows10 and above.

**Comment by Eric-mingjie** [comment]
My problem is solved now. Thanks very much.
