### ISSUE TITLE
Is the Change Feed Processor library production ready?

### ISSUE THREAD

**Issue by joeizy** [Azure/azure-documentdb-dotnet#224]
Hello! I'm looking to use the DocumentDB Change Feed to handle updating related documents - such as denomalized objects. I saw the [Change Feed Processor library](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/ChangeFeedProcessor) and wanted to know if it was **production ready** or actually just a sample.

The EventHubs team has the production ready [Microsoft.Azure.EventHubs.Processor](https://www.nuget.org/packages/Microsoft.Azure.EventHubs/) package explained in the docs [(EventProcessorHost Docs)](https://docs.microsoft.com/en-us/azure/event-hubs/event-hubs-dotnet-standard-getstarted-receive-eph) to assist with the same types of things the Change Feed Processor library does.

Thanks!

**Comment by mkolt** [comment]
Hello, yes, ChangeFeedProcessor library is prodiction ready and it already used in production by a number of projects.
Thanks!

**Comment by skram-softheme** [comment]
@mkolt thanks for great library, it really helps us a lot. Btw, why not to publish it as nuget?

**Comment by mkolt** [comment]
Thanks! We are working on making it part of DocumentDB .NET SDK.

**Comment by joeizy** [comment]
Thank you! Nuget package would be awesome! Love the regular updates and major progress DocumentDB, excuse me, CosmosDB :) has made over the last couple years!! Can't wait for Azure function support for changefeed so we don't need to use this library anymore.

**Comment by DaveAurionix** [comment]
@mkolt Any rough date for when the [official public Nuget](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/) feed of the CosmosDB .NET SDK is likely to include the Change Feed Processor features?

**Comment by mkolt** [comment]
No specific ETA, but there is good change this should be soon

**Comment by ealsur** [comment]
@DaveAurionix @joeizy The Change Feed Processor is not available as a [nuget package](https://docs.microsoft.com/azure/cosmos-db/documentdb-sdk-dotnet-changefeed).

**Comment by DaveAurionix** [comment]
Thank you!
