### ISSUE TITLE
Expose the JSON serialization settings.

### ISSUE THREAD

**Issue by RemyArmstro** [Azure/azure-documentdb-dotnet#229]
There is a community suggestion with almost 850 votes regarding this, but I just noticed there is no actual issue related to it open.  That surprised me.  The fact there is no convenient way to change the JSON serialization settings (without affecting the default behavior of your entire app), is causing a lot of people pain.

Edit: Now close to 950 votes.

**Comment by mcbridedm** [comment]
Please PLEASE get on this feature.  It seems rather ridiculous to not be there already.

**Comment by BowserKingKoopa** [comment]
Still struggling with this.

**Comment by benaiahjohn** [comment]
Please do this ASAP. Need this badly

**Comment by BowserKingKoopa** [comment]
I've had to wrap the DocumentDB api and wrest control of serialization away from it completely in order to get my objects to serialize/deserialize the way I want. And the api fights you the whole way because it really wants to be the one to do the serialization.

**Comment by kieronlanning** [comment]
+1

**Comment by carlos-sarmiento** [comment]
+1

**Comment by bergey** [comment]
The other thread mentioned by the OP seems to be https://feedback.azure.com/forums/263030-documentdb/suggestions/6422364-allow-me-to-set-jsonserializersettings

**Comment by RemyArmstro** [comment]
Yes, thank you.  Not sure why I didn't post the link when I mentioned it.  Bad OP.

**Comment by nhwilly** [comment]
me, too.  me, too.

**Comment by rnagpal** [comment]
We are currently working on this.

**Comment by nhwilly** [comment]
Great news!!!

**Comment by ahmedabadawi** [comment]
As a workaround, I had to wrap the entity being saved in another object with public accessors for the properties needed for searching and save the entity as a string serialized with a custom JSON Serialization options to allow instantiation from a private constructor or use private setters

**Comment by mcbridedm** [comment]
The sdk can return doc as string directly

**Comment by ahmedabadawi** [comment]
The use-case I was working on, is that I want to search by two attributes on the document and retrieve the whole document matching those criteria. So basically I made a wrapper class that exposes the two attributes used in the search and serialized the rest of the document as string inside that wrapper document

**Comment by kieronlanning** [comment]
How are away is this at the moment? Struggling without custom JSON serialization options at the moment.

**Comment by acollard** [comment]
Looks like this is now in 1.15.0 for .Net Framework. https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-sdk-dotnet#release-notes

Hoping this makes it into .Net Core soon.

**Comment by kieronlanning** [comment]
Thanks @acollard. Is there a timeframe for the .NET Core version?

**Comment by Liversage** [comment]
In the [Microsoft.Azure.DocumentDB 1.15.0 NuGet package](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/1.15.0) you can now provide your own `JsonSerializerSettings` when creating a `DocumentClient`. 👏

However, I ran into a problem and as there seem to be no good way to report CosmosDB issues I instead provide the information here as it might be useful to someone else.

If your document class derives from `Microsoft.Azure.Documents.Document` then the provided `JsonSerializerSettings` will **NOT** be used for serialization and deserialization.

**Comment by kieronlanning** [comment]
This is now a closed issue according to UserVoice (https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6422364-allow-me-to-set-jsonserializersettings?tracking_code=416a22ac7904c38f34440fe7c6ee9e55).

I've tried e-mailing the team, leaving feedback, but no-one is getting back to me on when the .NET Core version will get this support.

At this point, I'm having to move away from DocumentDb.

**Comment by rnagpal** [comment]
@kieronlanning We have fixed this for .NET Core and will be doing a releasing in next few days.

**Comment by kieronlanning** [comment]
Splendid, thanks @rnagpal.

**Comment by rnagpal** [comment]
@kieronlanning This is part of .NET Core 1.4.0 released today.

@Liversage : I'm closing this issue as this tracked the support of JsonSerializerSettings in the SDK. Would you mind creating a separate issue for the bug you found so that it can be tracked separately?

**Comment by kieronlanning** [comment]
That's great - updated and it's working as it's expected.

Thanks @rnagpal.
