### ISSUE TITLE
Package restore failing for latest document db sdk version 1.13.1

### ISSUE THREAD

**Issue by avantiajay** [Azure/azure-documentdb-dotnet#247]
HI all,
I have installed the latest the documentdb sdk from Nuget. The solution is building perfectly fine from my local machine. But when I try to build the solution from VSTS which is is using nuget version 3.3 and VS 2017. I am getting the below error : 

This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them. For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.Azure.DocumentDB.1.13.1\build\Microsoft.Azure.DocumentDB.targets.

I have tried ignoring the targets files by modifiying the csproj but it doesnt help.

**Comment by alexbransky** [comment]
I'm having the same issue, haven't been able to figure it out.

**Comment by rnagpal** [comment]
@avantiajay @alexbransky Do you see the import of the .targets file in your .csproj once you have installed the package. If yes, can you paste the contents of the import statement for the .targets file?
I'm assuming you are using "Manage Nuget Packages" option to install the DocumentDB package. Do you see the Microsoft.Azure.Documents.Client.dll in your local packages folder and other native dlls? Or you are only missing the .targets file in the build folder?

**Comment by alexbransky** [comment]
I had to edit the csproj file and remove the Import references to
DocumentDB at the bottom, and then update the project to .Net 4.6.2, and
then it worked.

**Comment by rnagpal** [comment]
@alexbransky That doesn't seems correct. Your app will fail on running queries as those native dlls are needed at runtime when executing queries. Can you tell me whether the .targets files was not downloaded as part of your nuget package referencing in your project(under build sub-folder)? Did the native dlls got downloaded(under runtimes\win7-x64\native)? Are you also seeing this on VS 2017/Nuget 3.3?
