### ISSUE TITLE
Method 'Count' is not supported

### ISSUE THREAD

**Issue by dagus** [Azure/azure-documentdb-dotnet#248]
Hi,

I am trying to use the aggregation Count with LINQ on a property of a customtype that is in a List.

Code e.g: 
public List<CustomType> CustomTypes;

public class CustomType
 {
      public string Type1 { get; set; }
      public string Type2 { get; set; }
 }

Linq e.g:
(x => x.CustomTypes..Count(t => t.Type1 == "sample") > 0)

The query above throws the following exception:
"ExceptionMessage": "Method 'Count' is not supported.

I am using 1.13.1 of Microsoft.Azure.DocumentDB.

Best Regards /
Daniel

**Comment by kirankumarkolli** [comment]
@dagus  as error states Count on sub parts is not supported.
