### ISSUE TITLE
Document selflink

### ISSUE THREAD

**Issue by kh771** [Azure/azure-documentdb-dotnet#251]
Hi

I'm working on a query to update a document in the database and noticed that if I use a defined query

`string strQuery = "SELECT c.Name,c.Index,c.Connected,c.ReadDate,c.TimeOffset FROM c where c.Name ='" + name + "'";`
`Document result = client.CreateDocumentQuery(coll.SelfLink, new SqlQuerySpec(strQuery)).AsEnumerable().FirstOrDefault();`

the result has no selflink or any other document attributes.

if I change to

`string strQuery = "SELECT * FROM c where c.Name ='" + name + "'";`

all document attributes are present.

The results in dynamic view are correct in both cases.

Why does defining query result in document attributes are null?

/Br

**Comment by kirankumarkolli** [comment]
@kh771 explicit projection limits to what is requested. 
Selflink can be projected by "._self" column/property
