### ISSUE TITLE
TCP mode performing HTTP requests?

### ISSUE THREAD

**Issue by davenewza** [Azure/azure-documentdb-dotnet#258]
Looking at the metrics of our CosmosDB service I can see that it is processing HTTP requests. In fact, the total number of HTTP 2XXs is equal to the total number of requests, leading me to believe that the client is somehow performing HTTP requests to the CosmosDB service (as if it is configured to use the HTTP protocol) and not a TCP direct connection.

![image](https://cloud.githubusercontent.com/assets/6212830/25992193/1f2a1e68-3706-11e7-9582-6d43184268e4.png)

The `DocumentClient` singleton is configured as such:
```csharp
client = new DocumentClient(uri, key, new ConnectionPolicy
{
    MaxConnectionLimit = 1000,
    ConnectionMode = ConnectionMode.Direct,
    ConnectionProtocol = Protocol.Tcp
});
```

This is a dotnet core project, using the  Microsoft.Azure.DocumentDB 1.14.0 and Microsoft.Azure.DocumentDB.Core 1.3.0 SDKs.

**Comment by rnagpal** [comment]
@davenewza The status code of the response is always reported in the form of http status codes irrespective of the connection policy chosen. If you run this from a local machine you can confirm this by using Fiddler. You will not see any traffic in fiddler(apart from the first few initialization related requests that have to always go through Gateway). Only when you change the ConnectionMode to Gateway, you will see fiddler traffic. Let me know if that answers your question.

Also, MaxConnectionLimit applies only in Gateway mode, so if you are using Direct TCP mode, you can remove setting that property.

Question for you: Is there a reason for you to use both .NETFX(1.14.0) and NET Core SDK(1.3.0) in the same solution?

**Comment by davenewza** [comment]
@rnagpal thanks for the answer. I clearly misunderstood. I assumed that TCP under direct mode would not use HTTP at all (but rather sockets or something of the sort).

Yes, removing `MaxConnectionLimit`. Using both packages was a mistake - thanks for pointing this out.

**Comment by davenewza** [comment]
Oh, wait. Are you saying that it won't actually use HTTP, but it will be reported (in the portal) as HTTP requests?

**Comment by kirankumarkolli** [comment]
@davenewza HTTP status codes are used for reporting purpose across all connection protocols (including TCP).
