### ISSUE TITLE
Getting exception while calling RegisterObserverAsync method of Change feed processor library

### ISSUE THREAD

**Issue by jharajeev** [Azure/azure-documentdb-dotnet#275]
I am trying to use the Azure Cosmos DB change feed processor library. While calling RegisterObserverAsync method, I am getting an exception **"PartitionKey value must be supplied for this operation."**. How do I supply the PartitionKey value? I don't see the API accepting any such parameter.

**Comment by JonasGranlund** [comment]
You can get the pkRange from ReadPartitionKeyRangeFeedAsync,  here are two pages that show a little regarding this: 
https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed
https://docs.microsoft.com/en-us/azure/cosmos-db/change-feed-hl7-fhir-logic-apps

**Comment by jharajeev** [comment]
Yes, ReadPartitionKeyRangeFeedAsync works but I was trying to register a ChangeFeedObserver provided by Change feed processor library but while calling the register API ChangeFeedEventHost.RegisterObserverAsync, I am getting the exception.

**Comment by mkolt** [comment]
Can you provide stack trace for the exception?<br>
Thanks!
