### ISSUE TITLE
Storage capacity

### ISSUE THREAD

**Issue by RaleS** [Azure/azure-documentdb-dotnet#279]
When adding a new collection in Azure portal, **Storage capacity** option can be set to either **Fixed (10GB)** or **Unlimited***.
 
How to specify **Storage capacity** when creating a collection with the SDK?

It seems that collections created with the SDK are defaulted to **Fixed**?

**Comment by rnagpal** [comment]
@RaleS Using the .NET SDK, if you have specified Throughput to be < 2500, we create a single partition(Fixed - 10GB). If you specify Throughput >=2500, we will create what is called a partitioned collection that can scale indefinitely as your storage increases. Through the SDK we allow you do create a collection upto 100GB but if you need to create a collection larger than that we can help you creating one by filing an Azure Support ticket.

Please let me know if that answers your question and if you have any other query.

**Comment by adampbrown** [comment]
The behaviour of creating a collection with a storage capacity of **Unlimited** when supplying an Offer Throughout >= 2500 no longer seems to apply. My calls to CreateDocumentCollectionIfNotExistsAsync() that supply a Throughout of 3000 have recently started to create a **Fixed** collection! 

What is the recommended way of creating an *Unlimted* collection via the SDK?
