### ISSUE TITLE
Graph property - lowercase L converted to uppercase

### ISSUE THREAD

**Issue by ChrisMiskowiec** [Azure/azure-documentdb-dotnet#280]
When I attempt to set a string property value containing any digit followed by a lowercase "l", the "l" gets converted to uppercase ("L"). Here is an example using TinkerPop Gremlin Console:

```
gremlin> :> g.addV('random').property('id', 'test2').property('value', '3l')
==>[id:test2,label:random,type:vertex,properties:[value:[[id:a7a4201c-63d0-440e-8553-e0fb78f85c68,value:3L]]]]
gremlin> :> g.V('test2').values('value')
==>3L
gremlin> :> g.addV('random').property('id', 'test3').property('value', '1a1b1c1d1e1f1g1h1i1j1k1l1m1n1o1p1q1r1s1t1u1v1w1x1y1z')
==>[id:test3,label:random,type:vertex,properties:[value:[[id:0da1b3f1-391a-4b70-a729-9ba3cf0ed031,value:1a1b1c1d1e1f1g1h1i1j1k1L1m1n1o1p1q1r1s1t1u1v1w1x1y1z]]]]
```

The same issue also occurs from Microsoft.Azure.Graphs Nuget package, Gremlin.NET Nuget package, and even in the Azure Portal Data Explorer.

This is a serious issue - we should be able to trust a data store to not alter the data being stored.

**Comment by dennyglee** [comment]
Thanks @ChrisMiskowiec - sorry about this bug.  We have already validated a fix for this and we will be deploying this in the next week or so.  In the interim, please do not hesitate to ping me if you have any questions.  Will close this issue _after_ we have confirmed the fix has been deployed.

**Comment by ashwini-ms** [comment]
Closing this as fixed
