### ISSUE TITLE
Delete with REST

### ISSUE THREAD

**Issue by Prybe** [Azure/azure-documentdb-dotnet#285]
Hi,
did you try to make a "delete" call with REST?
I´m not able to make it :-/

thx in advance 
Martin

**Comment by kirankumarkolli** [comment]
@Prybe Did you check DoucmentDb [REST samples](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/rest-from-.net)?

**Comment by kirankumarkolli** [comment]
@Prybe closing this issue. If you are still blocked feel free to re-open it.
