### ISSUE TITLE
DocumentClient singleton clarification?

### ISSUE THREAD

**Issue by dmcweeney** [Azure/azure-documentdb-dotnet#289]
Hi,

I just want some clarification on the following performance tip on DocumentDb.

"Use a singleton DocumentDB client for the lifetime of your application. 
Note that each DocumentClient instance is thread-safe and performs efficient connection management 
and address caching when operating in Direct Mode. To allow efficient connection management and better performance by DocumentClient, it is recommended to use a single instance of DocumentClient per AppDomain for the lifetime of the application."

In our case we have an ASP.Net Core WebApp which uses a number of DocumentDb databases, 
each in a different CosmosDb account and thus require different connection settings etc.

Using the above advice I presume it is safe to have a DocumentClient instance per database and 
each of these instances registered as a singleton in the ASP.Net Core DI framework?
Eg.
	services.AddSingleton<IMyAAADbDocumentClient>( myAAADbDocumentClientInstance );
	services.AddSingleton<IMyBBBDbDocumentClient>( myBBBDbDocumentClientInstance );
	services.AddSingleton<IMyCCCDbDocumentClient>( myCCCDbDocumentClientInstance );

Please confirm.

Thanks

Donal

**Comment by grahamehorner** [comment]
I have a Implemented a CosmosDB.DocumentClientCollection for exactly this reason the collection is keyed on the connection string this is a dependancy injected signleton that returns the DocumentClient if it already exists or creates on adding it to the collection.

**Comment by rnagpal** [comment]
@dmcweeney: Yes, your understanding is correct. You can have multiple DocumentClient instances in this case, one for each Cosmos DB account. 

Is there a reason for you to have different Cosmos DB accounts? Can you instead use different collections within a database or in different databases in the same Cosmos DB account. If you want them to be geo-distributed you could do that by adding regions that will replicate your data across other regions by allowing you to have a single endpoint for your application.

@grahamehorner Same comment for you. Is there any reason why you can't have your collections in the same Cosmos DB account?

**Comment by grahamehorner** [comment]
@rnagpal I have a requirement to keep data within a given region, but allow access to users from the region the data is for from anywhere in the world.

**Comment by dmcweeney** [comment]
@grahamehorner @rnagpal Thanks for the clarifications, I can sleep easier now!

@rnagpal Reason for the multiple accounts is that each db has different replication and consistency requirements and the replication can only be configured at the account level.

Thanks

Donal

**Comment by grahamehorner** [comment]
oh and one more issue is that my use case lends very well to a graph; however we also need to perform spatial queries, which at present (unless I'm mistaken) gremlin has no support for unlike Cosmos - Document API so the plan was to hold graph references in a document store with the geographic data perform spatial queries the load graph data using the reference links

**Comment by kirankumarkolli** [comment]
@ashwini-ms could you please address gremlin part of the question.

**Comment by ashwini-ms** [comment]
@grahamehorner , Yes.. Cosmos DB graph API does not support geo spatial data as of now but it is definitely on our road map.

**Comment by grahamehorner** [comment]
@ashwini-ms that great news thanks
