### ISSUE TITLE
Error when deploying ResourceTokenapp to Azure, I get an error.   

### ISSUE THREAD

**Issue by Jeremywhiteley** [Azure/azure-documentdb-dotnet#291]
When ever I deploy the Resourcetoken broker app to Azure I get this error 

https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/xamarin/UserItems/ResourceTokenBroker

Command: "D:\home\site\deployments\tools\deploy.cmd"
Handling .NET Web Application deployment.
MSBuild auto-detection: using msbuild version '14.0' from 'D:\Program Files (x86)\MSBuild\14.0\bin\amd64'.
All packages listed in packages.config are already installed.
  ResourceTokenBroker -> D:\home\site\repository\ResourceTokenBroker\bin\ResourceTokenBroker.dll
D:\home\site\repository\ResourceTokenBroker\ResourceTokenBroker.csproj : error MSB4057: The target "pipelinePreDeployCopyAllFilesToOneFolder" does not exist in the project.
Failed exitCode=1, command="D:\Program Files (x86)\MSBuild\14.0\Bin\MSBuild.exe" "D:\home\site\repository\ResourceTokenBroker\ResourceTokenBroker.csproj" /nologo /verbosity:m /t:Build /t:pipelinePreDeployCopyAllFilesToOneFolder /p:_PackageTempDir="D:\local\Temp\8d4baa4498efc25";AutoParameterizationWebConfigConnectionStrings=false;Configuration=Release;UseSharedCompilation=false /p:SolutionDir="D:\home\site\repository\.\\"
An error has occurred during web site deployment.
\r\nD:\Program Files (x86)\SiteExtensions\Kudu\63.60608.2880\bin\Scripts\starter.cmd "D:\home\site\deployments\tools\deploy.cmd"

**Comment by kirankumarkolli** [comment]
@Jeremywhiteley are you still blocked? 

I was able to publish by following https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-dotnet#publish-to-azure

**Comment by kirankumarkolli** [comment]
@Jeremywhiteley closing the issue. Feel free to re-open if you have a repro.
