### ISSUE TITLE
Requests originating from scripts cannot reference partition keys other than the one for which client request was submitted

### ISSUE THREAD

**Issue by bdcoder2** [Azure/azure-documentdb-dotnet#294]
Sorry - issue was my fault / misunderstanding -- please disregard or delete.

**Comment by nysthee** [comment]
Can you elaborate what was causing the issue?

**Comment by bdcoder2** [comment]
No need -- it was a misunderstanding on my part with regard to partition keys.  This "issue" should be deleted.  Thanks.

**Comment by bdcoder2** [comment]
Sorry -- that was way back when I was first experimenting with CosmosDB -- tried to find the project I was working on at the time, but could not (may have deleted it) -- but I did find my my post on StackOverflow:

[https://stackoverflow.com/questions/44830792/azure-documentdb-requests-originating-from-scripts-cannot-reference-partition](https://stackoverflow.com/questions/44830792/azure-documentdb-requests-originating-from-scripts-cannot-reference-partition)
