### ISSUE TITLE
graph - difference in implementation of Vertex properties vs TinkerPop - may confuse people

### ISSUE THREAD

**Issue by bartdotnet** [Azure/azure-documentdb-dotnet#297]
Hi,

http://tinkerpop.apache.org/docs/current/reference/#vertex-properties
. states that g.V().Property() should remove properties and create one
. states implements g.V().Properties().Property() ads a property

cosmosDB implements
. tinkerpop g.V().Property() as tinkerpop g.V().Properties().Property()
. does not implement tinkerpop g.V().Property() 

Regards,
Bart,

**Comment by ChrisMiskowiec** [comment]
@bartdotnet That section refers to vertex properties, which are properties that can have meta-properties.

g.V('x').properties() returns all properties for vertex "x".

g.V('x').property('name', 'value') adds a property "name" to vertex "x".

g.V('x').properties('name').properties() returns all properties for for property "name" on vertex "x" - in other words, the property itself can have properties.

As far as I can tell, none of these steps should remove any properties.

**Comment by dennyglee** [comment]
Thanks @ChrisMiskowiec !  Will close this issue; if there are any issues, please re-open and comment.  Thanks!

**Comment by bartdotnet** [comment]
@ChrisMiskowiec @dennyglee 

Hereby my - late but sincere - thanks for the feedback. I have improved my Gremlin skills a bit already in the meanwhile :-)

Kind Regards,
Bart,
