### ISSUE TITLE
x-ms-date header is missing and fails to create when DocumentDB Firewall is enabled

### ISSUE THREAD

**Issue by hteramoto** [Azure/azure-documentdb-dotnet#305]
This issue appears to be specific to how DocumentClient is instantiated.  I'm seeing this error when  DocumentClient is created with a resource token and firewall is enabled.  When DocumentClient is created using access key, this issue does not happen.

**Environment:**
Azure Cosmos DB (API:SQL, East US)
Microsoft.Azure.Documents.Client v1.15.0.0

**Reproduction Steps:**
1. Deploy Azure Cosmos DB and enable Firewall from the portal with your IP address whitelisted.
2. In the code, create DocumentClient using a resource token and attempt to create a new document to the existing collection.

**Expected:**
Document is created.

**Actual:**
Error is returned by Azure Cosmos DB

`
{
"code":"Unauthorized",
"message":
     "Message: {
         \"Errors\":
              [\"Authorization token mandates Date header. Please pass in RFC 1123 style date format.\"]
     }
     ActivityId: <removed>, 
     Request URI: <removed>"
}
`

Inspecting the network trace, x-ms-date header is missing in API calls.

Example code that reproduces this issue.

[Program.cs.txt](https://github.com/Azure/azure-documentdb-dotnet/files/1153189/Program.cs.txt)

**Comment by kirankumarkolli** [comment]
@hteramoto this is bug on our server side. We are working on a fix for this. 

Meanwhile you can unblock by using 'Direct' mode which doesn't have this issue.

**Comment by hteramoto** [comment]
Thanks @kirankumarkolli 
I have verified the workaround and make a connection to firewalled Cosmos DB.
