### ISSUE TITLE
IReliableReadWriteDocumentClient .NET Core 2.0

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-documentdb-dotnet#308]
Please create/update the DocumentDB nuget package to support the TransientFaultHandling or provide guidance on how similar functionality can be achieved when developing ASP.NET Core 1.1/2.0 Web API projects.

**Comment by ealsur** [comment]
@grahamehorner As far as I know, the SDK already has [transient fault handling included](https://stackoverflow.com/a/43276925/5641598).

**Comment by grahamehorner** [comment]
@ealsur thanks for the link, it would be great if the apis had been aligned so code didn't have to change if built against the .net core as opposed to full .net, think now I know about this feature I will look at abstract/wrap this to provide a consistent interface for out devs thanks again
