### ISSUE TITLE
Error: Request rate is large, with single DocumentClient instance

### ISSUE THREAD

**Issue by jrmurdoch** [Azure/azure-documentdb-dotnet#309]
I'm hitting the "Request rate is large" response this I expect as i've been testing during development. I have a single instance of DocumentClient so I don't expect this error to throw an exception. 

This code runs fine!
```
foreach(var product in products) {
                await documentClient.UpsertDocumentAsync(...);
            }
```

This code errors 
```
            var tasks = products.Select(p => documentClient.UpsertDocumentAsync(....));
            await Task.WhenAll(tasks);
```

I thought DocumentClient was thread safe and a single instance would manage the requests at the required rate. Any ideas?

**Comment by pendragon-andyh** [comment]
I have only recently started with Cosmos (so may be wrong) ...
* The "await" in your first example will pause until that single Upsert is finished.
* Your second example will unleash a large number of parallel requests.

I think the "Request rate is large" response is telling you that you need to throttle the rate at which you are hitting the database (compared to the number of RUs that are provisioned for that collection). Maybe [Parallel.ForEach](https://stackoverflow.com/questions/9290498/how-can-i-limit-parallel-foreach) will help.

If you need higher throughput then consider:
* Temporarily increase the number of RU/second for your collection.
* Using RequestOptions to temporarily switch to "lazy" indexing and eventual-consistency (reduces the time/cost of the write operations).
* Use stored procedures to upload a batch of records at-a-time (reduces latency).
* Use a partitioned-collection (spreads load across multiple partitions).

Hope that helps.

**Comment by pendragon-andyh** [comment]
Also, the ConnectionPolicy contains a MaxConnectionLimit property. The documentation indicates that this is only used when you are using Gateway mode.

**Comment by kirankumarkolli** [comment]
@jrmurdoch DoucmentClient is thread-safe. Server is throttling you are sending response "Request rate is large". @pendragon-andyh shared some good recommendations, please take a look. 

Also please note that partitioned collection gets more throughput.
