### ISSUE TITLE
Could not load file or assembly 'DocumentDB.Spatial.Sql.dll' or one of its dependencies

### ISSUE THREAD

**Issue by vikram77** [Azure/azure-documentdb-dotnet#311]
We have 3 projects:

1. Class Library (Target Framework 4.5)
2. Web App (MVC) Project (Target Framework 4.5)
3. Web API Project(Target Framework 4.5.2)

Recently started working with Azure Cosmos DB (Document DB driver). All the implementation is done in Class Library used in API & Web App projects both.

Apparently, Web App works fine but REST Api project throws an error:

Could not load file or assembly 'file:///D:\API\bin\DocumentDB.Spatial.Sql.dll' or one of its dependencies. The module was expected to contain an assembly manifest.

Have tried upgrading the target framework for all projects to 4.5.2 but still same issue.

following is the stack trace & assembly load trace
![image](https://user-images.githubusercontent.com/1557422/28955501-1df43d92-78df-11e7-9588-16d18e538859.png)

**Comment by kirankumarkolli** [comment]
@vikram77 are you still blocked? 
If possible could you please share solution, we will take a look.

**Comment by vikram77** [comment]
@kirankumarkolli  thanks for the revert but after struggling with it for over 3 days, eventually i just re-created my whole API project setting target to 4.5 instead of 4.5.2 and apparently that seemed to work fine.

**Comment by kirankumarkolli** [comment]
@vikram77 if possible could you please share the 4.5.2 solution. We will take a look.

**Comment by kirankumarkolli** [comment]
@vikram77 closing the issue for now. In-case you have a repro solution please re-open and we will take a look.
