### ISSUE TITLE
LINQ to SQL translation incorrectly translating SelectMany followed by OrderBy

### ISSUE THREAD

**Issue by mcbridedm** [Azure/azure-documentdb-dotnet#314]
When performing a SelectMany, followed by OrderBy, selector key on orderby does not properly apply to the correct node.

Example object I am querying against 
`{
  "id": [REMOVED],
  "StartTimestamp": 1499278500,
  "ClosingTimestamp": 1499276086,
  "Hospital": {
	"Id": "HospitalId"
  },
  "Attendees": [
	{
	  "Email": [REMOVED],
	  "Id": [REMOVED]
	}
  ],
  "_rid": [REMOVED],
  "_self": [REMOVED],
  "_etag": [REMOVED],
  "_attachments": [REMOVED],
  "_ts": [REMOVED]
}`

### Example Broken Query
Exception thrown stating: "Order-by over correlated collections is not supported"
```
// input to method is userId, and a predicate (indicating timestamp range, and hospitalId)
var orderedQueryable = client.CreateDocumentQuery<ConsolidatedCase>(collection.DocumentsLink, feedOptions);

var documentQuery = orderedQueryable
    .Where(predicate)
    .SelectMany(cc => cc.Attendees.Where(a => a.Id == UserId)
    .Select(x => cc))
    .OrderByDescending(x => x.StartTimestamp)
    .AsDocumentQuery();
```
Generated query is: `SELECT VALUE root FROM root JOIN a IN root["Attendees"] WHERE (((true AND (root["Hospital"]["Id"] = "HospitalId")) AND ((true AND (root["StartTimestamp"] >= 1500938556)) AND (root["StartTimestamp"] <= 1502261999))) AND (a["Id"] = "UserId")) ORDER BY a["StartTimestamp"] DESC`

The problem being that a["StartTimestamp"] is not a valid field.

I can resolve this by moving the orderby to before the SelectMany, and then it correctly orders by root["StartTimestamp"]

**Comment by kirankumarkolli** [comment]
@mcbridedm cosmos db doesn't allow order by on correlated collections (i.e. those created using JOINs).

**Comment by mcbridedm** [comment]
@kirankumarkolli Understood.  Even if ddb doesn't yet support orderby on a join, Shouldn't it at least generate valid sql?  Or no?  I'm trying to point out the translation being nonsensical - not necessarily ddb not yet having support for something.
