### ISSUE TITLE
Invalid Header when using compositeToken for RequestContinuation

### ISSUE THREAD

**Issue by danielzoeller** [Azure/azure-documentdb-dotnet#323]
Microsoft.Azure.DocumentDB SDK Version 1.14.1 and above.

When using an ORDER BY in a DocumentDB query, the ResponseContinuation that comes back from IDocumentQuery.ExecuteNextAsync has line breaks in the response which in turn causes an invalid http header when requesting the next page of results. 

Example ResponseContinuation:
```
[\r\n  {\r\n    "compositeToken": {\r\n      "token": "+RID:GsQyAP46BQBp8wMAAAAAAA==#RT:1#TRC:10#RTD:8g7DfTFCuwba#FPC:...[REMOVED FOR BREVITY]...LAsAwAAQA",\r\n      "range": {\r\n        "min": "",\r\n        "max": "FF"\r\n      }\r\n    },\r\n    "orderByItems": [\r\n      {\r\n        "item": 1.31470992E+17\r\n      }\r\n    ],\r\n    "rid": "GsQyAP46BQBp8wMAAAAAAA==",\
r\n    "skipCount": 0,\r\n    "filter": null\r\n  }\r\n]
```

When using that token for the next page of results it causes an invalid header to be sent.  The header is simply "]" with no value.

The workaround is to remove "/r/n" from the response before requesting the next page of results.

This only happens in the SDK.

**Comment by kirankumarkolli** [comment]
@danielzoeller we are not able to repro this. ContinutionToken should not have newlines. 
Any possibility of your code formatting the token ? 

If possible could you please share the repro sample code.

**Comment by danielzoeller** [comment]
I'll put together a sample repro app.  Make sure you are specifically looking at compositeToken though and not just a "regular" token.  The typical token (non-composite) doesn't have newlines, but the compositeToken does.  I'll put together a sample...

**Comment by danielzoeller** [comment]
Update:

It doesn't happen when running from a console app or from a unit test.  But the same code when called from a Web API causes the problem to happen.

I know for sure it's not my code changing the response because I put a TraceInformation immediately after I get the ResponseContinuation from ExecuteNextAsync and it has the newlines in it.

My guess is that I have nuget package installed on my web app that is modifying the JSON.  Too many packages installed to figure it out right now though.  The workaround I posted is perfectly acceptable so I am going to close this one.

For posterity's sake (and to prove I'm not an idiot) here is my suspect code:
```
            if (!string.IsNullOrEmpty(continuationToken))
            {
                queryOptions.RequestContinuation = continuationToken;
            }
            var dquery =
                    _client.CreateDocumentQuery<T>(link, query, queryOptions)
                    .AsDocumentQuery();

            string queryContinuationToken = null;
            var page                      = await dquery.ExecuteNextAsync<T>();
            var queryResult               = page.ToList();
            if (dquery.HasMoreResults)
                queryContinuationToken = page.ResponseContinuation;

            Trace.TraceInformation($"queryContinuationToken = {queryContinuationToken}");
```

and the output I get from that section of code is attached.
[Azure Issue 323.txt](https://github.com/Azure/azure-documentdb-dotnet/files/1232552/Azure.Issue.323.txt)
