### ISSUE TITLE
Projects referencing this sdk break if moved to a different directory

### ISSUE THREAD

**Issue by michaeldaw** [Azure/azure-documentdb-dotnet#324]
This is probably the same problem as #247, but that issue was closed.

If you import the DocumentDb nuget package, a build target is created in your csproj file that references the full path to `Microsoft.Azure.DocumentDB.targets`. The build target is called `EnsureNuGetPackageBuildImports`.
From this point, if the project is built from a different directory (say, on another machine), the full path indicated in the generated build target will no longer be correct and the build experiences an error.

Here is an example of the generated build target:
```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('c:\projects\myproject\packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets')" Text="$([System.String]::Format('$(ErrorText)', 'c:\projects\myproject\packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets'))" />
  </Target>
```
In my case, I commit the repository, and then pull it on another machine with a different directory structure. The only way to get the project to compile is to change that path to reflect the new directory structure. With .csproj files being committed to the repository, this becomes very tedious very fast.

The `EnsureNugetPackageBuildImports` target should use relative paths to its necessary files.

**Comment by michaeldaw** [comment]
The full path found in the build target can be manually changed to a path relative to the csproj file, making it possible to move the project to different directories. The build target in the example above becomes:
```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets'))" />
  </Target>
```

**Comment by kirankumarkolli** [comment]
@michaeldaw is this happening only for DocumentDB nuget package or even for other packages?

Suspecting this might be todo with the nuget version you are using. Please try to upgrade to [latest nuget version](https://www.nuget.org/downloads)

**Comment by michaeldaw** [comment]
As it turns out, I upgraded from VS 15.3 Preview to 15.3 Release just this morning (after posting this issue). I made a project and reference the documentdb nuget package, found that the file references are being written correctly:
```
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('..\packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets')" Text="$([System.String]::Format('$(ErrorText)', '..\packages\Microsoft.Azure.DocumentDB.1.17.0\build\Microsoft.Azure.DocumentDB.targets'))" />
  </Target>
```
Given your suggestion that it might have been a problem with Nuget itself, perhaps something was changed between the preview and release versions of VS2017. It certainly seems to work properly now.
Thank you for getting back to me so quickly.

**Comment by kirankumarkolli** [comment]
@michaeldaw glad that you are unblocked. Closing the ticket now.
