### ISSUE TITLE
When the lease expires, will the next AcquireAsync call succeeds?

### ISSUE THREAD

**Issue by JeffreyZZ** [Azure/azure-documentdb-dotnet#326]
For Azure Storage Blob, when the lease expires, the next call to acquire lease on the blob will succeed. For DocumentServiceLeaseManager, I didn't see the similar logic in its AcquireAsync method. Does AcquireAsync succeed when the lease expires?

**Comment by ealsur** [comment]
If the lease expires it means that it was not currently being used by a host (or not processed in the configured time). The PartitionManager is the one that will handle the case when another Host appears that can pickup the lease and call the AcquireAsync method on that lease, it's described in the README.

> Acquire leases: starting with available leases, then expired leases to fill up its target. If the number of own leases acquired is below the target, it steal leases from other hosts to load balance work.

Does that help?
