### ISSUE TITLE
Resource Not Found for cosmos DB Write

### ISSUE THREAD

**Issue by dewanymca** [Azure/azure-documentdb-dotnet#335]
Hi Team

We have been using cosmos db to store metadata for our application, We are using logic app as client to do operation with document db. Recently we switched interfacing to store procedure and started receiving intermittently below error. I was able to fix this one time when i redeployed cosmos db. can you please help this is becoming a blocker for us we are going live in coming weeks so it's super critical for us to fix this

                "code": "NotFound",
                "message": "Message: {\"Errors\":[\"Resource Not Found\"]}\r\nActivityId: fe99b343-b22c-4a23-a2be-990ab8c9770d, Request URI: /apps/ec83e5d7-3d94-460b-bcda-0bcf56299f77/services/54c7837f-2dfb-4141-a1d3-c2faa03d0878/partitions/e0cdc110-1997-4831-ae2d-37be4b8272ff/replicas/131473056075934016p"

Let me know if you need additional information

**Comment by rnagpal** [comment]
I'm following up offline with him

**Comment by Blackbaud-PeteLukich** [comment]
@dewanymca @rnagpal - what was the solution here?  my team is seeing the same issue, doing writes via SP's...

**Comment by rnagpal** [comment]
This was a code issue. They were deleting the stored procedure after every call while other thread was trying to execute this. So this "resource not found" was actually due to the stored procedure not found(and not the document). We were able to fix this on their code.
