### ISSUE TITLE
cosmosdb - graph - ability to create Graph vertex via DocumentDB API

### ISSUE THREAD

**Issue by bartdotnet** [Azure/azure-documentdb-dotnet#338]
Hi,

1. Issue
Vertexes described in Graphson that are saved to CosmosDB via the DocumentDB API are not entirely visible as Vertexes in the Graph API. The Graph API only shows ID, label and type properties.

2. reproduction 
```
data : https://github.com/bartdotnet/CosmosDbTests/blob/master/CosmosDbNativeGraphsonGraph/data/UsptoAssignees.jsongraph

example code: https://github.com/bartdotnet/CosmosDbTests/tree/master/CosmosDbNativeGraphsonGraph

```
query via the two vertexes via:
- the azure portal + cosmosDB Graph Explorer
- Microsoft Graph API
- Gremlin.Net
- Gremlin Console

3. reasoning:

GraphSon is used to store graph information in CosmosDB.
GraphSon is used are a response format.
GraphSon is used as internal storage format.
Saving a Vertex in GraphSon format in a CosmosDB Graph document via the DocumentDB API is said to expose the document via the GRAPH API of CosmosDB.
see also references to related info as comments in https://github.com/bartdotnet/CosmosDbTests/blob/master/CosmosDbNativeGraphsonGraph/CosmosDBDocumentHelper.cs

4. Please:
- indicate if above reasoning is correct and if not what is wrong
- confirm or deny loading graphs via Document is and will be possible, currently and in the future
- if above is to be possible please indicate if I made a mistake in the Json used as payload
- if above is to be possible, my scenario is correct and you agree this behaviour of CosmosDB Graph /and or DocumentDB API is not correct, please file a bug.

Thanks in advance,
Bart,

**Comment by bartdotnet** [comment]
Adding IDs in vertex and vertex custom properties does not seem to help

**Comment by bartdotnet** [comment]
the following result that is fetched out vie the DocumentDB API seems to be valid GraphSon

```
{"id":"ba02f0a0-f7f1-49a7-91cb-845ba024fa47","_rid":"kQtPAJSlVQA5AAAAAAAAAA==","_self":"dbs/kQtPAA==/colls/kQtPAJSlVQA=/docs/kQtPAJSlVQA5AAAAAAAAAA==/","_ts":1504774451,"_etag":"\"0000d401-0000-0000-0000-59b109330000\"","label":"Organization","type":"vertex","properties":{"assignee_organization":[{"value":"Microsoft Corporation","id":"b62e2c04-cd62-4ea3-95e3-fae47fd26d9b"}],"assignee_id":[{"value":"237c2b0099548ddbfa5a37f07e0687ab","id":"f24e1ab0-7580-4290-bbb2-15a0a0e785c9"}],"assignee_type":[{"value":"2","id":"06b4eedf-8715-45ee-a3ad-ee3d2906e93b"}],"@id":[{"value":"http://www.patentsview.org/api/assignee/237c2b0099548ddbfa5a37f07e0687ab","id":"9faf7aea-323f-4cd1-b42b-2b5134432549"}],"@type":[{"value":"Organization","id":"604f9eed-23d6-40cc-b9c0-9ea94ab57115"}]}}

{"id":"40acf9c3-2931-4627-b638-21e86feac288","_rid":"kQtPAJSlVQA6AAAAAAAAAA==","_self":"dbs/kQtPAA==/colls/kQtPAJSlVQA=/docs/kQtPAJSlVQA6AAAAAAAAAA==/","_ts":1504774451,"_etag":"\"0000d501-0000-0000-0000-59b109330000\"","label":"Organization","type":"vertex","properties":{"assignee_organization":[{"value":"Microsoft Corporation-One Microsoft Way","id":"87755d74-ab08-455f-b344-6453fe8effac"}],"assignee_id":[{"value":"86231c1210fc43324fb572053c38383e","id":"9fcd7c68-e370-4f39-b594-676da11a6fb8"}],"assignee_type":[{"value":"2","id":"a48adfb8-b067-4c10-93ac-521ee9bd7839"}],"@id":[{"value":"http://www.patentsview.org/api/assignee/86231c1210fc43324fb572053c38383e","id":"6ac197b1-4930-4d3c-bef5-66ac1cdcb952"}],"@type":[{"value":"Organization","id":"d8e450d2-1309-446f-be11-8dc3f9f52cb9"}]}}
```

formatting issues similar to https://stackoverflow.com/questions/32903802/following-graphson-format-not-working seem not to be relevant here as all seems correctly formatted

**Comment by bartdotnet** [comment]
tried another format (omitting the properties tag) format as well with little success https://stackoverflow.com/questions/44009349/storing-a-vertex-as-json-in-cosmosdb

**Comment by bartdotnet** [comment]
what is visible in the graph API:
```
{"id":"ba02f0a0-f7f1-49a7-91cb-845ba024fa47","label":"Organization","type":"vertex"}
{"id":"40acf9c3-2931-4627-b638-21e86feac288","label":"Organization","type":"vertex"}
```

**Comment by bartdotnet** [comment]
Hi @charbull,

Did you have time to reproduce the issue?

Thanks in advance,
Bart,

**Comment by charbull** [comment]
Hi @bartdotnet , no sorry not yet, I have been on vacation/travel I will have stable hours next week to try it.

Best,
Charbel

**Comment by jayantacs** [comment]
Hi @bartdotnet 

1.	Our output format is GraphSon when you query the system via gremlin API (like other tinkerpo-enabled graphs)
2.	However, that doesn’t mean that we store the graph in the same GraphSON format. In fact, the storage model to adhere to GraphSON may have significant scale limitation. 
a.	E.g., GraphSon format requires to store the edges of a vertex in the same document. This will cause significant performance issue for very high degree nodes (i.e., celebrity accounts on Twitter)
b.	Apart from storage, concurrency control also become a major issue. 
3.	Any property that starts with _ (e.g., _rid, _self) etc. are system properties, they can’t be accessed  via gremlin API. 
4.	Also, soon (ETA Sept end) we are going to release a Bulk Insert API, that will allow you to directly ingest data to DocumentDB bypassing the gremlin. This API is being designed to achieve high ingestion throughput, and will have direct knowledge of how data is stored in CosmosDB Graph. 

Please let us know, if there is any specific reason that you want to update graph via DocumentDB’s API, we will recommend the best practices.

**Comment by bartdotnet** [comment]
Hi @jayantacs,

Thanks again for the feedback. My intention was to examine Cosmos Graph bulkload via Document DB.

In understand GraphSON is only a representational format, not an internal one - for reason of performance -.

I am happy to see a Bulk load API is on the close horizon and will await for its arrival.

Regards,
Bart Debersaques,

**Comment by lpunderscore** [comment]
@jayantacs I know this is closed, but could you provide a link or a status for the bulk insert api? I am not able to find it.

**Comment by higalex** [comment]
@jayantacs Are there any updates on the bulk load API? I'm sure there are a lot of people waiting for it as there doesn't seem to be an alternative way to bulk load data into Cosmos DB Graph.
