### ISSUE TITLE
MaxDegreeOfParallelism throws exceptions in Docker (Net core SDK)

### ISSUE THREAD

**Issue by karimmansour92** [Azure/azure-documentdb-dotnet#341]
Couldn't find a specific repo for the net core sdk, if there's a better place to ask this question let me know.

We're having an issue where a document query with MaxDegreeOfParallelism set to anything but 0 results in a large number of exceptions being thrown from the library when running in docker. The same query when running without docker (IIS) works fine with no exceptions.  The same query, when targeting just 1 partition, also has no problems in both docker and without docker.

Interestingly, the query ultimately returns, but it takes about 10 seconds for a call that should be in the order of a few hundred ms.

The query we're running is:
`query = client.CreateDocumentQuery(UriFactory.CreateDocumentCollectionUri(DatabaseId, CollectionId), $"SELECT * FROM c WHERE c.isActive = true AND c.id IN (\"1\",\"2\",\"3\",\"4\") AND c.partitionKey IN (\"o-1-1\",\"o-1-2\",\"o-1-3\",\"o-1-4\")", new FeedOptions() { EnableCrossPartitionQuery = true, MaxDegreeOfParallelism = 10, MaxItemCount = -1 }).AsDocumentQuery();`

and then executing it and awaiting:
`var result = await query.ExecuteNextAsync();`

In the output console I'm seeing lots of:
> Exception thrown: 'Microsoft.Azure.Documents.DocumentClientException' in System.Private.CoreLib.ni.dll

The exception itself is:
> Microsoft.Azure.Documents.DocumentClientException: 'Cross partition query with TOP/ORDER BY or aggregate functions is not supported.'

Which is odd, since there is no aggregation in the sql query.

What could be the cause of this issue? Is the slowdown likely due to the large number of exceptions being thrown?

Some more info:
- We're running the app in docker with the standard microsoft/aspnetcore image.
- The client is running with the default connectionPolicy.

**Comment by bchong95** [comment]
Hi,

"Cross partition query with TOP/ORDER BY or aggregate functions is not supported." is a first chance exception that is expected when you try to run a cross partition query. The full exception should look something like this:

```

**Comment by rnagpal** [comment]
@karimmansour92 As Brandon mentioned, these are first chance exceptions and shouldn't be thrown to your application. This does increases the latency slightly but not in the order of secs that you are seeing. Please make sure you are following all performance tips here https://docs.microsoft.com/en-us/azure/cosmos-db/performance-tips If it still doesn't help please send email to askcosmosdb @ Microsoft.com with your sample application so that we can investigate further. Is your Cosmos DB account in the same region as your application?

**Comment by karimmansour92** [comment]
Thank you both for your replies.

@bchong95 Correct. The full exception I'm seeing is:
`{{
  "code": "BadRequest",
  "message": "Cross partition query with TOP/ORDER BY or aggregate functions is not supported.\r\nActivityId: 43fd4fb5-8792-45e5-9aa0-8a66a1ee841b",
  "additionalErrorInfo": "{\"partitionedQueryExecutionInfoVersion\":2,\"queryInfo\":{\"top\":null,\"orderBy\":[],\"orderByExpressions\":[],\"aggregates\":[],\"rewrittenQuery\":\"\"},\"queryRanges\":[{\"min\":\"05C1B58FF14DA008702E322E3400\",\"max\":\"05C1B58FF14DA008702E322E3400\",\"isMinInclusive\":true,\"isMaxInclusive\":true},{\"min\":\"05C1E5739D27FE08702E322E3500\",\"max\":\"05C1E5739D27FE08702E322E3500\",\"isMinInclusive\":true,\"isMaxInclusive\":true},{\"min\":\"05C1E5EFC971BA08702E322E3300\",\"max\":\"05C1E5EFC971BA08702E322E3300\",\"isMinInclusive\":true,\"isMaxInclusive\":true}]}"
}}`

The exception doesn't seem to be bubbling up to the application (doesn't get caught in a try-catch). I can, however, see those exceptions in the output while debugging (more than a dozen of them every time I run the query). After about 10 seconds, the results then come back, and are correct. 

Is there perhaps something about MaxDegreeOfParallelism that is specific to Windows, and so has issues when running in Docker (linux)?

@rnagpal I see. I am unfortunately seeing that the call, when debugging locally, takes in the order of 10 seconds, compared to less than 500ms when running with MaxDegreeOfParallelism set to 0. I've followed all the major performance tips but for the Direct-tcp connection which is giving us issues in docker, presumably for the same reasons in #194 (windows only support?).

I've sent you a sample application on the email address given.

We're testing the application locally for now, and the db is on the azure region closest to us.

**Comment by rnagpal** [comment]
@karimmansour92 You are probably running into this issue: 

https://blogs.msdn.microsoft.com/devops/2015/02/23/performance-improvement-when-debugging-net-code-with-visual-studio-2015/ 

Try checking "Enable Just My Code' as shown in https://msdn.microsoft.com/en-us/library/dn457346.aspx and let me know if that helps.

**Comment by karimmansour92** [comment]
Thanks Rajesh, that was it.
