### ISSUE TITLE
QueryResult does not expose null values

### ISSUE THREAD

**Issue by fabiomaulo** [Azure/azure-documentdb-dotnet#347]
![inspectingqueryresult](https://user-images.githubusercontent.com/125039/30674517-40e4abc4-9e51-11e7-83ae-b9d6fb4d18c9.PNG)

But the document is
![infoindb](https://user-images.githubusercontent.com/125039/30674537-5709083c-9e51-11e7-9f58-8939582e6c81.PNG)
As you know null !=='undefined' and, this time, this issue is blocking us

**Comment by ealsur** [comment]
Are you using custom Json serialization? What type of attributes are `shipping_id` and `pickup_id`? Are they `string` or `int?`?
[NullValueHandling](https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_NullValueHandling.htm) can serialize force the deserialization of null values I believe.

Queries to the service return all attributes (even those that are null) so it sounds like its a matter of when the data is being read.

**Comment by fabiomaulo** [comment]
This was the workaround
`o => (string)(o.shipping_id) != null,`
The original (not working) implementation was
`o => o.shipping_id != null,`
In practice we have to use an explicit cast to _something_ .
