### ISSUE TITLE
Paging

### ISSUE THREAD

**Issue by grahamehorner** [Azure/azure-documentdb-dotnet#350]
Please consider allowing server side paging; using linq skip operation and/or all the collecting continuation tokens of a query to allow jumping to a given page.

**Comment by kirankumarkolli** [comment]
@grahamehorner thanks for the feedback. Could you please update below link with your feedback. https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6350987--documentdb-allow-paging-skip-take
