### ISSUE TITLE
Storage Tables client and CosmosDB Table API client Nuget packages

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-documentdb-dotnet#352]
Currently, Tables Storage is positioned in the following way

>Standard Azure Table Storage is now part of Cosmos DB. To see that documentation, see the Azure Table Storage Overview. Also available is Premium Tables for Azure Table storage, offering throughput-optimized tables, global distribution, and automatic secondary indexes. To learn more and try out the new premium experience, please check out Azure Cosmos DB: Table API.

For Standard Azure Table Storage, there's a client: [WindowsAzure.Storage](https://www.nuget.org/packages/WindowsAzure.Storage).
For Premium Tables for Azure Table Storage (not as bad as .NET Core release names, but still mouthful) there's another client: [WindowsAzure.Storage-PremiumTable](https://www.nuget.org/packages/WindowsAzure.Storage-PremiumTable).

[CosmosDB Table API intro page](https://docs.microsoft.com/en-us/azure/cosmos-db/table-introduction) says the following:

> These applications can migrate to Azure Cosmos DB by using the Table API with no code changes and take advantage of premium capabilities.

Based on that, I'm assuming that the new package is to be used with the future Table development.

If WindowsAzure.Storage package will be deprecated, rather than having WindowsAzure.Storage-PremiumTable it would make sense to package and release the new client that is more aligned with what it is - **Microsoft.Azure.Tables**.

DocumentDB: [Microsoft.Azure.DocumentDB](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/) package
Graph API: [Microsoft.Azure.Graphs](https://www.nuget.org/packages/Microsoft.Azure.Graphs) package

**Comment by tomkerkhove** [comment]
Agreeing with @SeanFeldman on this

**Comment by kirankumarkolli** [comment]
@SeanFeldman totally agreed and we are working toward it. We will update on the names shortly.

**Comment by SeanFeldman** [comment]
Looks like the name was changed to [`Microsoft.Azure.CosmosDB.Table`](https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.Table).
Wish the team would keep things up to date 😉
