### ISSUE TITLE
Microsoft.Azure.Graphs SDK 0.3.0 built for AMD64

### ISSUE THREAD

**Issue by dzrhythm** [Azure/azure-documentdb-dotnet#361]
The latest 0.3.0 release for the Microsoft.Azure.Graphs SDK appears to target the AMD64 processor. The .net standard version will not run in Azure App Services and the net461 version won't even run locally for me, both due to BadImageFormatException.

Though the projects target "Any CPU", Visual Studio gives the warning:

Warning	MSB3270	There was a mismatch between the processor architecture of the project being built "MSIL" and the processor architecture of the reference "C:\Users\XXX\.nuget\packages\microsoft.azure.graphs\0.3.0-preview\lib\netstandard1.6\Microsoft.Azure.Graphs.dll", "AMD64". This mismatch may cause runtime failures. Please consider changing the targeted processor architecture of your project through the Configuration Manager so as to align the processor architectures between your project and references, or take a dependency on references with a processor architecture that matches the targeted processor architecture of your project.

**Comment by VincentK76** [comment]
Fyi, this problem has been resolved in version 0.3.1-preview package.

**Comment by olivertowers** [comment]
Issue fixed with 0.3.1-preview package. See [release notes](https://docs.microsoft.com/en-us/azure/cosmos-db/graph-sdk-dotnet).
