### ISSUE TITLE
Emulator running on local network throwing security error

### ISSUE THREAD

**Issue by declanmc** [Azure/azure-documentdb-dotnet#363]
I have set up the Cosmos DB emulator to run on one of the Windows Server 2012 R2 VMs in our local network as described here.

I have exported the certificate from the server and imported to my client machine. When I call my api which connects to the emulator through postman I get the following error:

`WinHttpException: A security error occurred                      
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw                       
System.Threading.Tasks.RendezvousAwaitable.GetResult()
System.Net.Http.WinHttpHandler&#x2B;&lt;StartRequest&gt;d__105.MoveNext()`

I can browse to the emulator explorer but I get the "Your connection is not private" message in Chrome and have to do the "proceed (unsafe)" to get to it.

The error message is pretty unhelpful but I'm presuming this is a certificate issue, and there is no way to bypass SSL when using the emulator. The guidance in the microsoft documentation is quite sparse on this issue also, do I need to generate a new certificate somehow when using the emulator on a local network?

**Comment by kirankumarkolli** [comment]
Please follow troubleshooting instructions at https://docs.microsoft.com/en-us/azure/cosmos-db/local-emulator#troubleshooting and send mail to askcosmosdb with the required details.

**Comment by joshuataylor** [comment]
This is not a Cosmos issue, but an certificate issue, we somehow need to distribute the certificates to the clients, or add a flag to allow insecure servers. So troubleshooting isn't relevant.

**Comment by YohanSciubukgian** [comment]
Can you add a flag to allow insecure connections for Dev/Test environment please ?
