### ISSUE TITLE
Question: how to properly update an Document with an JsonPatchDocument

### ISSUE THREAD

**Issue by MovGP0** [Azure/azure-documentdb-dotnet#367]
I am wondering what the best way to patch an document is, when I want to preserve the `ETag`:  

**Version 1**
```csharp
JsonPatchDocument<SomeType> patch = ...;

// getting the document
Document document = Client.CreateDocumentQuery<Document>(uri, options)
                            .SingleOrDefault(doc => doc.Id == id);

// Problem: does not work
patch.ApplyTo(document);

var response = await Client.ReplaceDocumentAsync(uri, document, new RequestOptions());
```

**Version 2**
```csharp
JsonPatchDocument<SomeType> patch = ...;

// getting the document
SomeType document = Client.CreateDocumentQuery<SomeType>(uri, options)
                            .AsQueryable()
                            .SingleOrDefault(doc => doc.Id == id);

// works
patch.ApplyTo(document);

// Problem: ETag missing; no check for concurrency issues 
var response = await Client.ReplaceDocumentAsync(uri, document, new RequestOptions());
```

**Comment by kirankumarkolli** [comment]
@MovGP0 optimistic concurrency requires [RequestOptions.AccessCondition](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.client.requestoptions.accesscondition?view=azure-dotnet#Microsoft_Azure_Documents_Client_RequestOptions_AccessCondition). 

FYR Sample https://github.com/Azure/azure-documentdb-dotnet/blob/1b22cac61ef2b9eeae9ddadbd850e48f023abc54/samples/code-samples/DocumentManagement/Program.cs#L433

**Comment by MovGP0** [comment]
@kirankumarkolli  albeit your information is very useful, the question was a different one: how to keep the `ETag` when casting to a specific type. 

The solution I have is to derive the POCO objects from the `Microsoft.Azure.Documents.Resource` class.
