### ISSUE TITLE
Update changelog for v1.18.0

### ISSUE THREAD

**Issue by nagytech** [Azure/azure-documentdb-dotnet#369]
Nuget and other sources specify that the v1.18.0 is the latest version, but no entry in the changelog.md file.

Can we get an update on what has changed since v1.17.0?

**Comment by kirankumarkolli** [comment]
@khdang  please update the change-log for 1.18.0

**Comment by kirankumarkolli** [comment]
Updated https://github.com/Azure/azure-documentdb-dotnet/blob/master/changelog.md
