### ISSUE TITLE
"Entity with the specified id does not exist in the system." Azure Function

### ISSUE THREAD

**Issue by chrisparkeronline** [Azure/azure-documentdb-dotnet#372]
Hi,

I receive a "Entity with the specified id does not exist in the system." when using the code bellow but only within a Azure Function in production. When I changed code to connect to my REST API, the same code within the Api works.

`_script = await _client.ReadDocumentAsync<Screenplay>(
                UriFactory.CreateDocumentUri( DatabaseId, CollectionId, myQueueItem.ScreenplayId ),
                new RequestOptions { PartitionKey = new PartitionKey( null ) } );`

Additional information. "parentId" is my partition key. This document has a null "parentId".

I have the firewall set to allow my local dev box IP address as well as the Azure Function Virtual IP address.

**Comment by kirankumarkolli** [comment]
null is handled differently in SDK. @chrisparkeronline please try 'Undefined.Value' as PartitionKey.

How is your REST API handling nulls?

**Comment by chrisparkeronline** [comment]
Hi, sorry for the delay. No sure what the issue was but recreating the partition with "/parentId" setup the partition using the path I wanted.

Additionally using the following code worked for me.

For documents with a null parentId, meaning no partition key (top level documents in my case), I used this code;
`var retVal = client
                    .CreateDocumentQuery<MyCustomObject>( Uri, query,
                        new FeedOptions { EnableCrossPartitionQuery = true, PartitionKey = new PartitionKey( null ) } ).AsEnumerable().FirstOrDefault();`

For documents that have a parentId, meaning sub documents of a top level document, I used this code;
`var retVal = client
                    .CreateDocumentQuery<MyCustomObject>( Uri, query,
                        new FeedOptions { EnableCrossPartitionQuery = true, PartitionKey = new PartitionKey( $"{parentIdValue}" ) } ).AsEnumerable().FirstOrDefault();`

Thank you for your help @kirankumarkolli.

**Comment by rnagpal** [comment]
@chrisparkeronline Just to clarify, when you pass "null" as the value of the partition key, it can be a valid value of your partition key. This is a different semantics than "missing" partition key from your document, in which case you need to pass Undefined.Value as Kiran mentioned above.

The exception that you are getting from ReadDocumentAsync API is expected if there is no such document. If you try running the same using the query approach you showed, you will get a "null"(and not an exception) for the retVal which means the same thing. It's a more graceful way to check for an existence of a document without throwing an exception and checking for 404 status code.

Please let me know if you have any further comments.
