### ISSUE TITLE
New MultiLineString in Microsoft.Azure.Documents.Spatial

### ISSUE THREAD

**Issue by ranouf** [Azure/azure-documentdb-dotnet#374]
Asp.net core 2.0
Microsoft.Azure.DocumentDB.Core 1.6.0

Hi,

I would like to create a new MultiLineString.
I can parse my GeoJson File, if it s a LineString I can convert my object to (LineString)object.
I tried to find an answer on the [MSDN](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.documents.spatial?view=azure-dotnet), but I didn find it.

But how to do the same with MultiLineString?

More information about MultiLineString: [here](https://docs.microsoft.com/en-us/sql/relational-databases/spatial/multilinestring)

Thank you for your help.
Cedric

**Comment by ranouf** [comment]
If I decompile the dll I can see the Class MultiLineString:

```
namespace Microsoft.Azure.Documents.Spatial
{
  internal sealed class MultiLineString : Geometry, IEquatable<MultiLineString>
  {
    [JsonProperty("coordinates")]
    public ReadOnlyCollection<LineStringCoordinates> LineStrings { get; private set; }

    public MultiLineString(IList<LineStringCoordinates> lineStrings)
      : this(lineStrings, new GeometryParams())
    {
    }

    public MultiLineString(IList<LineStringCoordinates> lineStrings, GeometryParams geometryParams)
      : base(GeometryType.MultiLineString, geometryParams)
    {
      if (lineStrings == null)
        throw new ArgumentNullException("lineStrings");
      this.LineStrings = new ReadOnlyCollection<LineStringCoordinates>(lineStrings);
    }

    internal MultiLineString()
      : base(GeometryType.MultiLineString, new GeometryParams())
    {
    }

    public override bool Equals(object obj)
    {
      return this.Equals(obj as MultiLineString);
    }

    public override int GetHashCode()
    {
      return this.LineStrings.Aggregate<LineStringCoordinates, int>(base.GetHashCode(), (Func<int, LineStringCoordinates, int>) ((current, value) => current * 397 ^ value.GetHashCode()));
    }

    public bool Equals(MultiLineString other)
    {
      if (other == null)
        return false;
      if (this == other)
        return true;
      return base.Equals((object) other) && this.LineStrings.SequenceEqual<LineStringCoordinates>((IEnumerable<LineStringCoordinates>) other.LineStrings);
    }
  }
}
```

Why did Microsoft hide it?

**Comment by ranouf** [comment]
I copy pasted the code from the dll. 
 I tried to convert my object Geometry to my MultilineString like : `(MultilineString)o.Geometry`. It doesnt work because the namespaces are different.
I tried to clone the object but MultilineString is not marked as Serializable.
I tried to clone using a JsonSerializer:
		```
public static TReturn Clone<TReturn>(dynamic source) where TReturn : class
		{
			Type currentType = source.GetType();

			DataContractJsonSerializer serializer = new DataContractJsonSerializer(currentType);
			DataContractJsonSerializer deserializer = new DataContractJsonSerializer(typeof(TReturn));
			using (MemoryStream ms = new MemoryStream())
			{
				serializer.WriteObject(ms, source);
				ms.Position = 0;
				return (TReturn)deserializer.ReadObject(ms);
			}
}
```

But I have this error:
System.Runtime.Serialization.InvalidDataContractException: 'Type 'Microsoft.Azure.Documents.Spatial.MultiLineString' cannot be serialized. Consider marking it with the DataContractAttribute attribute, and marking all of its members you want serialized with the DataMemberAttribute attribute. Alternatively, you can ensure that the type is public and has a parameterless constructor - all public members of the type will then be serialized, and no attributes will be required.'

I Set my MultiLineStrings constructur parameterless as Public. Same error.


Why Microsoft decided to hide MultilineString? I really need this class ....

I will to continue to search, any help will be appreciated

**Comment by ranouf** [comment]
Still need some help.

I tried to use Reflexion, but it doesnt work too.

		```
public static object GetProperty(this object o, string propertyName)
		{
			var property = o.GetType().GetProperty(propertyName);
			return property.GetValue(o);
		}
		public static TReturn GetProperty<TReturn>(this object o, string propertyName)
		{
			return (TReturn)GetProperty(o, propertyName);
		}
```

`var o = feature.Geometry.GetProperty<ReadOnlyCollection<object>>("LineStrings");`

I have an error saying can t cast from ReadOnlyCollection<LineStringCoordinates> to ReadOnlyCollection<object>

LineStringCoordinates  is private too ... What s wrong with Microsoft? Why did they take this decision? I really dont understand ...

So after i tried :
`var o = feature.Geometry.GetProperty<object>("LineStrings");`
With
	```
	public static object InvokeMethod(this object o, string methodName, params object[] args)
		{
			var method = o.GetType().GetMethod(methodName);
			return method.Invoke(o, args);
		}
		public static TReturn InvokeMethod<TReturn>(this object o, string methodName, params object[] args)
		{
			return (TReturn)InvokeMethod(o, methodName, args);
		}
```

But :
`o.InvokeMethod<IEnumerable<object>>("ToList")`
of
`o.InvokeMethod<IEnumerable<object>>("GetEnumerator")`

Doesnt work too ...

Is there someone who can ask to Microsoft why did they take the decision to put MultinLineString as private??? And ask to change it to public.

Or find a solution to my problem?

**Comment by ranouf** [comment]
So I finally choose to User JSon to get the value, but seriously it s dirty.

```
				var multiLineString = JToken.FromObject(feature.Geometry);
				points = multiLineString["coordinates"]
					.Select(coordinate => (JArray)coordinate)
					.SelectMany(positions => positions
						.Select(position => position.ToObject<IEnumerable<double>>())
						.Select(point => new Point(point.First(), point.Last()))
					)
					.ToList();
```

My opinion, MultinLineString need to be public.

I will close this issue when I will know why MultineLineString is private.

**Comment by bchong95** [comment]
Sorry for the late response. As of right now our indexing policy does not support MultiLineString:

https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet#1.10.0

The supported types are Point, LineString, Polygon, (and soon MultiPolygon). 

So we don't publicly have a DOM available for it, since to our backend it looks the same as a document that happens to have all the properties of a MultiLineString.

**Comment by bchong95** [comment]
I will close the issue for now. Please look out for future SDK releases with more geospatial support.

Please reopen if needed.
