### ISSUE TITLE
Method Skip is not supported while querying Cosmos DB

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-documentdb-dotnet#377]
Hi,

While i am trying to implement pagination in the cosmos db query. i am getting this error:

Microsoft.Azure.Documents.Client: Method 'Skip' is not supported.

Here is my C# code:

```
IDocumentQuery<T> query = client.CreateDocumentQuery<T>(
                UriFactory.CreateDocumentCollectionUri(DatabaseId, CollectionId),
                new FeedOptions { MaxItemCount = -1 })
                .Where(predicate)
                .Skip(pageIndex)
                .Take(pageSize) 
                .AsDocumentQuery();
```

How would i fix this? Thanks.

**Comment by kirankumarkolli** [comment]
@bchong95 can you please take a look?

**Comment by bchong95** [comment]
Hi,

We currently do not support Skip in SQL queries (and thus we don't support it for LINQ).

The workaround is to leverage the Continuation Token retrieved from executing the query.

This blog post talks about how this can be achieved:

http://www.kevinkuszyk.com/2016/08/19/paging-through-query-results-in-azure-documentdb/

Note that this method still consumes RUs to get to the skip point that you are interested in, so the recommendation is to keep these continuation tokens around for as long as possible. This means that if you have a webpage of paginated results, then you can periodically drain the query from start to finish and save the continuation tokens generated to have skip points. 

In the future we will support client side skips. 

Thank you,

**Comment by melzoghbi** [comment]
Thanks @bchong95. I am checking this solution out and will get back to you.

**Comment by melzoghbi** [comment]
This works. Thanks a lot @bchong95 :-) you can close this issue.

**Comment by pwen090** [comment]
I have seen on UserVoice that adding Skip and Take are being worked on but I cannot seem to find the github issue for that feature, is there one? thank you

**Comment by garfbradaz** [comment]
Starting my pagination journey for CosmosDB today, this does seem alittle painful not having skip.

**Comment by skram-softheme** [comment]
Take is already present, you can limit the number or items to get.
As for Skip, first we were upset that there is no Skip,  but later we realized that Skip would consume significant amount of RUs and such solution would not work in general case if you have thousands or millions documents.

So we allow pagination only by continuation token, e.g. virtual scroll etc. If you want to jump to page number 1000 - just use more specific query, like date time etc.

**Comment by georgiosd** [comment]
This is a serious shortcoming. I have to say, DocumentDB is missing a lot of features that I've taken for granted in https://github.com/ravendb/ravendb

**Comment by rmja** [comment]
[Here is the UserVoise issue for missing Skip](https://feedback.azure.com/forums/263030-azure-cosmos-db/suggestions/6350987--documentdb-allow-paging-skip-take) This is really something I expected would be baked in by now.

**Comment by garfbradaz** [comment]
Ive done paging fine without Skip.

**Comment by rmarskell** [comment]
@melzoghbi Can you please reopen this? The issue as stated has not been resolved and I didn't see any open issues this is a duplicate of. Based on the user voice link above, it's being worked on so it would be nice to be able to track it here.

**Comment by felipecruz91** [comment]
Any news on this?

**Comment by thiagospassos** [comment]
Wow, I'm really surprised this is not yet available. Any plans to work on this feature at all?

**Comment by vip32** [comment]
offset/limit (skip/take) is now available in cosmosdb
https://docs.microsoft.com/en-us/azure/cosmos-db/how-to-sql-query#OffsetLimitClause

**Comment by JohnnyFun** [comment]
Am I missing something silly, or does the emulator not support limit quite correctly?
![image](https://user-images.githubusercontent.com/8106379/57971345-c3c50f80-795a-11e9-818d-e6749fe50b61.png)

**Comment by vip32** [comment]
skip/take (linq) is being implemented in the new v3 cosmos client
https://github.com/Azure/azure-cosmos-dotnet-v3/issues/8

**Comment by vip32** [comment]
not sure if it will land in the current v2 @bchong95 ?
