### ISSUE TITLE
Latest version incompatible with latest emulator?

### ISSUE THREAD

**Issue by HaukiDog** [Azure/azure-documentdb-dotnet#380]
When I try to use 1.19.0 I get the following error when connecting to the emulator: "Invalid API version. Ensure a valid x-ms-version header value is passed". The issue does not happen when connecting to a hosted db. Downgrading to 1.18.1 does not result in issue.

Is there a new emulator available. I have 1.17.43.5.

**Comment by rnagpal** [comment]
@HaukiDog We will get a new emulator release out asap to address this issue.

**Comment by rnagpal** [comment]
This has been fixed in the latest release of the emulator today. Please upgrade.
