### ISSUE TITLE
Not compatable with Microsoft.Azure.DocumentDB.Core > 1.6.0

### ISSUE THREAD

**Issue by cschoede** [Azure/azure-documentdb-dotnet#384]
**Description**

Using Cosmos DB Emulator (1.17.29.4) with Microsoft.Azure.Document.DB.Core > 1.6.0 nuget package will throw an exception on client side.

**Technical Details**

- ASP.NET Core 2.0 (Debug Any CPU)
- Emulator 1.17.29.4
- Microsoft.Azure.DocumentDB.Core > 1.6.0

**Exception**

- **Message**: `One or more errors occurred. (Invalid API version. Ensure a valid x-ms-version header value is passed.
ActivityId: f26a0cac-6811-4826-b0b5-44abf43fa44d, Windows/10.0.15063 documentdb-netcore-sdk/1.7.1)`
  - **Inner Exception**: `Invalid API version. Ensure a valid x-ms-version header value is passed.
ActivityId: f26a0cac-6811-4826-b0b5-44abf43fa44d, Windows/10.0.15063 documentdb-netcore-sdk/1.7.1`

Linking to #185 As they have similar topics but not necessarily related issues.

Code
```csharp
using Microsoft.Azure.Documents;
using Microsoft.Azure.Documents.Client;
using System;
using System.IO;

namespace ConsoleApp1
{
    class Program
    {
        static void Main(string[] args)
        {
            try
            {
                using (var client = new DocumentClient(new Uri("https://localhost:8081"),
                    "C2y6yDjf5/R+ob0N8A7Cgv30VRDJIWEHLM+4QDU5DE2nQ9nDuVTqobD4b8mGGyPMbIZnqyMsEcaGQy67XIw/Jw=="))
                {
                    ResourceResponse<Database> resp = client.CreateDatabaseIfNotExistsAsync(new Database
                    {
                        Id = "Teams",
                    }).Result;

                    Console.WriteLine(resp.StatusCode);

                    using (var stream = new StreamReader(resp.ResponseStream))
                    {
                        Console.WriteLine(stream.ReadToEnd());
                    }
                }
            }
            catch(Exception e)
            {
                Console.WriteLine(e.Message);
            }
        }
    }
}
```

**Comment by rnagpal** [comment]
@cschoede  :  You need the latest version of the emulator in order to work with 1.7.0 and onwards. Please refer to the Release Notes of 1.7.0 for the download link : https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-sdk-dotnet-core
