### ISSUE TITLE
Portal generates wrong connection string for previously created CosmosDB for Table API

### ISSUE THREAD

**Issue by SeanFeldman** [Azure/azure-documentdb-dotnet#386]
`CloudTable.CreateIfNotExistsAsync()` and `CloudTable.CreateIfNotExists()` fail with exception

```
Microsoft.Azure.Storage.StorageException: 'The remote server returned an error: (400) Bad Request.'
```

Inspecting response with Fiddler shows

```json
{
  "code":"BadRequest",
  "message":"Request url is invalid.\r\nActivityId: 079aa362-28ef-4b7f-83b0-0e3bb1681357, Microsoft.Azure.Documents.Common/1.17.101.1"
}
```

**Steps to reproduce**

1. Clone a [sample application](https://github.com/Azure-Samples/azure-cosmos-db-table-dotnet-getting-started) from the [Table API documentation](https://docs.microsoft.com/en-us/azure/cosmos-db/tutorial-develop-table-dotnet).
1. Run the samle using original `WindowsAzure.Storage-PremiumTable` package version`0.1.0-preview`. `CreateIfNotExistsAsync/CreateIfNotExists` works as expected.
1. Replace `WindowsAzure.Storage-PremiumTable` package with `Microsoft.Azure.CosmosDB.Table` version `1.0.0` and `CreateIfNotExistsAsync/CreateIfNotExists` fails. 

Note: command also fails when a table **already exists**.

**Comment by SeanFeldman** [comment]
Futher investigation and [another sample](https://github.com/Azure-Samples/storage-table-dotnet-getting-started)(this time a right example) leads me to think that there's an issue with the portal and CosmosDB Table API instance created earler.

The database I used (West US):
![image](https://user-images.githubusercontent.com/1309622/33002754-69b2565e-cd73-11e7-97f6-4356413747ed.png)

But connection string generated was wrong:

![image](https://user-images.githubusercontent.com/1309622/33002794-9f1e9d16-cd73-11e7-89bf-fd761a9c3b61.png)

**Comment by SeanFeldman** [comment]
Also, documentation mixes old and new package based samples (https://github.com/Azure/azure-documentdb-dotnet/issues/386).

**Comment by yaronyg** [comment]
The preview SDK can be used with preview table accounts. The GA SDK can be used with GA table accounts. The two can't be mixed and matched. In this case I believe you are trying to use the GA SDK with a preview table. You can tell if a table is preview because it has a banner across it in the portal that reads "https://msdata.visualstudio.com/CosmosDB/CosmosDB%20Team/_workitems/edit/107577"

**Comment by SeanFeldman** [comment]
@yaronyg I had no tables in the DB and no banner.

I did notice today that the Overview page had the following:
![image](https://user-images.githubusercontent.com/1309622/33056822-f98737f0-ce44-11e7-8d9a-b879f71eb97f.png)

Not very indicative if you ask me. In the ocean of text, that should be a screaming colour and not a pleasent blue b/g 🙂

**Comment by yaronyg** [comment]
@SeanFeldman we are actively working on a new banner to try and make this all much clearer.
