### ISSUE TITLE
NetStandard Packages shouldn't be published in a different package

### ISSUE THREAD

**Issue by tonyferrell** [Azure/azure-documentdb-dotnet#387]
DocumentDb has two different packages: one supporting [.NET Standard](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/), and one supporting [.NET Framework](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/). This makes it very hard to build abstractions and libraries that target multiple frameworks.

Would it be possible to get a single package that supports targeting both?

**Comment by ausfeldt** [comment]
Resolved in 1.21.0 https://www.nuget.org/packages/Microsoft.Azure.DocumentDB/
