### ISSUE TITLE
Question: bulk insert graph

### ISSUE THREAD

**Issue by eosfor** [Azure/azure-documentdb-dotnet#391]
Hello colleagues,

Is there any option to bulk insert the graph, or import from GraphML or DOT?

Thanks

**Comment by olivertowers** [comment]
A bulk import .net library for COSMOSDB graph is in the works. Can give a firm ETA, but expecting a preview release by the end of December.

**Comment by burikella** [comment]
We're successfully using https://docs.microsoft.com/en-us/azure/cosmos-db/import-data for importing graph.

**Comment by eosfor** [comment]
Thanks very much!

**Comment by grahamehorner** [comment]
I’ve been attempting to import the OSM dataset into a graph without success, I believe a batch feature would help as the number of RUs would as I understand it be reduced as a result

FYI https://planet.openstreetmap.org/

**Comment by mcharters** [comment]
@olivertowers is there a preview release of a bulk import tool yet? If so, can I preview it please? 😄

**Comment by burikella** [comment]
@Raghu-Gurrala, yes, I'm using json. Each edge stored as separate document. It looks like following:
`{"label":"HAS","id":"{new-guid}","_sink":"{target-vertex-id}","_sinkLabel":"{target-vertex-label}","_vertexId":"{source-vertex-id}","_vertexLabel":"{source-vertex-label}","_isEdge":true}`

**Comment by mcharters** [comment]
Has anyone successfully bulk inserted graph JSON with partition keys? I was able to upload edges and vertices through the bulk insert tool but things broke down when I tried to add partitioning into the mix.

**Comment by jayantacs** [comment]
@riparkms : You should be good to go now!!

**Comment by QuantMonk** [comment]
Can confirm that I can access now. Thank you @jayantacs

**Comment by zebarooo** [comment]
@jayantacs - can you add me too please?

**Comment by pdekkers** [comment]
@jayantacs - can you add me too please?

**Comment by jayantacs** [comment]
@punitkshah @pdekkers : Done.

**Comment by jayantacs** [comment]
@pdekkers @punitkshah : Done

**Comment by punitkshah** [comment]
Works for me. I didn't have 2-factor Authentication set-up - had to therefore enable it.

**Comment by jayantacs** [comment]
@zebarooo :  I added you.

**Comment by zebarooo** [comment]
awesome, thanks!

**Comment by jayantacs** [comment]
@jmuthuku : Added you.

**Comment by jmuthuku** [comment]
thanks @jayantacs , but I am still not able to access it. Getting 404 Error.

**Comment by jayantacs** [comment]
@jmuthuku : can you try now?

**Comment by jmuthuku** [comment]
thanks again @jayantacs . I am able to access now (after enabling 2FA). After filling all the details in App.Config I tried to run GraphBulkImportTest but I am running into this error:

System.AggregateException: One or more errors occurred. ---> System.TypeLoadException: Could not resolve type with token 0100005e (from typeref, class/assembly System.Diagnostics.Eventing.EventProviderTraceListener, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
  at Microsoft.Azure.Documents.Client.DocumentClient.Initialize (System.Uri serviceEndpoint, Microsoft.Azure.Documents.Client.ConnectionPolicy connectionPolicy, System.Nullable`1[T] desiredConsistencyLevel) [0x00014] in <8b43155ec86d4fe3bef147f5d0a40526>:0
  at Microsoft.Azure.Documents.Client.DocumentClient..ctor (System.Uri serviceEndpoint, System.String authKeyOrResourceToken, Microsoft.Azure.Documents.Client.ConnectionPolicy connectionPolicy, System.Nullable`1[T] desiredConsistencyLevel) [0x00070] in <8b43155ec86d4fe3bef147f5d0a40526>:0
  at GraphBulkImportTest.Program+<TestBulkInSertAsync>d__3.MoveNext () [0x00051] in /Users/jayarajm/temp/Microsoft.Azure.Graphs.BulkImport-master/GraphBulkImportTest/GraphBulkImportTest/Program.cs:40
  --- End of inner exception stack trace ---
  at System.Threading.Tasks.Task.ThrowIfExceptional (System.Boolean includeTaskCanceledExceptions) [0x00011] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:2157
  at System.Threading.Tasks.Task.Wait (System.Int32 millisecondsTimeout, System.Threading.CancellationToken cancellationToken) [0x00043] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3189
  at System.Threading.Tasks.Task.Wait () [0x00000] in /Users/builder/data/lanes/5533/mono-mac-sdk/external/bockbuild/builds/mono-x64/mcs/class/referencesource/mscorlib/system/threading/Tasks/Task.cs:3054
  at GraphBulkImportTest.Program.Main (System.String[] args) [0x00001] in /Users/jayarajm/temp/Microsoft.Azure.Graphs.BulkImport-master/GraphBulkImportTest/GraphBulkImportTest/Program.cs:22

Any ideas how to get past this. I'd appreciate if you can let me know. Thanks

**Comment by jasonchester** [comment]
@jayantacs can you add me to the bulk import repo?

**Comment by jayantacs** [comment]
@jasonchester: You should have access now.

**Comment by gauravhub** [comment]
@jayantacs, For Java based applications, is there a similar library that we can use for bulk import?

**Comment by AbhishekTripathi** [comment]
@jayantacs Please provide access to me as well.

**Comment by J0nnie** [comment]
@jayantacs Can you provide med access as well. Thanks!

**Comment by gaport** [comment]
@jayantacs Can I get access to this as well. Thanks

**Comment by FSou1** [comment]
@jayantacs can you add me to the bulk import repo? Thanks

**Comment by whilke** [comment]
@jayantacs Can i also get access to the bulk import repo? Thanks

**Comment by tknandu** [comment]
@AbhishekTripathi @J0nnie @daviwu @FSou1 @whilke Have provided access. 

To be noted - we're going to be releasing Graph Import functionality in the BulkExecutor library (which was GAed) very shortly to make access easier - will update details here soon!

**Comment by PhilStollery** [comment]
Just at the point of needing to do this- perfect timing. Is this where it's being added? https://www.nuget.org/packages/Microsoft.Azure.CosmosDB.BulkExecutor/

**Comment by Tameshiwari** [comment]
FYI this provided link 

https://github.com/Microsoft/Microsoft.Azure.Graphs.BulkImport

is broken [404...] or someone just simply decided to remove the linked content from the map😒

**Comment by dagrkatyal** [comment]
@jayantacs Can you please provide me access to https://github.com/Microsoft/Microsoft.Azure.Graphs.BulkImport

**Comment by ainurt** [comment]
Hi @jayantacs  Can also get access to https://github.com/Microsoft/Microsoft.Azure.Graphs.BulkImport

Thanks!

**Comment by hugovanmens** [comment]
Hello @jayantacs, I would like access as well.
Thanks in advance!

**Comment by PhilStollery** [comment]
Any update on the official release?

**Comment by danvanderboom** [comment]
Could I get access to the bulk import tool as well? Thanks.

**Comment by jayantacs** [comment]
The tool is public now. 

https://github.com/Azure-Samples/azure-cosmosdb-graph-bulkexecutor-dotnet-getting-started/

**Comment by dmelgarejoPDESGO** [comment]
> @mcharters @Raghu-Gurrala : Please try this for Importing graph. It has partition key support https://github.com/Microsoft/Microsoft.Azure.Graphs.BulkImport
> 
> It's in preview and would be released soon. I have given you access to the repository.

Can you give me access to the repository? dmelgarejoPDESGO
