### ISSUE TITLE
Question: Is there a possibility of port exhaustion from many limited requests?

### ISSUE THREAD

**Issue by Jacob-McKay** [Azure/azure-documentdb-dotnet#392]
Our team is still investigating, but the only working theory we have left as to why our service plans keep running out of sockets (where the graph of: "TCPv4\ TCPv4 Connections Established" spikes at max and remains until restart/redeploy/scaling of the resources in the service plan) is that when documentdb starts rate limiting our requests under heavy load, the documentdb client is not releasing the ports it holds.

We will be working on a test to prove whether this is the case soon, but I thought it cheap to inform the docdb team in case they had some insight that may confirm or deny the risk of port exhaustion under heavy load when rate-limiting occurs.

Edit: I didn't ask a question and the title is listed as a question (woops).
The Question: Is there a chance the .net sdk is consuming and not release many of the sockets it's using?

**Comment by kirankumarkolli** [comment]
@Jacob-McKay docdb does connection pooling and has a timeout for the connections. 

How frequently is this happening and do you have a repro for this?

**Comment by Jacob-McKay** [comment]
We have a new theory that we're not handling our http connections well, so when one of our application apis is under heavy load and becomes unavailable due to a high number of 429 calls to it's database, consumers of that api and retrying and creating more connections that they aren't cleaning up.

We had a nightly job that would task docdb with many large requests causing the regular spike in 429's and subsequent socket exceptions.  Classic case of correlation not meaning causation.  I'll close this issue, thanks!
