### ISSUE TITLE
In some cases strings like "10.3" treated as a "Oct, 3" date and causes exception

### ISSUE THREAD

**Issue by burikella** [Azure/azure-documentdb-dotnet#396]
We encountered issue with some query structures, I've simplified our relatively complex query query up to following repro sample:
`g.V().and(__.out().has('value', '10.3'))`
This query causes exception

> Gremlin Query Compilation Error: Data type 'Date' not yet supported by Binary Comparison functions.

Any further simplification of the query doesn't cause exception anymore.

I've found only one workaround for this issue – using 10.3 as a number without quotes. But such trick is limited by another issue related with current culture, see #397.

**Comment by olivertowers** [comment]
I was unable to repro this issue. Are you connecting to a gremlin server or use Microsoft.Azure.Graphs

Can you provide a sample data set for which this is failing

For example Sample data format as a gremlin expression a which 
```
g.addV().property(id, "A").as("a").
  addV().property(id, "B").as("b").
  addV().property(id, "C").as("c").
  addV().property(id, "D").as("d").
  addV().property(id, "E").as("e").
  addE("created").from("a").to("d").
  addE("created").from("a").to("e").
  addE("created").from("b").to("e")

```

Also what is the current culture for your application?

**Comment by burikella** [comment]
I've created blank graph on Azure Portal, created following sample:
```
g.addV().property('id', 'Root').as('root')
  .addV().property('id', 'A').property('value', '10.3').as('a')
  .addE('has').from('root').to('a')
```
Then tried to execute query from original issue:
`g.V().and(__.out().has('value', '10.3'))`

This result in error:
```
Gremlin Query Compilation Error: Data type 'Date' not yet supported by Binary Comparison functions.
		ExceptionType : GraphCompileException
		Source : Microsoft.Azure.Graphs
		Context : graphclientext
		RequestId : ca48490a-ade3-42d7-8f5f-f9ba732785a4
		Scope : graphext-execquery
		Status : ScriptEvaluationError
		HResult : 0x80131500
```

**Comment by olivertowers** [comment]
@burikella Fix for this bug has been committed and will be rolled out with the next service release. 

Thanks for reporting this issue!

**Comment by burikella** [comment]
@olivertowers Thank you!

**Comment by olivertowers** [comment]
Bug is fixed on on the service, closing the issue.
