### ISSUE TITLE
Hire competent product manager

### ISSUE THREAD

**Issue by jackbond** [Azure/azure-documentdb-dotnet#430]
When the Nuget version for these packages is higher than the release notes, SOMEBODY ISN'T DOING THEIR JOB. This is NOT a new problem.

SDK release notes (only when the lazy hack decides to do his job)

https://github.com/Azure/azure-documentdb-dotnet/blob/master/changelog.md
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet

My guess is that I'm going to wait a few days and get no response. At that point, I'll drop the F bomb a few times on Twitter, and somebody will get off their ass.

**Comment by kirankumarkolli** [comment]
@jackbond release notes updates goes through documentation release process and which takes around 1 business day. Github release note is updated with 1.20.1 release notes.
