### ISSUE TITLE
Microsoft.Azure.Documents.Document is defined in both Microsoft.Azure.DocumentDB.Core and Microsoft.Azure.WebJobs.Extensions.DocumentDB

### ISSUE THREAD

**Issue by steevcoco** [Azure/azure-documentdb-dotnet#435]
I have an issue with being able to define `Microsoft.Azure.Documents.Document` helpers in a shared library, and use them in a function app that imports `Microsoft.Azure.WebJobs.Extensions.DocumentDB` for Cosmos bindings. (The function app is being written in Visual Studio on the net461 version --- and the class library so happens to be NetStandard2.0.)

My shared library references

    "Microsoft.Azure.DocumentDB.Core" Version="1.8.1"

To make some `Document`and `DocumentClient` helper classes. And my function app uses `CosmosDBTrigger` bindings; and so it must import

    Microsoft.Azure.WebJobs.Extensions.DocumentDB - 1.1.0

But that can't work because "`Document` exists in both NuGet references", so there is a conflict. Any advice on how to have a shared library with DocumentDb utilities while having Cosmos bindings in the function app? (A.k.a. why are there two NuGet libraries that separately define `Microsoft.Azure.Documents.Document`?)

P.S. I didn't import the `WebJobs.Extensions.DocumentDB` in my class library because that seems wrong ... Though that might solve my specific issue since that would seem to erase the conflict: but I don't know what all is included in the `WebJobs` NuGet --- first off --- and second, can I define a NetStandard shared library with that import?? Perhaps I'm asking a but much because I want to define my shared library as NetStandard --- or, perhaps I am right in that I shouldn't be trying to import `WebJobs.Extensions` in anything other than a function app itself ... I just want DocumentDb helpers in a shared NetStandard library, and import those into a function app with Cosmos bindings :-)

... Heh: this newbie is just waiting for the function apps v2 release to "turn everything into NetStandard" and erase any oddball NuGet crossed-up dependencies! How did I discover NuGet dll hell?!?

**Comment by kirankumarkolli** [comment]
@ealsur can you please look into this?

**Comment by ealsur** [comment]
@steevcoco I think your issue is because the `WebJobs.Extensions.DocumentDB` has a dependency on the `Microsoft.Azure.DocumentDB` nuget package. 
If you want to work with Net Standard / Core, you might need to wait until Functions V2 is released, where the Cosmos DB Extension actually uses the Core package.

Or make your library use the `Microsoft.Azure.DocumentDB` package, and not the Core version.

**Comment by steevcoco** [comment]
Yes: OK ... sorry. I can see the dependencies! Just a little confused ... Since 461 can consume NetStandard, I assumed I'd make the shared library NetStandard ... I got a little turned around with some previewing too. It seems clear. Thanks!
