### ISSUE TITLE
Graph - Multiple issues with parsing of numeric constants in the graph gremlin query

### ISSUE THREAD

**Issue by jasonchester** [Azure/azure-documentdb-dotnet#438]
Steps to reproduce.

I have tested this with both the Document Client extensions in C# as well as the Gremlin.Net native connection integers behaved the same between both gremlin.net however floats were not consistent.

quick summary of the issues 
* Negative sign lost in gremlin queries in both connections for ints/floats `g.V('').inject(-1)` 
* Syntax for passing a float constant in gremlin.net is not the same as the output format and does not round trip
* Unable to pass literal floating point constants in with Microsoft.Azure.Graphs when using the exponent form

with `<PackageReference Include="Microsoft.Azure.Graphs" Version="0.3.1-preview" />`
```
✔ executed in 00:00:00.0554110. 1.97 RUs. 1 results. 65 characters.
gremlin> g.V('').inject(-9223372036854775807).inject(-2147483647).inject(-1).inject(0).inject('neg ints:').fold()
[  "neg ints:",  0,  1,  2147483647,  9223372036854775807  ]
✔ executed in 00:00:00.0715030. 1.97 RUs. 1 results. 65 characters.

gremlin> g.V('').inject(-100.1).inject(-10000000000000000000.1).inject(-1E19D).inject(-1E308D).inject('neg float')
✖ Gremlin Query Compilation Error: Failed to interpret string "1E+19" into any data type.
```
with `<PackageReference Include="Gremlin.Net" Version="3.2.7" />`
```
gremlin> g.V('').inject(-9223372036854775807).inject(-2147483647).inject(-1).inject(0).inject('neg ints:')
[  "neg ints:",  0,  1,  2147483647,  9223372036854775807  ]
✔ executed in 00:00:00.3091340. 5 results. 0 characters.

gremlin> g.V('').inject(-100.1).inject(-10000000000000000000.1).inject(-1E19D).inject(-1E308D).inject('neg float')
[  "neg float",  1E+308,  1E+19,  1E+19,  100.1 ]
✔ executed in 00:00:00.1459430. 5 results. 0 characters.

gremlin> g.V('').inject(1E+19)
✖ ScriptEvaluationError:
ActivityId : f2678603-5fbd-4108-aee8-b5a59983eea1
ExceptionType : GraphCompileException
ExceptionMessage :
	Gremlin Query Compilation Error: Script compile error: Unexpected error encountered during query compilation
Source : Microsoft.Azure.Graphs
	GremlinRequestId : f2678603-5fbd-4108-aee8-b5a59983eea1
	Context : graphcompute
	Scope : graphparse-translate-outer
	GraphStatusCode : ScriptEvaluationError
	HResult : 0x80131500

ActivityId : f2678603-5fbd-4108-aee8-b5a59983eea1
ExceptionType : FormatException
ExceptionMessage :
	Input string was not in a correct format.
Source : mscorlib
	HResult : 0x80131537
```

on the azure portal data explorer the results were the same.

**Comment by olivertowers** [comment]
Confirmed that these bugs exists:

- Negative signs being lost on ints/floats
- Failing to parse numbers with exponents.

Fixes for these issues are in-progress. Note that the fixes will be applied to the Gremlin Server (so accessible via Gremlin.NET) and won't be available for Microsoft.Azure.Graphs.

Regarding syntax round trip, can you clarify the specific issue?

If this is referring to the following:

    g.inject(10000000000000000000.1) = [1E+19] 

The reason for this is that the implementation only support the core numeric types, which does not include BigDecimal. As is shown, CosmosDB Graph will parse BigDecimal values to a Double.

These are the supported constant types for CosmosDB Graph:

- String
- Int
- Long
- Float
- Double
- Boolean

**Comment by olivertowers** [comment]
These issues should now be resolved for the CosmosDB Gremlin server (via Gremlin.NET or other gremlin driver client).

As per my reply above, there are some cases that will still not round trip.
