### ISSUE TITLE
The read session is not available for the input session token.\r\nActivityId: bd45d180-1f9e-4df3-b085-13d5fb0ebeb1

### ISSUE THREAD

**Issue by siteshkumar5516** [Azure/azure-documentdb-dotnet#440]
Hi While searching from document DB getting issue
I am using SDK-1.17.0
"The read session is not available for the input session token.\r\nActivityId: c8ab0c4d-54bb-4f5a-9885-a04c4fbd8b59, \r\nResponseTime: 2018-03-01T10:29:57.5058455Z, StoreReadResult: StorePhysicalAddress: rntbd://10.234.121.187:14000/apps/2fc6e9a6-e2f7-40ec-b55d-5a316f28c4a1/services/5071e6b3-2aca-47c4-8aef-43877881b1ff/partitions/61e9abba-d1b8-4cda-b738-fac401d09030/replicas/131606293141634379s, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 0, IsGone: False, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: Query\r\nResponseTime: 2018-03-01T10:30:04.6958447Z, StoreReadResult: StorePhysicalAddress: rntbd://10.234.120.182:16700/apps/2fc6e9a6-e2f7-40ec-b55d-5a316f28c4a1/services/5071e6b3-2aca-47c4-8aef-43877881b1ff/partitions/61e9abba-d1b8-4cda-b738-fac401d09030/replicas/131606389825728977p, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 0, IsGone: False, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: Query\r\nResponseTime: 2018-03-01T10:30:12.0858493Z, StoreReadResult: StorePhysicalAddress: rntbd://10.234.123.56:14000/apps/2fc6e9a6-e2f7-40ec-b55d-5a316f28c4a1/services/5071e6b3-2aca-47c4-8aef-43877881b1ff/partitions/61e9abba-d1b8-4cda-b738-fac401d09030/replicas/131608651398947821s, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 0, IsGone: False, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: Query\r\nResponseTime: 2018-03-01T10:30:19.4258512Z, StoreReadResult: StorePhysicalAddress: rntbd://10.98.199.57:14000/apps/2fc6e9a6-e2f7-40ec-b55d-5a316f28c4a1/services/5071e6b3-2aca-47c4-8aef-43877881b1ff/partitions/61e9abba-d1b8-4cda-b738-fac401d09030/replicas/131608651398947820s, LSN: -1, GlobalCommittedLsn: -1, PartitionKeyRangeId: , IsValid: False, StatusCode: 0, IsGone: False, IsNotFound: False, IsInvalidPartition: False, RequestCharge: 0, ItemLSN: -1, ResourceType: Document, OperationType: Query\r\n, Microsoft.Azure.Documents.Common/1.20.0.0"

**Comment by kirankumarkolli** [comment]
@siteshkumar5516 we are looking into it on service side. I am closing this thread for now. 

Please send mail to 'askcosmosdb@microsoft.com' with below details 
1. How frequently is this happening and few time-ranges.
2. What's the impact of this on your application/service.
3. Cosmos DB account name
4. Related activity id's and if possible
