### ISSUE TITLE
Problem using the latest Microsoft.Azure.DocumentDB NuGet package with .NET Standard

### ISSUE THREAD

**Issue by Liversage** [Azure/azure-documentdb-dotnet#442]
I noticed that the `Microsoft.Azure.DocumentDB` NuGet package was updated to 1.21.0 and that `Microsoft.Azure.DocumentDB.Core` was updated to 1.9.0. Furthermore, the description for this package now contains the text

> This package has been deprecated and replaced by Microsoft.Azure.DocumentDB

It seems that I now should use `Microsoft.Azure.DocumentDB 1.21.0` everywhere in my solution. However, I have a full .NET framework application that has dependencies on .NET Standard 2.0 libraries using Cosmos DB and I'm experiencing some problems that can be reproduced as follows:

1. Create a new blank solution (File > New Project > Installed > Other Project Types > Visual Studio Solutions > Blank Solution)

2. Add a .NET Standard class library project (File > Add > New Project > Installed > Visual C# > .NET Standard > Class Library (.NET Standard))

3. Add a reference to the `Microsoft.Azure.DocumentDB 1.21.0` NuGet package to this project (Project > Manage NuGet Packages > Browse > Microsoft.Azure.DocumentDB > Install)

4. Add a full framework console application project (File > Add > New Project > Installed > Windows Classic Desktop > Console App (.NET Framework))

5. Add a reference from the console application to the library (Project > Add Reference > Projects > ClassLibrary1 > OK)

6. In the class library add a public static field of type `IDocumentClient` to `Class1`

7. Verify that the solution compiles

8. In the console application retrieve the value of the field added in 6.

The solution no longer compiles. The error message is

> The type 'IDocumentClient' is defined in an assembly that is not referenced. You must add a reference to assembly 'Microsoft.Azure.DocumentDB.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.	FullFrameworkApplication	C:\Users\Martin\Source\Repos\CosmosDB\FullFrameworkApplication\Program.cs	9	N/A

So I'm instructed to add a reference to the NuGet package that has been deprecated. Even though adding this package fixes the compile error it doesn't seem right. In fact, it is the "core" package that I have to add to the full framework project to fix the compile error.

Can you please provide some guidance on how to use the latest version of Microsoft Azure Cosmos DB .NET SDK with .NET Standard libraries?

**Comment by ausfeldt** [comment]
Thanks, I was able to reproduce. Working on a fix now.

**Comment by ausfeldt** [comment]
When you install the package it installs the .net framework assembly because the console app targets .net framework, but you want the .net standard assembly. Both versions are in the same package. For now make sure it references the .net standard assembly by editing your csproj from

```XML
<Reference Include="Microsoft.Azure.Documents.Client, Version=1.21.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
  <HintPath>..\packages\Microsoft.Azure.DocumentDB.1.21.0\lib\net45\Microsoft.Azure.Documents.Client.dll</HintPath>
</Reference>
<Reference Include="Newtonsoft.Json, Version=6.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
  <HintPath>..\packages\Newtonsoft.Json.6.0.8\lib\net45\Newtonsoft.Json.dll</HintPath>
  <Private>True</Private>
</Reference>
```
To

```XML
<Reference Include="Microsoft.Azure.DocumentDB.Core, Version=1.9.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35, processorArchitecture=MSIL">
  <HintPath>..\packages\Microsoft.Azure.DocumentDB.1.21.0\lib\netstandard1.6\Microsoft.Azure.DocumentDB.Core.dll</HintPath>
</Reference>
<Reference Include="Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
  <HintPath>..\packages\Newtonsoft.Json.9.0.1\lib\net45\Newtonsoft.Json.dll</HintPath>
</Reference>
```

And update the packages.config from

```XML
<package id="Microsoft.Azure.DocumentDB" version="1.21.0" targetFramework="net461" />
<package id="Newtonsoft.Json" version="6.0.8" targetFramework="net461" />
```
to

```XML
<package id="Microsoft.Azure.DocumentDB" version="1.21.0" targetFramework="netstandard1.6" />
<package id="Newtonsoft.Json" version="9.0.1" targetFramework="netstandard1.6" />
```

**Comment by kirankumarkolli** [comment]
@Liversage please use the work-around above while we address the issue in the package.

**Comment by Liversage** [comment]
@ausfeldt @kirankumarkolli Thank you for you response. The workaround that I'm successfully using in my solution is to add the deprecated package as a dependency of my full framework project.

I have converted all my projects (also the full framework project) to the new "lean" .csproj format so I'm actually not sure how to apply the `HintPath` used in your workaround. However, as I have working solution that is not a problem.

**Comment by kirankumarkolli** [comment]
@Liversage single nuget package is unlisted and newer independent versions are published. Please use https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/.

**Comment by xfzhang1974** [comment]
Is there any dependency of Microsoft.Azure.DocumentDB v2.1.3 on some other packages? 
I tried to use Cosmos DB as chatbot conversion data store, and the package versions I have used are
Microsoft.Bot.Builder v3.16.1.38846
Microsoft.Bot.Builder.Azure v3.16.1.38846
Microsoft.Bot.Connector v3.16.1.38846
and I always receive the below exception

Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.IDocumentClient.DeleteDocumentAsync(System.Uri, Microsoft.Azure.Documents.Client.RequestOptions)'.

**Comment by xfzhang1974** [comment]
Does Microsoft.Azure.DocumentDB v2.1.3 has any hard dependency on any specific version of some other packages?
I tried to set up Cosmos DB as chatbot conversation data store.
The version I used for Microsoft.Bot.Builder, Microsoft.Bot.Builder.Azure and Microsoft.Bot.Connector is 3.16.1.38846. And I alway got the below exception

Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Azure.Documents.Client.ResourceResponse`1<Microsoft.Azure.Documents.Document>> Microsoft.Azure.Documents.IDocumentClient.DeleteDocumentAsync(System.Uri, Microsoft.Azure.Documents.Client.RequestOptions)'.

**Comment by Liversage** [comment]
@xfzhang1974 I'm not sure your problem is relevant to this issue. However, the error you get indicates that there is a serious version mismatch.

With the version that you list I would expect that you have a dependency on `Microsoft.Bot.Builder.Azure 3.16.1.38889` which has a dependency on `Microsoft.Azure.DocumentDB >= 1.22.0`. You seem to be having a dependency on `Microsoft.Azure.DocumentDB 2.1.3`. You could try to change this to `Microsoft.Azure.DocumentDB 1.22.0`. If your project is .NET Core you can simply remove the dependency as NuGet properly will handle the transitive dependencies but if you have a full framework project adding a dependency on a specific package version can fix some problems.

**Comment by xfzhang1974** [comment]
@Liversage Thanks for the information. 
I got my chatbot working with Cosmos DB. 
Here are the ddl versions that work for me.
Microsoft.Bot.Builder.Azure 3.16.1.38846
Microsoft.Azure.DocumentDB  1.22.0.0

BTW, I had a hard time with NuGet, which didn't update web.config automatically.
