### ISSUE TITLE
Microsoft.Azure.DocumentDB 1.21.0 issues

### ISSUE THREAD

**Issue by FelschR** [Azure/azure-documentdb-dotnet#443]
I'm getting the following issues in my unit tests after upgrading:

.NET Framework 4.5.2:
```
Error Message:
 System.AggregateException : One or more errors occurred.
---- Microsoft.Azure.Documents.DocumentClientException : Message: {"Errors":["Owner resource does not exist"]}
ActivityId: 24f7ab71-6c7e-4ea9-94dd-6b26bcbf0aa6, Request URI: /apps/DocDbApp/services/DocDbMaster0/partitions/780e44f4-38c8-11e6-8106-8cdcd42c33be/replicas/1p/
```

.NET Core 1.0 & .NET Core 2.0:
```
[xUnit.net 00:00:04.2013498]       System.AggregateException : One or more errors occurred. (Invalid API version. Ensure a valid x-ms-version header value is passed.
[xUnit.net 00:00:04.2014028]       ActivityId: b1bb6273-79b8-475c-9ecd-1c90e49c609d, Windows/10.0.14393 documentdb-netcore-sdk/1.9.0)
```

The unit tests use the Cosmos DB Emulator (which might not support the new library version yet?)

My project is a library with .NET Framework & .NET Standard as target.
My unit test projects are running the tests for .NET Framework 4.5.2, .NET Core 1.0 and .NET Core 2.0.

Strangely the errors only occur on my AppVeyor build and not when I run the unit tests locally.

My project:
https://github.com/FelschR/AspNetCore.Identity.DocumentDB/tree/master
https://ci.appveyor.com/project/FelschR/aspnetcore-identity-documentdb/build/1.1.0-master-47

**Comment by ausfeldt** [comment]
What is the version of the emulator that the tests fail against?

**Comment by FelschR** [comment]
On the build server I download it from https://aka.ms/cosmosdb-emulator each time the build runs.

Locally I have 1.20.108.4 which I also got from the link yesterday,

**Comment by ausfeldt** [comment]
@FelschR 1.21.0 has been unlisted. Does  this issue exist with 1.20.2?

**Comment by cecilphillip** [comment]
Also, version 1.3.0 of the ChangeFeedProcessor still references 1.21.0 which causes build warnings when the ChangeFeedProcessor is added to a project with 1.20.2 already installed.

**Comment by kirankumarkolli** [comment]
1.21.1 version published and now changefeedprocessir should be consumable. 
Apologies for the in-convenience.

**Comment by kirankumarkolli** [comment]
Resolving the bug for now. In-case of any issues, please re-activate or create a new bug.
