### ISSUE TITLE
DocumentClientException during heavy load

### ISSUE THREAD

**Issue by luk-zar** [Azure/azure-documentdb-dotnet#448]
Hi,
We are performing performance tests with our system (azure function) utilizing CosmosDB as data store. We use singleton approach with DocumentClient as presented here: https://github.com/Azure/azure-functions-host/wiki/Managing-Connections

But among 600k requests we got about 21k errors with simmilar error message:

> The input authorization token can't serve the request. Please check that the expected payload is built as per the protocol, and check the key being used. Server used the following payload to sign: 'get
>
>
>mon, 12 mar 2018 14:55:41 gmt
>
>'
>ActivityId: b3944cde-e55d-430d-98e0-03eaaa01e199, Microsoft.Azure.Documents.Common/1.21.0.0

I've googled this message and it seems that it could be connected with wrong characters in document id, but it is not the case in our app, because we use the same pattern for ids.

So, what could the cause for these kind of errors? Is it connected with heavy load? Or is it possible for us to find detailed error messages connected to this activityid?

Below is exception call stack:

>Inner exception Microsoft.Azure.Documents.DocumentClientException handled at Microsoft.Azure.WebJobs.Script.Description.DotNetFunctionInvoker.GetTaskResult:
>   at Microsoft.Azure.Documents.Client.ClientExtensions+<ParseResponseAsync>d__4.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.GatewayServiceConfigurationReader+<GetDatabaseAccountAsync>d__0.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Routing.GlobalEndpointManager+<GetDatabaseAccountFromAnyLocationsAsync>d__0.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.GatewayServiceConfigurationReader+<InitializeReaderAsync>d__b.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.DocumentClient+<InitializeGatewayConfigurationReader>d__35d.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.DocumentClient+<GetInitializationTask>d__29.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.DocumentClient+<EnsureValidClientAsync>d__44.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.Client.DocumentClient+<ReadDocumentPrivateAsync>d__193`1.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.BackoffRetryUtility`1+<>c__DisplayClass2+<<ExecuteAsync>b__0>d__4.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteAsync>d__a.MoveNext (Microsoft.Azure.Documents.Client, Version=1.14.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
>   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
>   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)

**Comment by kirankumarkolli** [comment]
@luk-zar did you check if failures are correlating to an instance which might have a stale key?

Also are you using resource tokens or master key?

**Comment by luk-zar** [comment]
Hi @kirankumarkolli ,
It turned out that we had problems with appSettings passed from azure function down to our CosmosDB services. They were not always valid (and we use the same for whole application). We temporary fixed it by getting appSettings directly in out CosmosDB service (using Environment.GetEnvironmentVariable). It is not elegant but it is working... If it is not bug in our code then it seems that it is connected to azure function runtime, I guess.

**Comment by kirankumarkolli** [comment]
@luk-zar glad that you are unblocked. Please report this to azure functions. 
Closing this thread, feel free to re-open if needed.
