### ISSUE TITLE
Where is the changelog for the NET Standard SDK?

### ISSUE THREAD

**Issue by filipw** [Azure/azure-documentdb-dotnet#449]
The main repo changelog https://github.com/Azure/azure-documentdb-dotnet/blob/master/changelog.md only covers the .NET Framework SDK.
Where is the changelog for the [.NET Standard SDK](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.Core/)?

**Comment by ausfeldt** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-dotnet-core
