### ISSUE TITLE
Unable to create user permission for database

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-documentdb-dotnet#469]
I'm trying to add a permission for a user with the following code:
```csharp
private async Task CreatePermissionAsync()
{
    const string endpoint = "https://<redacted>.documents.azure.com:443/";
    const string authKey = "<redacted>";
    const string databaseId = "ToDoList";
    const string userId = "foobar";
    
    using (var client = new DocumentClient(
        new Uri(endpoint),
        authKey,
        new ConnectionPolicy { ConnectionMode = ConnectionMode.Direct, ConnectionProtocol = Protocol.Tcp }))
    {
        var dbUri = UriFactory.CreateDatabaseUri(databaseId).ToString();
        var userUri = UriFactory.CreateUserUri(databaseId, userId).ToString();
        await client.CreatePermissionAsync(
            userUri,
            new Permission
            {
                Id = "DatabasePermission",
                PermissionMode = PermissionMode.All,
                ResourceLink = dbUri,
                ResourcePartitionKey = new PartitionKey(userId)
            });
    }
}
```

(The database and the user already exist)

This code fails with the following exception:

> **DocumentClientException:**: Message: {"Errors":["The input Resource link 'dbs\/ToDoList' is invalid. Ensure to provide a valid resource link of size lesser than '256' characters.","The request payload is invalid. Ensure to provide a valid request payload."]}

I'm not sure where the `\` is coming from (it wasn't there in the `dbUri` variable); could it be the cause of the problem?

If not, how am I supposed to create a user permission for the database?

**Comment by thomaslevesque** [comment]
I looked at the request with Fiddler; the `\` isn't in the request, so it's probably not the issue.

```http
POST https://<redacted>.documents.azure.com/dbs/ToDoList/users/foobar/permissions HTTP/1.1
x-ms-date: Wed, 04 Apr 2018 07:43:45 GMT
authorization: <redacted>
Cache-Control: no-cache
x-ms-consistency-level: Session
User-Agent: documentdb-dotnet-sdk/1.21.1 Host/32-bit MicrosoftWindowsNT/10.0.16299.0
x-ms-version: 2017-11-15
Accept: application/json
Host: <redacted>.documents.azure.com
Content-Length: 108
Expect: 100-continue

{"id":"DatabasePermission","permissionMode":"All","resource":"dbs/ToDoList","resourcePartitionKey":["foobar"]}
```

```http
HTTP/1.1 400 Bad Request
Content-Type: application/json
Server: Microsoft-HTTPAPI/2.0
x-ms-last-state-change-utc: Thu, 29 Mar 2018 22:45:17.304 GMT
x-ms-schemaversion: 1.5
x-ms-quorum-acked-lsn: 13
x-ms-current-write-quorum: 3
x-ms-current-replica-set-size: 4
x-ms-xp-role: 1
x-ms-global-Committed-lsn: 13
x-ms-number-of-read-regions: 0
x-ms-transport-request-id: 0
x-ms-request-charge: 1.24
x-ms-serviceversion: version=1.21.0.0
x-ms-activity-id: 7b49af75-b83f-4e6c-8a3e-8fdbd3aea3c5
x-ms-session-token: 0:13
Strict-Transport-Security: max-age=31536000
x-ms-gatewayversion: version=1.21.0.0
Date: Wed, 04 Apr 2018 07:43:41 GMT
Content-Length: 567

{"code":"BadRequest","message":"Message: {\"Errors\":[\"The input Resource link 'dbs\\/ToDoList' is invalid. Ensure to provide a valid resource link of size lesser than '256' characters.\",\"The request payload is invalid. Ensure to provide a valid request payload.\"]}\r\nActivityId: 7b49af75-b83f-4e6c-8a3e-8fdbd3aea3c5, Request URI: /apps/7d397473-3b24-4bb1-afff-6c023af05d38/services/667fd8e9-c889-4383-b8fe-fed9e6887ae9/partitions/56d39fa9-26ee-40f1-9d7a-fc629454c07b/replicas/131668371121495083p, RequestStats: , SDK: Microsoft.Azure.Documents.Common/1.21.0.0"}
```

**Comment by thomaslevesque** [comment]
OK, apparently I can't give permission to a user for the whole database... I have to do it separately for each collection individually. Which means I need to use a different resource key for each collection. Or am I missing something?

(Note that I tried passing a wildcard (`/dbs/ToDoList/colls/*`) as the resource, and it was accepted, but didn't actually give me permission to access anything)

**Comment by thomaslevesque** [comment]
@Mike-Ubezzi-MSFT thanks, I saw this page already. But it didn't say clearly on what kind of resource I could create a permission. I tried to create it on the database, and it didn't work, but the error message I received wasn't helpful at all to help me understand the problem.

Anyway, I solved my problem, although the Cosmos DB permission system isn't what I hoped it would be...

**Comment by sauravsarangi** [comment]
Hi,
So is it correct to assume, that I can not set permission for the DB level for a user and I have to create the user and provide permission for all the Collections in that database one by one?

**Comment by thomaslevesque** [comment]
@sauravsarangi yes, that's correct
