### ISSUE TITLE
Cannot execute stored procedures using emulator

### ISSUE THREAD

**Issue by wpitallo** [Azure/azure-documentdb-dotnet#487]
Cannot execute stored procedures using emulator

**Comment by moderakh** [comment]
@wpitallo can you please provide more explanation. Are you getting failure? what's your sample repro code? emulator, sdk version, etc.

**Comment by David-Noble-at-work** [comment]
@wpitallo, 

I'm assuming that as you said on another thread that what you're talking about is adding a new feature to the Emulator's Web UI:

- Execute stored procedures from the Web UI

Is that the case? This is a feature that we just added to our backlog and expect to release it soon.

**Comment by wpitallo** [comment]
@David-Noble-at-work , correct it is the same as on the other thread from the Web UI
