### ISSUE TITLE
Change Feed Processor v1.3.x Leaks Connections

### ISSUE THREAD

**Issue by jabberwik** [Azure/azure-documentdb-dotnet#494]
It appears that version >=1.3 of the Change Feed Processor library is opening new observers and not properly closing them, resulting in eventual saturation of host resources.

After our production cluster stopped responding, we noticed the following pattern for our CosmosDB total requests:
![change-feed-incident-total-cosmosdb-requests](https://user-images.githubusercontent.com/239954/39609656-2ff63cfe-4f10-11e8-8a70-b05f67e93db9.png)
* The start of the ramp at the left is when we deployed a new code package which upgraded the library from version 1.2.0 to 1.3.2. We had been operating stably with 1.2.0 for some time.
* The spikes along the way are known events from some data batches being loaded.
* At approximately noon (the instability in the middle of the graph), our cluster became unresponsive. We observed minimal performance degradation up to this point. We could still query CosmosDB from non-cluster hosts.
* The subsequent drop-offs of the ramp resulted from shutting off the service which used the Change Feed for some (but not all) tenants.
* The ramp disappeared when we deployed a new version which rolled back the Change Feed Processor to version 1.2.0, with no other changes rolled back.

We emit log entries when our `IChangeFeedObserver.OpenAsync` and `IChangeFeedObserver.CloseAsync` methods are called. We observed the following pattern:
![change-feed-incident-observer-start-vs-close](https://user-images.githubusercontent.com/239954/39609808-4588c798-4f11-11e8-9afc-dfa14c2e4cb2.png)
* The blue line shows instances when `OpenAsync` was called.
* The other lines show instances when `CloseAsync` was called, broken out by `ChangeFeedObserverCloseReason`.

This graph demonstrates that after the deployment, `OpenAsync` was being called constantly with no corresponding `CloseAsync` events, up until the cluster collapsed. From this, plus the complete mitigation of the issue by merely rolling back to v1.2.0, we have concluded that a change in the 1.3 versions caused the issue. Since this library is not open-source, I cannot speculate as to any further causes.

**Comment by ealsur** [comment]
Actually, the code for that version of the CFP is [here](https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/ChangeFeedProcessor).

The new CFP version (2.0) has it's own repo: https://github.com/azure/azure-documentdb-changefeedprocessor-dotnet. It is available in [Nuget as pre-release](https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.ChangeFeedProcessor/2.0.1-prerelease). The release notes are here: https://docs.microsoft.com/azure/cosmos-db/sql-api-sdk-dotnet-changefeed#pre-release-builds.

What you are seeing are not leaking connections, the metrics show an increase in the Requests. In the screenshot, there are mainly `LeaseLost` reasons, which I believe might indicate another Processor stealing the leases or an error in the `ProcessChangesAsync` method. The main changes in 1.3.x were dependencies (bumped to 1.20.x on the SDK) and stability improvements, did you change the SDK nuget package in your project too?

I think @mkolt knows how you can turn on extra logs on the application to see what is happening with the Leases. 

Just to verify, does your `ProcessChangesAsync` method have a global try/catch method to avoid the closing of the Observer in case of an exception?

**Comment by jabberwik** [comment]
The code at that location is out-of-date. The commit date is Jan 25th and the [user-agent](https://github.com/Azure/azure-documentdb-dotnet/blob/4da1ef7ff04e3cc0fbf53d67943560290dc74f6f/samples/ChangeFeedProcessor/DocumentDB.ChangeFeedProcessor/ChangeFeedEventHost.cs#L84) indicates we are looking at version 0.3.4 there.

We are using .NET Core 2.0. The deployment also upgraded the DocDb.Core SDK from 1.7.1 to 1.9.1, but we did not change that version in the rollback which solved the issue.

Our `ProcessChangesAsync` does have a global try/catch, and we log any exceptions that it catches. There were no logs at any point from that method.

Why would there be so many `OpenAsync` calls with no corresponding `CloseAsync` when our code is not throwing any exceptions? The event host appears to be gradually creating thousands of observers and never closing them.

**Comment by jabberwik** [comment]
At the time we were running 3 instances of the service, each on a different host with a different host name. When the problem started, we saw (# of partitions + 1) documents in each lease collection, as expected. I didn't audit the contents of each document but at a glance they looked the same as they ever did.

Once the spikes started, all the `LeaseLost` reasons were because the observers were suddenly unable to communicate with CosmosDB, causing an exception to be thrown and crash the service. The stack traces for these have been thoroughly mangled by async/await and App Insights, but I put one in a [gist here](https://gist.github.com/jabberwik/56256b01051cebf1aed36cc523dc2699) if you're interested.

Due to how the Service Fabric SDK operates, these crashes did not result in a new `ChangeFeedEventHost` object being created--it was reused, along with the thousands of observers it had created, which means the unresponsiveness persisted rather than immediately resolving itself.

But this itself is not the root issue; had our services crashed like a normal service, we would be restarting every 18 hours or so as the connection ramp hits a critical point.

**Comment by ealsur** [comment]
Apparently it fails on the [RegisterObserverFactoryAsync](https://gist.github.com/jabberwik/56256b01051cebf1aed36cc523dc2699#file-stacktrace-json-L288), trying to call [GetDatabaseAccount](https://gist.github.com/jabberwik/56256b01051cebf1aed36cc523dc2699#file-stacktrace-json-L48) on the Core 1.9.1 library. It doesn't show what's the actual error though.

@mkolt Do you think any of the extra logging could shed some light on the real error?

**Comment by jabberwik** [comment]
I want to make sure we're on the same page about what the "real error" is. This pattern at the left of the second graph is what concerns me:
![image](https://user-images.githubusercontent.com/239954/39642478-775a775e-4f97-11e8-87b7-d759aa060830.png)

Each dot on that blue line represents ~10 times that `IChangeFeedObserver.OpenAsync` has been called -- about once every 30 seconds. No exceptions are seen during this time. There are no `LeaseLost` occurrences during this time, or any other calls to `IChangeFeedObserver.CloseAsync`. These observers are sticking around and continuing to poll the database at an ever-increasing volume.

**Comment by mkolt** [comment]
In 1.x version when multiple instances of CFP are started at the same time, they potentially can try to take all leases, shortly that would stabilize (leases would be lost). Version 2.x has more deterministic start. How about this: can you try v2.x and see if the issue persists?

**Comment by mkolt** [comment]
Also to diagnose, enable tracing, see https://github.com/Azure/azure-documentdb-changefeedprocessor-dotnet (this tells how to enable tracing for both v2 and v2 using v1 API which would be same as tracing for v1).

**Comment by jabberwik** [comment]
.NET Core does not support trace listeners. Separate issue, but I'd prefer you all use the same `ILogger` interface as every other MS library these days.

Our lease store was in use for weeks prior to this upgrade and we did not purge any lease documents as part of the upgrade. Our `ProcessChangesAsync` calls were operating normally from deployment up until everything started crashing. Despite so many observers existing, it appears that it was still routing the changes to a correct one.

We will try v2 and let you know what happens.

**Comment by jabberwik** [comment]
We tried using the v2 library and did not see the issue anymore. We also observed that running locally with v1.3 did not show the issue either. We are currently seeing if a change in .NET Core runtimes has any effect; our workstations are currently ahead of our build agents.

**Comment by diaconesq** [comment]
Possibly not related, but if by any chance you are using `host.GetEstimatedRemainingWork()`, it keeps adding (new) observers to the host each time it is called, in v. 1.3.1 and 1.3.2. Version 1.3.3 seems to have fixed it.

**Comment by jabberwik** [comment]
We are calling the work estimator every 5 minutes; that could definitely be the source of the problem, and explain why we didn't see it locally. Glad it got fixed!

**Comment by mkolt** [comment]
Yes, this was fixed in 1.3.3. BTW in v2 this was never an issue.
