### ISSUE TITLE
Supported LINQ operators ?

### ISSUE THREAD

**Issue by thomaslevesque** [Azure/azure-documentdb-dotnet#513]
I have something like this:

```csharp
...
.Where(x => x.Items.Any(i => i.Type == itemType && i.Name == itemName))
```

And it throws _DocumentQueryException: Method 'Any' is not supported._

A possible SQL query to achieve the same result would be something like this:

```sql
SELECT VALUE c
FROM c
JOIN i in c.Items
where i.Type = @itemType and i.Name = @itemName
```

Is there a list of which LINQ operators are supported in document queries?

**Comment by Cephei** [comment]
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#Linq
Scroll down and you'll see a list of supported operations. I came here looking for additional support for LINQ set operations `Except`, `Distinct`, `Intersect`, `Union`

**Comment by thomaslevesque** [comment]
@Cephei thanks! Never noticed this before...

**Comment by JoeBrockhaus** [comment]
> https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sql-query#Linq
> Scroll down and you'll see a list of supported operations. I came here looking for additional support for LINQ set operations `Except`, `Distinct`, `Intersect`, `Union`

This looks like what was the intended link: https://docs.microsoft.com/en-us/azure/cosmos-db/sql-query-linq-to-sql#SupportedLinqOperators
