### ISSUE TITLE
Using Microsoft.Azure.DocumentDB.TransientFaultHandling with 1.22.0

### ISSUE THREAD

**Issue by nithinmohantk** [Azure/azure-documentdb-dotnet#514]
Does it make sense to use Microsoft.Azure.DocumentDB.TransientFaultHandling further with 1.22.0, as it seems the CosmosDB SDK For .NET seems to be tweaked for TransientFaultHandling internally.

So should we need the package any more with latest SDKs 
https://www.nuget.org/packages/Microsoft.Azure.DocumentDB.TransientFaultHandling/

**Comment by kirankumarkolli** [comment]
Equivalent of transient fault handling is in-build and on by-default in document db SDK. Also please note that TransientFaultHandling is very old and not actively developed and will be deprecated shortly.
