### ISSUE TITLE
Gremlin query compile error

### ISSUE THREAD

**Issue by FSou1** [Azure/azure-documentdb-dotnet#522]
I'm not quite sure the right place for this issue, but following this [post](https://tsmatz.wordpress.com/2017/07/04/azure-cosmos-db-gremlin-graph-tutorial/) I've faced with the compile error at this query:

`g.V('u001').repeat(in('manager')).until(has('id', 'u006')).path()`

> Failed to execute query: g.V('u001').repeat(in('manager')).until(has('id', 'u006')).path(): Script eval error: 
>  ActivityId : d3ed91c7-a973-400e-8c89-0c069411bfd3 ExceptionType : GraphCompileException ExceptionMessage :
>  Gremlin Query Compilation Error: Script compile error: Unexpected token: ')'; in input: 'g.V('u001').repeat(in('manager'))'. @ line 1, column 33. Source : Microsoft.Azure.Graphs GremlinRequestId : d3ed91c7-a973-400e-8c89-0c069411bfd3 Context : graphcompute Scope : graphparse-translate-outer GraphStatusCode : ScriptEvaluationError HResult : 0x80131500

I've changed different parts of the query and figured out that the issue occured with `in('manager')` statement. Whether it's replaced with `out('manager')` the query compiles.

**Comment by olivertowers** [comment]
`as` and `in` are keywords in groovy grammar, so to avoid syntax errors they will need to be qualified as static member references, like so: `__.as()` or `__.in()`.

**Comment by jasonchester** [comment]
Thanks for the explanation. 

I ran into this as well and it always bothered me that something like .by(out()) worked while .by(in()) did not.

Is there an FAQ section or some other place in the docs to capture these got gotchas? Tinkerpop's Gremlin documentation is a bit of mess.

Even better would be a more specific error message than a generic syntax error when groovy keywords are involved.
