### ISSUE TITLE
Spatial Polygons - Currently maximum supported number of points is 256

### ISSUE THREAD

**Issue by daveh101** [Azure/azure-documentdb-dotnet#541]
I'm running into the issue where a polygon can't support more than 256 points.  Is this likely to be improved upon, if so, when?

We are trying to use this for highly accurate town/county boundaries.  For example, a relatively small one that is being worked on right now has 455 points for it.  I'm sure this could be cut down a bit, but we would lose the accuracy if we did.  However, that won't necessarily help on bigger regions.

**Comment by ealsur** [comment]
Hi @daveh101, raising the maximum points for a polygon is currently in the roadmap although I don't have any official dates to share.

**Comment by ealsur** [comment]
Closing, please reopen if you have any more questions.
