### ISSUE TITLE
RequestRateTooLargeException with simple graph and queries

### ISSUE THREAD

**Issue by FSou1** [Azure/azure-documentdb-dotnet#544]
I've started to investigate Azure CosmosDB GraphAPI.

My graph consists of:
- Person vertexes: 10_000;
- Product vertexes: 500;
- Brand vertexes: 5;
- Made edges: 500;
- Bought edges: 200_000;

All of the data has been uploaded into a **single partition** (how wrong is it?).

Seems not very large, isn't it?

But, unfortunately, I'm not able to query the graph with next queries if the **throughtput less than 10_000 RU** due to RequestRateTooLargeException:

Let's find recommendations for John based on common and different bought products: 
```
g.V().has('name','John').as('his').
 out('bought').aggregate('self').
 in('bought').where(neq('his')).
 out('bought').where(without('self')).
 dedup().values('name')
```

Let's find products based on persons who bought >= 3 common products with John: 
```
g.V().has('name','John').as('his').
 out('bought').aggregate('self').
 in('bought').where(neq('his')).dedup()
 .group()
 .by().by(out('bought').where(within('self')).count().is(gt(2)))
 .select(keys).unfold()
 .out('bought').where(without('self'))

```
The queries above does not seem for me heavy weight as well.

Would you mind assisting me with recommendations and, probably, letting me know the root cause of my issue?

Thank you in advance,

**Comment by LuisBosquez** [comment]
Hello @FSou1,

The RU/s are related to the amount of objects (vertices and edges) that the running dataset retrieves before it creates a result, therefore, the way to reduce the amount of RU/s for a query would be to have a graph design that provides the result without using as many objects. Otherwise, the only choice would be to increase the RU/s for the account.

Thanks,
Luis

**Comment by FSou1** [comment]
Hello @LuisBosquez,

Do you have any suggestions how the graph like mine could be redesigned? I thought that it's small enough and RU/s should not be so expensive.
