### ISSUE TITLE
DocumentClient.OpenAsync() just hangs causing eventual OperationCancelledException.

### ISSUE THREAD

**Issue by Cephei** [Azure/azure-documentdb-dotnet#554]
- I'm running the latest emulator in a Windows 10 Pro VM using Parallels.
- I've installed the `DocumentDbEmulatorCertificate` on my host, OS X.
  I've assigned "always trust" for the localhost cert
- The cert contains a secondary `DNS Name` entry that has part of my Window's account first/last name. e.g DANIELGIOULCF28
- I've added a OS X `hosts` file entry for this DNS name to point to my VM.

1. I can successfully access CosmosDB Emulator explorer in my OS X browser without certificate issues.
2. I am running the emulator using `/AllowNetworkAccess`
3. The Windows firewall is completely off.
4. I am specifying the `/Key={}` key that I generated. I'm using this key in .NET Core 2.1.
5. I've tried the 1.9.1 and 2.0 preview nuget packages.
6. I know the key works because if I use the default, it tells me incorrect.

When I try to call `documentClient.OpenAsync()` the application just `awaits` until the task is cancelled, and quits.

**Comment by Cephei** [comment]
I still can't connect to the emulator over the network in `2.0.0-preview`. I can access the data explorer in my browser just fine. Is anyone able to connect to the emulator when it's in a VM or on the local network?

**Comment by christopheranderson** [comment]
Hey Cephei, I don't think this is related to the .NET SDK, but rather exposing the Emulator properly in parallels. 

Could you send me an email at chrande@microsoft.com and I'll connect you with our Emulator expert to see if we can work this out?

**Comment by Cephei** [comment]
Quick solution: try shutting down the Hyper-V service if you have it running and reset your CosmosDB data. `e.g. delete both certificates using mmc and delete your /AppData/Local/CosmosDBEmulator/ folder`

Then just:
1. restart the emulator using `/AllowNetworkAccess`
2. import the new emulator certificate into your host machine (if on OS X, set it to always be trusted)
