### ISSUE TITLE
Collection quota not consistent

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-dotnet#66]
When using the SDK to retrieve the document quota the results I get are inconsistent.  The collections are currently static so the values should not be changing.  The result is most noticeable when the queries are performed by my published web site rather than local host.

Here is a table showing a collection and the two sets of results I get.  When run a number of times the values alternate randomly between the two sets of values.

Collection   Mode          % Storage Used    Performance Level 
  
User2        Consistent     11.67                   S1 

User2        Consistent     14.48                   S1  

If we compare with the value shown on the portal, the portal shows 1.45 GB used (14.48%) which agrees with only one set of results.  I have not seen the portal show different values.
I currently only have one collection in the database that has anywhere near this amount of data so I cannot see it being a programming error and it is not restricted to this particular collection.

I am assuming that the information is coming from different replicas but why should there be such a large difference (if you expect there to be any difference at all!).

I am currently using Gateway mode.

**Comment by ryancrawcour** [comment]
I would agree with your statement that the reason for the difference is because of different replicas reporting their current state. What doesn't make sense though is that you say your collection is static i.e. you're not actively writing data, is this correct?

**Comment by Geetarman** [comment]
Yes that is correct. It is a collection I created but then have left alone as you were looking at another issue (sort by) in that collection.
The only time it will have been accessed is by the web page that list all the collections in the database and reports their status.

**Comment by ryancrawcour** [comment]
I will dig in to this some more and come back here with findings

**Comment by Geetarman** [comment]
Thanks. You do have access to that collection…

**Comment by Geetarman** [comment]
Just a thought here.  I originally had the collections with the default indexes (so hash on strings). I deleted it (or changed the index in the portal I can’t really be sure) and changed the index to range on strings.  Is it possible the replicas don’t have the same index settings – it might explain the difference in size.

**Comment by ryancrawcour** [comment]
That shouldn't happen. If that is what is causing this then we have a bug to resolve. Will take a look at User2 now and see what's happening.

**Comment by ryancrawcour** [comment]
We have tracked this down to a problem where secondary replicas weren't reporting the cost of the index storage. The primary (the one the portal uses) was. Therefore the difference being seen is data vs data + index. 

We are working on a fix for this which should be deployed soon.

**Comment by Geetarman** [comment]
That’s great . Thankyou

**Comment by ryancrawcour** [comment]
The backend fix for this has been deployed.
