### ISSUE TITLE
Read/Replace/Delete From Partition Using UriFactory Link

### ISSUE THREAD

**Issue by kspearrin** [Azure/azure-documentdb-dotnet#67]
My database implements a `HashPartitionResolver` similar to the example shown in the [sample code](https://github.com/Azure/azure-documentdb-net/blob/master/samples/code-samples/Partitioning/Program.cs).

This sample shows how to replace using `database.selfLink`, however, what if I want to use `UriFactory` with the database Id and document Id?

If I try something like this, I get "unexpected ResourceType" errors:

    await client.ReplaceDocumentAsync("/dbs/my_database/docs/my_document", myDocument);

I see no option to provide a partition key parameter anywhere like `CreateDocumentQuery<T>` has.

How do I replace a document while using a partitioning strategy with ID based links? I also see the same issue with the Delete and Read methods.

**Comment by arramac** [comment]
@kspearrin if you initialize like this, then you can use "id based routing" with PartitionResolver:
    this.client.PartitionResolvers[UriFactory.GetDatabaseUri("mydb")] = hashResolver

**Comment by kspearrin** [comment]
So this is the proper syntax for a document replace in that scenario?

    await client.ReplaceDocumentAsync("/dbs/my_database/docs/my_document", myDocument);

**Comment by arramac** [comment]
No, this is not supported. You have to call ResolveForCreate to get the collection, then call UriFactory to build the Uri for the Document. If you'd like, we can re-purpose or fork this issue to track this issue and being able to alternate between ID and SelfLinks with IPartitionResolver.

**Comment by kspearrin** [comment]
Ok great. That was what I was trying to get at here. It would be ideal if the PartitionResolver just handled this all for you, as long as you registered it using your database and collection ID links, rather then the self links.

**Comment by ryancrawcour** [comment]
We'll take a look and see if there is something we can do to improve the experience on Read, Delete and Replace. The difficulty is that we need the db, and the doc but not the collection because the resolver should figure that out.

**Comment by kspearrin** [comment]
So here's how I ended up getting this to work for me today, thanks to @arramac's suggestions above:

    var hashResolver = new HashPartitionResolver(
        "UserId",
        new[] { 
            UriFactory.CreateCollectionUri("db0", "coll0").OriginalString,
            UriFactory.CreateCollectionUri("db0", "coll1").OriginalString
        }
    );

    client.PartitionResolvers[UriFactory.CreateDatabaseUri("db0").OriginalString] = hashResolver;
    
    //
    // Elsewhere in the codebase where I only have access to client and the databaseId ...
    //
    
    // Creating
    
    var ryanDoc = await client.CreateDocumentAsync( UriFactory.CreateDatabaseUri(databaseId), new UserProfile("U4", ...));
    var ryanUser = (UserProfile)(dynamic)ryanDocument;
    
    // Elsewhere again, deleting ...
    
    var resolver = client.PartitionResolvers[UriFactory.CreateDatabaseUri(databaseId).OriginalString];
    var partitionKey = resolver.GetPartitionKey(ryanUser);
    var collectionIdLink = aresolver.ResolveForCreate(partitionKey);
    
    await client.DeleteDocumentAsync(collectionIdLink + "/docs/" + ryanUser.UserId);

**Comment by ryancrawcour** [comment]
yes, that will work. i'm keeping this issue open as a reminder to investigate better way to address this in the SDK.

**Comment by rnagpal** [comment]
Can you try the following if that works:

Document ryanDoc = client.CreateDocumentQuery(UriFactory.CreateDatabaseUri(databaseId),
                String.Format("SELECT * FROM ROOT r where r.UserId = \"{0}\"", ryanUser.UserId), null, ryanUser.UserId)
                .AsEnumerable()
                .FirstOrDefault();

await client.DeleteDocumentAsync(ryanDoc.AltLink);

Note that you have to use .NET SDK 1.5 for using the partitionKey parameter to the CreateDocumentQuery API taking the URI based links.

You can use this approach for cases where the document already exists which is true in case of Read/Delete/Replace to get the Document by passing in the partitionKey to the CreateDocumentQuery API but I agree that we could hide this complexity from you.

**Comment by kspearrin** [comment]
@rnagpal that will work, but that assumes that you are always dealing with a `Document` object. In my case, I am deailing with POCOs that are abstraccted away from `Document` (see `ryanUser` which is a `UserProfile`).

**Comment by rnagpal** [comment]
I agree. Though there is a overload for CreateDocumentQuery that return IQueryable<dynamic>, there is no such API for Delete/Replace/Read that can take that as a parameter and figure out the collection and do the necessary operation. We will add this to our product backlog.

Thanks for reporting!

**Comment by aliuy** [comment]
As of April 2016, it is advised to use server-side partitioning instead of client-side partition resolvers: https://azure.microsoft.com/en-us/documentation/articles/documentdb-partition-data/
