### ISSUE TITLE
Add a generic overload to ReadDocumentAsync

### ISSUE THREAD

**Issue by BrianVallelunga** [Azure/azure-documentdb-dotnet#71]
Currently, `CreateDocumentQuery` allows the results to be returned in a strongly typed manner using generics. Why doesn't `ReadDocumentAsync` have a similar overload? There should be a simple method to load a document of a known type without resorting to casting and dynamics.

This is especially important now that self links have been de-emphasized and we have the new UriFactory.

What I'm envisioning is:

```
var uri = UriFactory.CreateDocumentUri("DB", "Collection", "id");
var myDocument = await client.ReadDocumentAsync<MyDocument>(uri);
```

Alternatively, perhaps this should belong in a different method such as `GetDocument<T>(Uri link)`

**Comment by ryancrawcour** [comment]
This is a good suggestion, will look in to this for a future version.

**Comment by gorkar** [comment]
Is this on the roadmap?

**Comment by BrianVallelunga** [comment]
I'm surprised there's been no movement on this. It seems like this is the first API I would ever write for a document database. RavenDB has `T Load<T>(string id)` and it's literally the first thing in the getting started guide.

**Comment by mingaliu** [comment]
Thanks for your suggestion. Yes, we will plan to add this typed interface in next release.

**Comment by rnagpal** [comment]
The generic version of ReadDocument has been added and will be released as part of upcoming SDK release early next week.

**Comment by rnagpal** [comment]
@BrianVallelunga @gorkar  This has been added to 1.12.2 release of the SDK. The API is ReadDocumentAsync<T> that returns Task<DocumentResponse<T>> You can access the generic object from the Document property of the DocumentResponse<T>

**Comment by edwinf** [comment]
@rnagpal Is there a reason the new generic versions of the read were not added to the IDocumentClient interface and only exist on the concrete object itself?

**Comment by rnagpal** [comment]
@edwinf We didn't want to break the existing interface hence we didn't added it. We are working on options to have them exposed through interfaces or as extension methods.

**Comment by BrianVallelunga** [comment]
Thanks for the progress update. This will be useful.
