### ISSUE TITLE
ReliableReadDocumentClient throws "Request rate is large" exception from CreateDocumentCollectionQuery method

### ISSUE THREAD

**Issue by vladbilyk** [Azure/azure-documentdb-dotnet#78]
I see that `ReliableReadDocumentClient` implemented in Microsoft.Azure.Documents.Client.TransientFaultHandling, Version=1.2.0.0 throws "Request rate is large" exception from method `CreateDocumentCollectionQuery`, but as I believe it shouldn't. 

See code snippet below:

```c#
    static void Main(string[] args)
    {
        var ts = new List<Thread>();
        for (int j = 0; j < 100; ++j)
        {
            var t = new Thread(() =>
            {
                try
                {
					using (var client = CreateReliableClient())
					{
						Database database = client.CreateDatabaseQuery().Where(db => db.Id == DatabaseId).ToArray().FirstOrDefault();
						// the next line throws exception 
						DocumentCollection collection = client.CreateDocumentCollectionQuery(database.SelfLink).Where(c => c.Id == CollectionId).ToArray().FirstOrDefault();
					}
                }
                catch (Exception e)
                {
                    Console.WriteLine(e.InnerException.Message);
                }
            });
            t.Start();
            ts.Add(t);
        }

        foreach (var t in ts)
        {
            t.Join();
        }
    }

    static IReliableReadWriteDocumentClient CreateReliableClient()
    {
        return new DocumentClient(new Uri(EndpointUrl), AuthorizationKey)
            .AsReliable(new FixedInterval(10, TimeSpan.FromSeconds(1)));
    }
```

Could you please fix it?

**Comment by ryancrawcour** [comment]
You should open this as an issue in that component as it should handle this exception. 

However; l see a number of issues with the code you have provided. 
1) you shouldn't be creating a new instance of the document client 100 times as you are. you should create it once and reuse it. 

2) you shouldn't be doing a query for the database and collection 100 times like this. You should query for it once and cache the returned objects. You're wasting calls to the server (which cost you request units) and network roundtrips. 

In fact you don't even need to query for the database and collection anymore. With ID Based Routing you can get rid of using selfLinks and just use the id. Meaning when you want to read or write documents you don't need to first get the database and collection objects, you can now just do CreatDocumentAsync(UriFactory.CreateDocumentCollectionUri("dbid", "collid"), ...);

If you must have the db and collection object for some reason then you can also do ReadDatabaseAsync and ReadCollectionAsync which is more efficient than querying.

**Comment by vladbilyk** [comment]
@ryancrawcour, thank you for fast answer, could you please specify where exactly I should open the issue? Unfortunately I cannot find Microsoft.Azure.Documents.Client.TransientFaultHandling repository.

Regarding my code snippet, thank you for your observation - I've written it just to demonstrate how to reproduce the issue, it is not production code for sure :)

**Comment by ryancrawcour** [comment]
Sorry, I was under the impression it was. I will ask the library author to look at it. 
But you really should change your code above and address the issues I raised. Not only will you see a dramatic improvement in performance, much lower RU charges and much simpler code. Fixing the issues in your code will likely also not cause this throttling error you are seeing.

**Comment by vladbilyk** [comment]
Thank you for your assistance, I've already planned the requests optimization and id-based routing.
