### ISSUE TITLE
Resource not found errors

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-dotnet#80]
I have an application that has been working reliably for some time.  As of around 4.30 pm (UK time) on 24/11/2015 it started to exhibit resource not found errors.
Basically the application has a collection called "System" where it stores system settings.  It executes regularly against that collection to retrieve settings.  Most of those settings retrieve fine but a couple suddenly started to receive frequent (but not always!) resource not found errors.
I copied the entire contents of that collection to a new collection called "System2" and reconfigured the application to read from that collection instead and the errors no longer occur.
It leave me to believe there is an issue with one of the replicas or could there be something I am not doing correctly in my application?
I can grant access if you would like to look, otherwise I will delete and rebuild the "System" collection.

**Comment by TheDarkCode** [comment]
In the Azure Portal: How is your database account configured under "Settings" > "Default Consistency"?

**Comment by Geetarman** [comment]
It is configured for "Session".  I am not sure why the default consistency is relevant though...

**Comment by TheDarkCode** [comment]
Default consistency can be the cause of some problems that arise when you try to query the database but get back different results based on which replica is serving the results. Under session consistency any writes you just made will be immediately searchable, however others who attempt to access those same writes may not be able to do so until all the replicas have been updated.

**Comment by Geetarman** [comment]
I am not performing writes - only reads.

**Comment by TheDarkCode** [comment]
Without any new writes, it could be due to a hardware failure at the datacenter. However, replicas are spread out to protect against isolated hardware failures. The backend should maintain the process of properly allocating replicas to always maintain a majority quorum. There are always at least one primary replica for accepting writes (used by the portal), and at least two secondary replicas for handling all reads.

The other alternative is that you are getting throttled and you may see the issue go away when you switch to an S2 or S3 tier.

**Comment by ryancrawcour** [comment]
We'll look in to this. Please email me at least one activity id for the failure.

**Comment by Geetarman** [comment]
Message: {\"Errors\":[\"Resource Not Found\"]}\r\nActivityId: a9bfc31b-db34-40e0-ab95-e4858d5cfc9e, 
Request URI: /apps/7d397473-3b24-4bb1-afff-6c023af05d38/services/2ea20b6e-179c-477e-8250-fbe86532a8b1/partitions/f3fc907a-18ce-4ed4-bf09-55dc54f06877/replicas/130928549434808689p"}

The above occurred just now.  Just to confirm since using the new ("System2") collection I have had no errors...

**Comment by ryancrawcour** [comment]
This seems to be related to an issue with the index that we've seen before and have fixed. Unclear right now why this only started showing itself recently. 

Doing a rebuild of the index should fix this problem. You can initiate a rebuild by changing the index policy of the collection(s) impacted. 

Change something like indeed mode from consistent to lazy. Or exclude a path in the where clause in the query you are running. Wait for the index to be rebuilt, and then change the index policy back again. 

You can do this in the portal, or via code. 
If you need assistance with this please let me know. 

Once you have done this please let me know if this fixed the issue. 

We'll investigate further as to why this issue just started showing up.

**Comment by Geetarman** [comment]
Adding and removing an exclude path didn't make any difference but changing the index mode from consistent to lazy and back again seems to have fixed it....
thanks for the prompt response!

**Comment by ryancrawcour** [comment]
Thanks for confirming. Apologies for the trouble caused.

**Comment by kraman-msft** [comment]
ResourceNotFound response is returned only when the resource doesn't exist in the system. Indexing doesn't have any impact on resource not found being returned.

If this issue is still happening can you post the following information to help debug further.

1) Operation being performed (i.e. Read Document / Create Document etc)
2) Resource id/name
3) Activity ID
4) Timestamp.
5) Account name.

**Comment by naveen0905** [comment]
We are also getting the same error. Operation being performed is "Read Documents using Linq Queries"

{"Errors":["Resource Not Found"]} ActivityId: 63240357-3964-4cd2-b571-cacecc68eeb5,

**Comment by naveen0905** [comment]
We are also getting the same error. We are reading the documents using Dotnet SDK 1.11.0.0 .  

{"Errors":["Resource Not Found"]} ActivityId: 63240357-3964-4cd2-b571-cacecc68eeb5, 

Below is the exception getting logged in AppInsights:

[{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Client.ClientExtensions+<ParseResponseAsync>d__4.MoveNext",
	"level": 0,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 1,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 2,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.GatewayStoreModel+<>c__DisplayClass10+<<InvokeAsync>b__f>d__12.MoveNext",
	"level": 3,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 4,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 5,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<>c__DisplayClass2+<<ExecuteAsync>b__0>d__4.MoveNext",
	"level": 6,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 7,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 8,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext",
	"level": 9,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext",
	"level": 10,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 11,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 12,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteAsync>d__a.MoveNext",
	"level": 13,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 14,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 15,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.GatewayStoreModel+<InvokeAsync>d__1f.MoveNext",
	"level": 16,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 17,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 18,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.GatewayStoreModel+<ProcessMessageAsync>d__2.MoveNext",
	"level": 19,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 20,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 21,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Routing.ClientCollectionCache+<ReadCollectionAsync>d__6.MoveNext",
	"level": 22,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 23,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 24,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<>c__DisplayClass2+<<ExecuteAsync>b__0>d__4.MoveNext",
	"level": 25,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 26,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 27,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext",
	"level": 28,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteRetry>d__1b.MoveNext",
	"level": 29,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 30,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 31,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.BackoffRetryUtility`1+<ExecuteAsync>d__a.MoveNext",
	"level": 32,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 33,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 34,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Common.CollectionCache+<>c__DisplayClass10+<<ResolveByNameAsync>b__f>d__12.MoveNext",
	"level": 35,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 36,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 37,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Common.AsyncCache`2+<GetAsync>d__6.MoveNext",
	"level": 38,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 39,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 40,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Common.CollectionCache+<ResolveCollectionAsync>d__0.MoveNext",
	"level": 41,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 42,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 43,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Query.DocumentQueryExecutionContextFactory+<CreateDocumentQueryExecutionContextAsync>d__3.MoveNext",
	"level": 44,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 45,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 46,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Linq.DocumentQuery`1+<CreateDocumentQueryExecutionContextAsync>d__12.MoveNext",
	"level": 47,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 48,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 49,
	"line": 0
},
{
	"assembly": "Microsoft.Azure.Documents.Client, Version=1.11.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35",
	"method": "Microsoft.Azure.Documents.Linq.DocumentQuery`1+<ExecuteNextPrivateAsync>d__18`1.MoveNext",
	"level": 50,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess",
	"level": 51,
	"line": 0
},
{
	"assembly": "mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089",
	"method": "System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification",
	"level": 52,
	"line": 0
},
{
	"assembly": "MS.IT.LNR.CommonLibrary, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
	"method": "MS.IT.LNR.CommonLibrary.DocumentDBHelper+<GetDocumentsAsync>d__19`1.MoveNext",
	"level": 53,
	"line": 0
}]

**Comment by Geetarman** [comment]
This issue is closed and I have not had that error since.  I would recommend you open a new issue for yourselves either here or on the DocumentDB MSDN forum...

**Comment by naveen0905** [comment]
Geetarman,

The issue which we are facing got resolved. It is an issue with our code.
