### ISSUE TITLE
Add ODM like mongoosejs

### ISSUE THREAD

**Issue by pacific202** [Azure/azure-documentdb-dotnet#82]
I'd like to propose an Object Document Mapper library added to the dotnet sdk, with functionality similar to the mongoose library for mongo/node ( http://mongoosejs.com/ ) or the morphia library for mongo/java ( https://github.com/mongodb/morphia )

Core functionality of a DDB ODM should include:

1. Simplified connection methods
2. Annotation definitions for POCO's
3. CRUD operations (w/ LINQ support)

It would also be nice to have:

1. External relationship mapping between objects
2. Plugin framework

**Comment by ryancrawcour** [comment]
There is already LINQ support. What additional LINQ support would you like?

**Comment by ryancrawcour** [comment]
What do you mean by "annotation definitions for POCOs"? Could you give an example, please.

**Comment by ryancrawcour** [comment]
What do you mean by "Simplified connection methods"? Could you give an example, please.

**Comment by pacific202** [comment]
1. I meant that the ODM shouldn't break LINQ support, rather complement it

2. Tags that would be attached to the POCO's to let the ODM know what to do with those fields (e.g. ID, Reference).  Here are the Morphia annotations:

     http://mongodb.github.io/morphia/1.0/guides/annotations/

3. Just like the two MongoDB libraries can be operational with a few lines of code, connecting to DocumentDB should be quick with this library too.  For example, it would be nice if this library would just create a database if it doesn't find the one that is requested.

**Comment by ryancrawcour** [comment]
Ok. Will take it under consideration. As it is not an issue with the current SDK, but a feature request for future could you please vote for this on https://feedback.azure.com/forums/263030-documentdb
