### ISSUE TITLE
Unable to import documents at the rate I should be able to

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-dotnet#83]
I am trying to import documents from an external source.  The collection that is being used to import into has performance level S3 - therefore 2500 request units.   The documents I am importing (which are in the main of very similar size - 1150 bytes) report a charge of 3.5 RU's on average when inserted.
Therefore I should be able to import at a rate of about 700 documents/sec.
The maximum rate I can seem to achieve is around 150 documents/sec.

I read in the documents to import from storage and when the document insert is commented out it flies so the issue appears to be with the insert into documentdb.  The code uses threads heavily but no matter how many threads I create the rate will not exceed this amount.

I also have tried the bulk import stored procedure found on this site but that has no effect , the rate is still about the same.
Note that this is all running from within a deployed Azure application.

Any suggestions why this might be?
(I know there is a documentdb import tool available on github but it doesn't satisfy my specific requirements)

**Comment by ryancrawcour** [comment]
Please use either stackoverflow  or MSDN support forums to ask these sort of questions. The forums have a much bigger community following, plus the answer becomes useful to others. Thanks.
