### ISSUE TITLE
Order by asc and desc give different results

### ISSUE THREAD

**Issue by Geetarman** [Azure/azure-documentdb-dotnet#89]
If I perform the following query 
 select c.id,c.TenantId,c.ObjectType from c where c.TenantId="James Industries PLC" order by c._ts asc

the query explorer returns a page of results with HasMoreResults = true

However, with the same query sorted desc
select c.id,c.TenantId,c.ObjectType from c where c.TenantId="James Industries PLC" order by c._ts desc

only 3 results were returned with the HasMoreResults flag set to false. There are 397343 objects that should match this query in the database. Screenshots to show this included.

The discrepancy varies.  I have paged through all the results asc at times and found that the number of results falls short by about 100 compared to when no sort is performed but this varies and at times shows no discrepancy at all.

Since the collection I am experiencing this on is highly dynamic I have created a copy of the collection which I can keep for you to inspect.  However, this collection gives different results.  In this case the asc query returns no results and HasMoreResults=false wheres the desc search returns a page and HasMoreResults=true.  Screenshots to show this also included.  Note that this copy was made by inserting all the documents into a new collection with no indexing policy and then applying the indexing policy later.

I can give you access details for the databases on request.

Here are the screenshots (original)
![org_orderbyasc](https://cloud.githubusercontent.com/assets/7965853/12510287/bd29906c-c100-11e5-970d-41e9fcf32671.png)
![org_orderbydesc](https://cloud.githubusercontent.com/assets/7965853/12510288/bd7f449e-c100-11e5-8461-dd5d2e0d5750.png)

copy
![cpy_orderbyasc](https://cloud.githubusercontent.com/assets/7965853/12510313/eab6d6b6-c100-11e5-8c09-c42f3ad5e87d.png)
![cpy_orderbydesc](https://cloud.githubusercontent.com/assets/7965853/12510315/ee15b124-c100-11e5-9049-25ed3a03505b.png)

**Comment by ryancrawcour** [comment]
Thanks for the detailed info on this issue. We’re currently deploying a hotfix related to Order By which may actually fix this issue. The deployment should be going out today or over the weekend. Will try reproduce this again next week.

**Comment by ryancrawcour** [comment]
we believe this has been resolved. 
the following test was run against the endpoint you shared and the values of 397343 was returned each time. 

`
static void Main(string[] args)
{
    using (client = new DocumentClient(new Uri(endpoint), key))
    {
        var queryToRun = "select c.id,c.TenantId,c.ObjectType from c where c.TenantId=\"James Industries PLC\"";

        int a = RunQuery(queryToRun).Result;
        Console.WriteLine("Results from a: " + a.ToString());

        int b = RunQuery(queryToRun + " order by c._ts asc").Result;
        Console.WriteLine("Results from b: " + b.ToString());

        int c = RunQuery(queryToRun + " order by c._ts desc").Result;
        Console.WriteLine("Results from c: " + c.ToString());
    }
}

static async Task<int> RunQuery(string queryToRun)
{
    var qry = client.CreateDocumentQuery(collectionUri, queryToRun, new FeedOptions { MaxItemCount = -1 }).AsDocumentQuery();
    int count = 0;
    while (qry.HasMoreResults)
    {
        count += (await qry.ExecuteNextAsync<Document>()).Count;
    }

    return count;
}
`

Please verify that the issue is resolved.

**Comment by Geetarman** [comment]
I’m afraid this is matching with the number of results I am seeing. I am getting 397350 using my code.
I will investigate this later today to see if there is  bug in my code or not.  The only difference I can see at the moment is that I think my code might still be specifying a specific MaxItemCount (it isn’t meant to be , it should have been updated to use -1 but I think it is being overridden by a web setting that I forgot to remove).  However, I have to finish some other work off first before I can do this – although due to the time difference I may have had the chance to investigate further by the time you read this….

Regards
Steve

**Comment by Geetarman** [comment]
SORRY! The data I was looking at was for a different collection.
I am assuming you looked at the collection ‘Users1-backup22.01.2016-08:37:52’ in which case my code does agree with the number you are getting (phew)!

In that case yes I agree the issue looks resolved.
