### ISSUE TITLE
Support for Skip

### ISSUE THREAD

**Issue by joakimskoog** [Azure/azure-documentdb-dotnet#92]
Please add Linq support for Skip since it would make it much easier, and possible at all in many scenarios, to use paging.

Example on how I would do it with Linq To Sql: `return query.Skip((pageNumber - 1) * pageSize).Take(pageSize);`

This is sadly not possible after switching to DocumentDB. Therefore I, and many others, would love it if you implemented support for `Skip`

**Comment by ryancrawcour** [comment]
Closing as it's not an issue but a feature request. Please vote for the request on our uservoice page. 

https://feedback.azure.com/forums/263030-documentdb
