### ISSUE TITLE
DeleteDocumentAsync throws NullReferenceException

### ISSUE THREAD

**Issue by ahmettahasakar** [Azure/azure-documentdb-dotnet#93]
Hello,

If I try to delete a nonexisting item like below 

```
public static Document DeleteItem(Guid Id)
        {
                Uri uri = UriFactory.CreateDocumentUri(DatabaseId, CollectionId, Id.ToString());
                return client.DeleteDocumentAsync(uri).Result;
            }
```

I get a NullReferenceException. but the documentation here https://msdn.microsoft.com/en-us/library/microsoft.azure.documents.client.documentclient.deletedocumentasync.aspx states that I should have received DocumentClientException. am I missing something?

**Comment by ryancrawcour** [comment]
What is the value of DatabaseId, CollectionId and Id? 
Could you please include the stack trace, or post a gist with a repro.
